// Copyright 2025 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
// Generated by lynx/tools/config/gen_config.py from lynx_config.yml

import { describe, it, expect } from 'vitest';
import { compilerOptionsKeys, configKeys } from '../index';

describe('type-config index', () => {
  it('should export correct keys and types', () => {
    expect(compilerOptionsKeys).toBeDefined();
    expect(configKeys).toBeDefined();
  });
  it('should have correct compilerOptionsKeys', () => {
    expect(compilerOptionsKeys.length).toBe(0);
    expect(compilerOptionsKeys).toEqual([]);
  });
  it('should have correct configKeys', () => {
    expect(configKeys.length).toBe(18);
    expect(configKeys).toEqual([
      'disableLongpressAfterScroll',
      'enableA11y',
      'enableAccessibilityElement',
      'enableCSSInheritance',
      'enableEndGestureAtLastFingerUp',
      'enableJsBindingApiThrowException',
      'enableListNewArchitecture',
      'enableNativeList',
      'enableNewClipMode',
      'enableNewGesture',
      'enableNewIntersectionObserver',
      'enableNewTransformOrigin',
      'enableReduceInitDataCopy',
      'enableRemoveComponentExtraData',
      'enableTextOverflow',
      'enableTextRefactor',
      'keyboardCallbackPassRelativeHeight',
      'removeDescendantSelectorScope',
    ]);
  });
});
