// Copyright 2025 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
// Generated by lynx/tools/config/gen_config.py from lynx_config.yml

import { describe, expectTypeOf, it } from 'vitest';
import { Config, CompilerOptions } from '../types/index';

describe('Test Config Types', () => {
  it('should have correct Config type', () => {
    expectTypeOf<Config>().toBeObject();
    expectTypeOf<Config>().toHaveProperty('disableLongpressAfterScroll').toEqualTypeOf<boolean | undefined>();
    expectTypeOf<Config>().toHaveProperty('enableA11y').toEqualTypeOf<boolean | undefined>();
    expectTypeOf<Config>().toHaveProperty('enableAccessibilityElement').toEqualTypeOf<boolean | undefined>();
    expectTypeOf<Config>().toHaveProperty('enableCSSInheritance').toEqualTypeOf<boolean | undefined>();
    expectTypeOf<Config>().toHaveProperty('enableEndGestureAtLastFingerUp').toEqualTypeOf<boolean | undefined>();
    expectTypeOf<Config>().toHaveProperty('enableJsBindingApiThrowException').toEqualTypeOf<boolean | undefined>();
    expectTypeOf<Config>().toHaveProperty('enableListNewArchitecture').toEqualTypeOf<boolean | undefined>();
    expectTypeOf<Config>().toHaveProperty('enableNativeList').toEqualTypeOf<boolean | undefined>();
    expectTypeOf<Config>().toHaveProperty('enableNewClipMode').toEqualTypeOf<boolean | undefined>();
    expectTypeOf<Config>().toHaveProperty('enableNewGesture').toEqualTypeOf<boolean | undefined>();
    expectTypeOf<Config>().toHaveProperty('enableNewIntersectionObserver').toEqualTypeOf<boolean | undefined>();
    expectTypeOf<Config>().toHaveProperty('enableNewTransformOrigin').toEqualTypeOf<boolean | undefined>();
    expectTypeOf<Config>().toHaveProperty('enableReduceInitDataCopy').toEqualTypeOf<boolean | undefined>();
    expectTypeOf<Config>().toHaveProperty('enableRemoveComponentExtraData').toEqualTypeOf<boolean | undefined>();
    expectTypeOf<Config>().toHaveProperty('enableTextOverflow').toEqualTypeOf<boolean | undefined>();
    expectTypeOf<Config>().toHaveProperty('enableTextRefactor').toEqualTypeOf<boolean | undefined>();
    expectTypeOf<Config>().toHaveProperty('keyboardCallbackPassRelativeHeight').toEqualTypeOf<boolean | undefined>();
    expectTypeOf<Config>().toHaveProperty('removeDescendantSelectorScope').toEqualTypeOf<boolean | undefined>();
  });
});

describe('Test Compile Options Types', () => {
  it('should have correct types', () => {
    expectTypeOf<CompilerOptions>().toBeObject();
  });
});
