# Copyright 2024 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.
import os
from typing import Callable

from core.builder.builder import Builder
from core.env.env import RTFEnv
from core.target.target import Target
from core.utils.log import Log
from core.utils.shell_runner import run_command_with_error_log
from core.base.result import Err, Ok
from core.base.constants import Constants


class GnBuilder(Builder):
    def __init__(self, args: [str], output: str, silent: bool = False):
        super().__init__()
        self.args = args
        self.output = output
        self.silent = silent
        self.generated_args = None

    def args_gn_path(self):
        return os.path.join(
            RTFEnv.get_project_root_path(), self.output, "args.gn"
        )

    def read_args_gn(self):
        # Read bytes: the content is only ever compared for equality, and
        # binary mode keeps a non-ASCII args.gn readable under any locale.
        try:
            with open(self.args_gn_path(), "rb") as args_gn:
                return args_gn.read()
        except OSError:
            return None

    def pre_action(self, skip: Callable[[], bool] = None):
        gn_gen_cmd = f'gn gen {self.output} --args="{" ".join(self.args)}"'
        result = run_command_with_error_log(
            gn_gen_cmd, silent=self.silent, error_msg="gn gen failed"
        )
        if result.returncode != 0:
            return Err(Constants.CALL_COMMAND_ERR, f"run {gn_gen_cmd} failed")
        # Remember what we generated so that build() can tell a genuinely broken
        # target apart from another process having regenerated our output dir.
        self.generated_args = self.read_args_gn()
        return Ok()

    def check_output_not_regenerated(self):
        """Detect another build regenerating our output directory.

        `gn gen` rewrites a directory wholesale. Because a native-ut run keeps
        invoking ninja for many minutes after its single `gn gen`, any other
        build that targets the same directory with different args (the other
        native-ut template, oliver/build_gn.py, the desktop explorer/Clay
        builds, ...) silently drops our targets from the graph. Ninja then
        reports a bare `unknown target`, which looks like a missing GN target
        rather than the collision it actually is.
        """
        if self.generated_args is None:
            return None
        current_args = self.read_args_gn()
        if current_args is None or current_args == self.generated_args:
            return None
        return (
            f"{self.output} was regenerated by another build while this run "
            "was in progress: its args.gn no longer matches the args this run "
            "generated. Do not run two gn builds that share an output "
            "directory at the same time."
        )

    def build(self, target: Target):
        Log.info(f"{target.name} start build!")
        for task in target.build_tasks:
            regenerated = self.check_output_not_regenerated()
            if regenerated is not None:
                Log.error(regenerated)
                return Err(Constants.CALL_COMMAND_ERR, regenerated)
            build_cmd = f"ninja -C {self.output} {task}"
            result = run_command_with_error_log(
                build_cmd, silent=self.silent, error_msg=f"{task} build failed"
            )
            if result.returncode != 0:
                return Err(Constants.CALL_COMMAND_ERR, f"{task} build failed!")
            if RTFEnv.env_map["os"] == "linux":
                target.target_path = os.path.join(
                    RTFEnv.get_project_root_path(),
                    self.output,
                    "exe.unstripped",
                    task,
                )
            else:
                target.target_path = os.path.join(
                    RTFEnv.get_project_root_path(), self.output, task
                )
            Log.success(f"{task} build success!")
            return Ok()
