// Copyright 2026 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

package org.lynxsdk.extension

class LynxExtensionRegistryGenerator {
    static String generate(String packageName, List<LynxExtensionInfo> extensions) {
        String providerEntries = extensions.collect {
            "      \"${it.providerClassName}\""
        }.join(',\n')
        if (providerEntries.length() == 0) {
            providerEntries = ''
        }
        """// Generated by org.lynxsdk.extension. Do not edit.
package ${packageName}.generated.extensions;

import android.content.Context;
import androidx.annotation.Keep;
import com.lynx.tasm.LynxViewBuilder;
import com.lynx.tasm.extension.LynxExtensionRegistry;

@Keep
public final class ExtensionRegistry {
  private static final String[] PROVIDERS = new String[] {
${providerEntries}
  };

  private ExtensionRegistry() {}

  public static void setupGlobal(Context context) {
    LynxExtensionRegistry.setupGlobal(context, PROVIDERS);
  }

  public static void setup(LynxViewBuilder builder) {
    LynxExtensionRegistry.setup(builder, PROVIDERS);
  }
}
"""
    }
}
