// Copyright 2026 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

package org.lynxsdk.extension

class LynxExtensionRegistryGenerator {
    static final String REGISTRY_PACKAGE_NAME = 'com.lynx.tasm.extension'
    static final String REGISTRY_CLASS_NAME = 'LynxAutolinkGenerated'

    static String generate(List<LynxExtensionInfo> extensions) {
        return generateRegistry(extensions)
    }

    static String generateRegistry(List<LynxExtensionInfo> extensions) {
        String providerEntries = extensions.collect {
            "      \"${it.providerClassName}\""
        }.join(',\n')
        if (providerEntries.length() == 0) {
            providerEntries = ''
        }
        """// Generated by org.lynxsdk.extension. Do not edit.
package ${REGISTRY_PACKAGE_NAME};

import android.content.Context;
import androidx.annotation.Keep;
import com.lynx.tasm.LynxViewBuilder;

@Keep
public final class ${REGISTRY_CLASS_NAME} {
  private static final String[] PROVIDERS = new String[] {
${providerEntries}
  };

  private ${REGISTRY_CLASS_NAME}() {}

  public static void setupGlobal(Context context) {
    LynxExtensionRegistry.setupGlobal(context, PROVIDERS);
  }

  public static void setup(LynxViewBuilder builder) {
    LynxExtensionRegistry.setup(builder, PROVIDERS);
  }
}
"""
    }
}
