packages:
  - '.'
  - 'js_libraries/*'
  - devtool/lynx_devtool/resources/devtool-switch
  - devtool/lynx_devtool/resources/lynx-logbox
  - devtool/lynx_devtool/resources/lynx-error-parser
  - devtool/lynx_devtool/resources/logbox-types
  - explorer/homepage
