#!/usr/bin/env python3
# Copyright 2025 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.

# """
# This script defines the project classes relative to project.json generated by gn.
# """

import sys
import os
import string
import logging

class Project:

    def __init__(self, project_json):
        self.targets = project_json['targets']
        self.build_settings = project_json['build_settings']
        self.toolchains = project_json["toolchains"]
        self.root_path = self.build_settings['root_path']
        self.build_path = os.path.join(self.root_path,
                                       self.build_settings['build_dir'][2:])

    def get_absolute_path(self, path):
        if path.startswith("//"):
            return self.root_path + path[1:]
        return path

    def instead_source_path_prefix(self, path):
        return self.get_absolute_path(path).replace(self.root_path,
                                                    "${ROOT_PATH}")

    def instead_source_path_prefix_list(self, paths_list):
        if len(paths_list) <= 0:
            return []
        return [self.instead_source_path_prefix(path) for path in paths_list]


class CMakeTargetType:

    def __init__(self, command, modifier, property_modifier, is_linkable,
                 is_dependency_barrier):
        self.command = command
        self.modifier = modifier
        self.property_modifier = property_modifier
        self.is_linkable = is_linkable
        self.is_dependency_barrier = is_dependency_barrier


CMakeTargetType.custom = CMakeTargetType('add_custom_target', 'SOURCES', None,
                                         False, False)

# See GetStringForOutputType in gn
cmake_target_types = {
    'unknown':
    CMakeTargetType.custom,
    'group':
    CMakeTargetType.custom,
    'executable':
    CMakeTargetType('add_executable', None, 'RUNTIME', True, True),
    'loadable_module':
    CMakeTargetType('add_library', 'MODULE', 'LIBRARY', True, True),
    'shared_library':
    CMakeTargetType('add_library', 'SHARED', 'LIBRARY', True, True),
    'static_library':
    CMakeTargetType('add_library', 'STATIC', 'ARCHIVE', True, False),
    'source_set':
    CMakeTargetType('add_library', 'OBJECT', None, False, False),
    'copy':
    CMakeTargetType.custom,
    'action':
    CMakeTargetType.custom,
    'action_foreach':
    CMakeTargetType.custom,
    'bundle_data':
    CMakeTargetType.custom,
    'create_bundle':
    CMakeTargetType.custom,
}

cmake_link_flags_tags = {
    'unknown': 'CMAKE_SHARED_LINKER_FLAGS',
    'executable': 'CMAKE_EXE_LINKER_FLAGS',
    'shared_library': 'CMAKE_SHARED_LINKER_FLAGS',
    'static_library': 'CMAKE_STATIC_LINKER_FLAGS',
}

source_file_types = {
    '.cc': 'cxx',
    '.cpp': 'cxx',
    '.cxx': 'cxx',
    '.c': 'c',
    '.s': 'asm',
    '.S': 'asm',
    '.asm': 'asm',
    '.o': 'obj',
    '.obj': 'obj',
}


class Metadata:

    def __init__(self, properties):
        metadata = properties.get('metadata', {})
        self.output_path = self.get_first_var(metadata.get('output_path', []),
                                              "")
        self.is_cmake_target = self.get_first_var(
            metadata.get('is_cmake_target', []), False)
        self.is_subspec_target = self.get_first_var(
            metadata.get('is_subspec_target', []), False)
        self.cmake_version = self.get_first_var(
            metadata.get('cmake_version', []), "")
        self.sub_cmake_target = metadata.get('sub_cmake_target', [])
        self.sub_cmake_target_and_link = metadata.get(
            'sub_cmake_target_and_link', [])
        self.find_and_link_packages = metadata.get('find_and_link_packages',
                                                   [])
        self.project_name = self.get_first_var(
            metadata.get('project_name', []), "")
        self.file_name = self.get_first_var(metadata.get('file_name', []), "")

    def get_first_var(self, var_list, default_val):
        return var_list[0] if len(var_list) > 0 else default_val


class Target:

    def __init__(self, gn_name, project):
        if not gn_name in project.targets.keys():
            logging.error('Can not find target %s in your gn scripts' %
                          (gn_name))
        self.gn_name = gn_name
        self.properties = project.targets[self.gn_name]
        self.gn_type = self.properties.get('type', None)
        self.metadata = Metadata(self.properties)
        self.output_name = self.properties.get('output_name', '')
        # gn attributes
        self.asmflags = self.properties.get('asmflags', [])
        self.cflags = self.properties.get('cflags', [])
        self.cflags_c = self.properties.get('cflags_c', [])
        self.cflags_cc = self.properties.get('cflags_cc', [])
        self.configs = self.properties.get('configs', [])
        self.defines = self.properties.get('defines', [])
        self.deps = self.properties.get('deps', [])
        self.include_dirs = self.properties.get('include_dirs', [])
        self.ldflags = self.properties.get('ldflags', [])
        self.lib_dirs = self.properties.get('lib_dirs', [])
        self.libs = self.properties.get('libs', [])
        self.sources = self.properties.get('sources', [])
        self.outputs = self.properties.get('outputs', [])
        self.script = self.properties.get('script', "")
        self.args = self.properties.get('args', [])
        self.response_file_contents = self.properties.get(
            'response_file_contents', [])
        self.declare_path = self.get_declare_path()
        self.dep_actions = set()

        # cmake attributes
        self.file_name = self.metadata.file_name
        self.project_name = self.metadata.project_name
        self.is_cmake_target = self.metadata.is_cmake_target
        self.cmake_name = self.get_cmake_target_name()
        self.cmake_type = cmake_target_types.get(self.gn_type, None)
        self.deps_packages, self.link_modules = self.find_all_deps_packages(
            self.metadata.find_and_link_packages, project)
        self.output_path = self.metadata.output_path
        self.cmake_version = self.metadata.cmake_version
        self.sub_cmake_target = self.collect_sub_cmake_target()

        # subspec attributes
        self.is_subspec_target = self.metadata.is_subspec_target

    def get_declare_path(self):
        module_path = self.gn_name.split(':')[0]
        sub_path = module_path[2:]
        if len(sub_path) > 0:
            module_path += '/'
        return module_path

    def collect_sub_cmake_target(self):
        need_link_sub_cmake_targets = self.metadata.sub_cmake_target_and_link
        for sub in need_link_sub_cmake_targets:
            self.libs.append(Target(sub, project).output_name)
        return need_link_sub_cmake_targets + self.metadata.sub_cmake_target

    def should_check_sources_target(self, target):
        return target.gn_type in [
            "executable", "loadable_module", "shared_library",
            "static_library", "source_set", "group"
        ]

    def is_useful_target(self, target):
        if not self.should_check_sources_target(target):
            return True
        useful = False
        if len(target.sources) > 0:
            for source in target.sources:
                if not source.endswith('.h') and not source.endswith('.hpp'):
                    useful = True
                    break
        return useful

    def get_directly_dependencies(self, project):
        """
    Find directly dependencies of this target
    """
        dep_targets = set()
        for dep in self.deps:
            dep_target = Target(dep, project)
            dep_targets.add(dep_target)
        return dep_targets

    def find_all_dependencies(self, project):
        """
    Find all dependencies starting with this target
    """
        all_deps_source_targets = set()
        all_deps_binary_targets = set()
        has_checked_targets = {}
        has_checked_targets[self.gn_name] = self
        if self.is_useful_target(self):
            all_deps_source_targets.add(self)
        for dep in self.deps:
            dep_target = Target(dep, project)
            if dep_target.gn_type == 'action':
                self.dep_actions.add(dep_target.cmake_name)
            self.recursive_find_dependent_targets(project, dep_target,
                                                  all_deps_source_targets,
                                                  all_deps_binary_targets,
                                                  has_checked_targets)
            self.dep_actions = self.dep_actions.union(dep_target.dep_actions)
        return all_deps_source_targets, all_deps_binary_targets

    def recursive_find_dependent_targets(self, project, main_target,
                                         all_deps_source_targets,
                                         all_deps_binary_targets,
                                         has_checked_targets):
        """
    Recursive search dependencies
    """
        # Check whether the current target has been found before to avoid an infinite loop.
        if main_target.gn_name in has_checked_targets.keys():
            main_target.dep_actions = has_checked_targets[
                main_target.gn_name].dep_actions
            return 0
        else:
            has_checked_targets[main_target.gn_name] = main_target
        # If the current target's type is cmake_target or a dependency barrier, add it to all_deps_binary_targets, and needn't to find its dependencies.
        # Else, add it to all_deps_source_targets, and recursively find its dependencies.
        if main_target.is_cmake_target or main_target.cmake_type.is_dependency_barrier:
            all_deps_binary_targets.add(main_target)
            return 0
        else:
            if self.is_useful_target(main_target):
                all_deps_source_targets.add(main_target)
                self.add_deps_packages(main_target)
        for dep in main_target.deps:
            dep_target = Target(dep, project)
            if dep_target.gn_type == 'action':
                main_target.dep_actions.add(dep_target.cmake_name)
            r = self.recursive_find_dependent_targets(project, dep_target,
                                                      all_deps_source_targets,
                                                      all_deps_binary_targets,
                                                      has_checked_targets)
            main_target.dep_actions = main_target.dep_actions.union(
                dep_target.dep_actions)
            if r != 0:
                return r
        return 0

    def find_all_user_defines(self, target_list):
        """
    Find custom macros
    """
        all_defines = set()
        for target in target_list:
            if target.gn_type != 'shared_library':
                defines = target.defines
                all_defines.update(defines)
        return all_defines

    def add_deps_packages(self, target):
        if len(target.deps_packages.keys()) > 0:
            for package_name in target.deps_packages.keys():
                if package_name in self.deps_packages.keys():
                    self.deps_packages[package_name][
                        0] = self.deps_packages[package_name][
                            0] or target.deps_packages[package_name][0]
                    self.deps_packages[package_name][1] = list(
                        set(self.deps_packages[package_name][1])
                        | set(target.deps_packages[package_name][1]))
                else:
                    self.deps_packages[package_name] = target.deps_packages[
                        package_name]
        if len(target.link_modules) > 0:
            self.link_modules = set(
                set(self.link_modules) | set(target.link_modules))

    def find_all_deps_packages(self, find_and_link_packages, project):
        packages = {}
        modules = set()
        if len(find_and_link_packages) > 0:
            for package in find_and_link_packages:
                package_name = package[0]
                search_paths = project.instead_source_path_prefix_list(
                    package[1])
                configd = package[2] == "cmake::configd"
                start_index = 3 if configd else 2
                for module in package[start_index:]:
                    modules.add(module)
                packages[package_name] = [configd, search_paths]
        return packages, modules

    def find_first_of(self, s, a):
        return min(s.find(i) for i in a if i in s)

    def cmake_target_escape(self, a):
        """Escapes the string 'a' for use as a CMake target name.

    CMP0037 in CMake 3.0 restricts target names to "^[A-Za-z0-9_.:+-]+$"
    The ':' is only allowed for imported targets.
    """

        def Escape(c):
            if c in string.ascii_letters or c in string.digits or c in '_.+-':
                return c
            return '__'

        return ''.join([Escape(c) for c in a])

    def get_cmake_target_name(self):
        path_separator = self.find_first_of(self.gn_name, (':', '('))
        location = None
        name = None
        toolchain = None
        if not path_separator:
            location = self.gn_name[2:]
        else:
            location = self.gn_name[2:path_separator]
            toolchain_separator = self.gn_name.find('(', path_separator)
            if toolchain_separator == -1:
                name = self.gn_name[path_separator + 1:]
            else:
                if toolchain_separator > path_separator:
                    name = self.gn_name[path_separator + 1:toolchain_separator]
                assert self.gn_name.endswith(')')
                toolchain = self.gn_name[toolchain_separator + 1:-1]
        assert location or name

        cmake_target_name = None
        if location.endswith('/' + name):
            cmake_target_name = location
        elif location:
            cmake_target_name = location + '_' + name
        else:
            cmake_target_name = name
        if toolchain:
            cmake_target_name += '--' + toolchain
        return self.cmake_target_escape(cmake_target_name)
