// Copyright 2026 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

import fs from 'node:fs';
import path from 'node:path';

import type {
  HarmonyLibraryInfo,
  PrepareHarmonyAutolinkOptions,
  PrepareHarmonyAutolinkResult,
} from './types.js';
import { parseJson5File, scanHarmonyLibraries } from './scanner.js';

const REGISTRY_MODULE_NAME = 'lynx_library_registry';
const REGISTRY_PACKAGE_NAME = '@lynx/lynx_library_registry';
const DEFAULT_LYNX_DEPENDENCY = '@param:dependencies.lynx_version';

interface BuildProfile {
  modules?: BuildProfileModule[];
  [key: string]: unknown;
}

interface BuildProfileModule {
  name: string;
  srcPath: string;
  targets?: unknown[];
  [key: string]: unknown;
}

interface ModuleManifest {
  module?: {
    type?: unknown;
  };
}

interface OhPackageManifest {
  dependencies?: Record<string, unknown>;
  [key: string]: unknown;
}

interface GeneratorState {
  modules: Array<{
    name: string;
    srcPath: string;
  }>;
}

export function prepareHarmonyAutolink(
  options: PrepareHarmonyAutolinkOptions = {}
): PrepareHarmonyAutolinkResult {
  const projectRoot = fs.realpathSync(
    path.resolve(options.projectRoot ?? process.cwd())
  );
  const outputDir = path.resolve(
    projectRoot,
    options.outputDir ?? path.join('.lynx', 'autolink', REGISTRY_MODULE_NAME)
  );
  const libraries = scanHarmonyLibraries(projectRoot);
  const buildProfilePath = path.join(projectRoot, 'build-profile.json5');
  const buildProfile = parseJson5File<BuildProfile>(buildProfilePath);
  const originalModules = normalizeModules(
    buildProfile.modules,
    buildProfilePath
  );
  const consumerModuleDir = resolveConsumerModule(
    projectRoot,
    originalModules,
    options.consumerModule
  );

  const generatedFiles = writeRegistryHar(
    outputDir,
    libraries,
    options.lynxDependency ?? DEFAULT_LYNX_DEPENDENCY
  );
  const generatedModules = wireBuildProfile(
    projectRoot,
    buildProfilePath,
    buildProfile,
    originalModules,
    libraries,
    outputDir
  );
  wireConsumerModule(consumerModuleDir, outputDir);
  const generatorState: GeneratorState = { modules: generatedModules };
  writeFile(
    path.join(outputDir, '.lynx-autolink-state.json'),
    `${JSON.stringify(generatorState, null, 2)}\n`
  );
  generatedFiles.push(path.join(outputDir, '.lynx-autolink-state.json'));

  return {
    libraries,
    consumerModuleDir,
    outputDir,
    generatedFiles,
  };
}

export function generateRegistrySource(
  libraries: HarmonyLibraryInfo[]
): string {
  const sortedLibraries = [...libraries].sort((left, right) =>
    left.npmName.localeCompare(right.npmName)
  );
  const imports = sortedLibraries
    .map(
      (library, index) =>
        `import { LynxLibraryProviderImpl as LynxLibraryProvider${index} } from '${library.ohPackageName}';`
    )
    .join('\n');
  const providers = sortedLibraries
    .map(
      (library, index) => `  {
    packageName: '${escapeSingleQuoted(library.npmName)}',
    provider: new LynxLibraryProvider${index}(),
  },`
    )
    .join('\n');
  const importBlock = imports.length === 0 ? '' : `${imports}\n`;

  return `// Generated by @lynx/lynx-library-plugin. Do not edit.
import { LynxLibraryProviderEntry, LynxLibraryRegistry } from '@lynx/lynx';
${importBlock}
const PROVIDERS: LynxLibraryProviderEntry[] = [
${providers}
];

export function setupGlobal(): void {
  LynxLibraryRegistry.setupGlobal(PROVIDERS);
}
`;
}

function writeRegistryHar(
  outputDir: string,
  libraries: HarmonyLibraryInfo[],
  lynxDependency: string
): string[] {
  const dependencies: Record<string, string> = {
    '@lynx/lynx': lynxDependency,
  };
  for (const library of [...libraries].sort((left, right) =>
    left.npmName.localeCompare(right.npmName)
  )) {
    dependencies[library.ohPackageName] = fileDependency(
      outputDir,
      library.harmonyDir
    );
  }

  const files = new Map<string, string>([
    [
      'oh-package.json5',
      json5({
        name: REGISTRY_PACKAGE_NAME,
        version: '0.0.0',
        main: 'Index.ets',
        license: 'Apache-2.0',
        dependencies,
      }),
    ],
    [
      'build-profile.json5',
      json5({
        apiType: 'stageMode',
        buildOption: {
          arkOptions: {
            byteCodeHar: false,
          },
        },
        targets: [{ name: 'default' }],
      }),
    ],
    [
      'hvigorfile.ts',
      `import { harTasks } from '@ohos/hvigor-ohos-plugin';

export default {
  system: harTasks,
  plugins: [],
};
`,
    ],
    [
      'Index.ets',
      `export { setupGlobal } from './src/main/ets/Index';
`,
    ],
    [
      'src/main/module.json5',
      json5({
        module: {
          name: REGISTRY_MODULE_NAME,
          type: 'har',
          deviceTypes: ['default', 'tablet', '2in1'],
        },
      }),
    ],
    ['src/main/ets/Index.ets', generateRegistrySource(libraries)],
  ]);

  const generatedFiles: string[] = [];
  for (const [relativePath, content] of files) {
    const filePath = path.join(outputDir, relativePath);
    writeFile(filePath, content);
    generatedFiles.push(filePath);
  }
  return generatedFiles;
}

function wireBuildProfile(
  projectRoot: string,
  buildProfilePath: string,
  buildProfile: BuildProfile,
  originalModules: BuildProfileModule[],
  libraries: HarmonyLibraryInfo[],
  outputDir: string
): GeneratorState['modules'] {
  const statePath = path.join(outputDir, '.lynx-autolink-state.json');
  const previousState = fs.existsSync(statePath)
    ? parseJson5File<GeneratorState>(statePath)
    : { modules: [] };
  const previousEntries = new Set(
    previousState.modules.map(
      (module) => `${module.name}\n${normalizeRelativePath(module.srcPath)}`
    )
  );
  const modules = originalModules.filter(
    (module) =>
      !previousEntries.has(
        `${module.name}\n${normalizeRelativePath(module.srcPath)}`
      )
  );
  const defaultTargets = modules[0]?.targets;
  const generatedModules: BuildProfileModule[] = [];

  for (const library of libraries) {
    generatedModules.push({
      name: library.moduleName,
      srcPath: projectRelativePath(projectRoot, library.harmonyDir),
      ...(defaultTargets == null ? {} : { targets: defaultTargets }),
    });
  }
  generatedModules.push({
    name: REGISTRY_MODULE_NAME,
    srcPath: projectRelativePath(projectRoot, outputDir),
    ...(defaultTargets == null ? {} : { targets: defaultTargets }),
  });

  const addedModules: BuildProfileModule[] = [];
  for (const generatedModule of generatedModules) {
    if (addModule(modules, generatedModule, projectRoot)) {
      addedModules.push(generatedModule);
    }
  }
  buildProfile.modules = modules;
  writeFile(buildProfilePath, json5(buildProfile));
  return addedModules.map((module) => ({
    name: module.name,
    srcPath: module.srcPath,
  }));
}

function addModule(
  modules: BuildProfileModule[],
  candidate: BuildProfileModule,
  projectRoot: string
): boolean {
  const candidatePath = path.resolve(projectRoot, candidate.srcPath);
  const samePath = modules.find(
    (module) => path.resolve(projectRoot, module.srcPath) === candidatePath
  );
  if (samePath != null) {
    if (samePath.name === candidate.name) {
      return false;
    }
    throw new Error(
      `Harmony module path '${candidate.srcPath}' is already mapped as ${samePath.name}; cannot map ${candidate.name}`
    );
  }
  const sameName = modules.find((module) => module.name === candidate.name);
  if (sameName != null) {
    throw new Error(
      `Harmony module '${candidate.name}' is already mapped to ${sameName.srcPath}; cannot map ${candidate.srcPath}`
    );
  }
  modules.push(candidate);
  return true;
}

function wireConsumerModule(
  consumerModuleDir: string,
  outputDir: string
): void {
  const ohPackagePath = path.join(consumerModuleDir, 'oh-package.json5');
  const ohPackage = parseJson5File<OhPackageManifest>(ohPackagePath);
  const dependencies = ohPackage.dependencies ?? {};
  dependencies[REGISTRY_PACKAGE_NAME] = fileDependency(
    consumerModuleDir,
    outputDir
  );
  ohPackage.dependencies = dependencies;
  writeFile(ohPackagePath, json5(ohPackage));
}

function resolveConsumerModule(
  projectRoot: string,
  modules: BuildProfileModule[],
  configuredModule: string | undefined
): string {
  if (configuredModule != null) {
    const moduleDir = path.resolve(projectRoot, configuredModule);
    assertConsumerModule(moduleDir);
    return moduleDir;
  }

  const hapModules = modules
    .map((module) => path.resolve(projectRoot, module.srcPath))
    .filter((moduleDir) => {
      const moduleManifestPath = path.join(moduleDir, 'src/main/module.json5');
      if (!fs.existsSync(moduleManifestPath)) {
        return false;
      }
      return (
        parseJson5File<ModuleManifest>(moduleManifestPath).module?.type ===
        'entry'
      );
    });
  if (hapModules.length !== 1) {
    throw new Error(
      `Expected exactly one entry consumer module, found ${hapModules.length}; configure consumerModule explicitly`
    );
  }
  assertConsumerModule(hapModules[0] as string);
  return hapModules[0] as string;
}

function assertConsumerModule(moduleDir: string): void {
  if (!fs.existsSync(path.join(moduleDir, 'oh-package.json5'))) {
    throw new Error(`Consumer module ${moduleDir} is missing oh-package.json5`);
  }
  const moduleManifestPath = path.join(moduleDir, 'src/main/module.json5');
  if (
    !fs.existsSync(moduleManifestPath) ||
    parseJson5File<ModuleManifest>(moduleManifestPath).module?.type !== 'entry'
  ) {
    throw new Error(
      `Consumer module ${moduleDir} must contain an entry src/main/module.json5`
    );
  }
}

function normalizeModules(
  modules: BuildProfileModule[] | undefined,
  buildProfilePath: string
): BuildProfileModule[] {
  if (!Array.isArray(modules)) {
    throw new Error(`Missing modules array in ${buildProfilePath}`);
  }
  return modules.map((module) => {
    if (
      typeof module?.name !== 'string' ||
      typeof module?.srcPath !== 'string'
    ) {
      throw new Error(`Invalid module entry in ${buildProfilePath}`);
    }
    return module;
  });
}

function projectRelativePath(projectRoot: string, target: string): string {
  const relative = normalizeRelativePath(path.relative(projectRoot, target));
  return relative.startsWith('.') ? relative : `./${relative}`;
}

function fileDependency(fromDir: string, targetDir: string): string {
  const relative = normalizeRelativePath(path.relative(fromDir, targetDir));
  return `file:${relative.startsWith('.') ? relative : `./${relative}`}`;
}

function normalizeRelativePath(value: string): string {
  return value.split(path.sep).join('/');
}

function json5(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function writeFile(filePath: string, content: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  if (
    !fs.existsSync(filePath) ||
    fs.readFileSync(filePath, 'utf8') !== content
  ) {
    fs.writeFileSync(filePath, content);
  }
}

function escapeSingleQuoted(value: string): string {
  return value.replaceAll('\\', '\\\\').replaceAll("'", "\\'");
}
