// Copyright 2021 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

#include "clay/ui/component/intersection_observer_manager.h"

#include <algorithm>
#include <cmath>
#include <memory>
#include <utility>

#include "clay/public/value.h"
#include "clay/ui/component/base_view.h"
#include "clay/ui/component/expose_manager/expose_observer.h"
#include "clay/ui/component/intersection_observer.h"
#include "clay/ui/component/page_view.h"

namespace clay {

namespace {

constexpr double kLargeExposureTargetViewportAreaRatio = 0.5;

bool HasValidPositiveArea(const BaseView* view) {
  return view && std::isfinite(view->Width()) &&
         std::isfinite(view->Height()) && view->Width() > 0 &&
         view->Height() > 0;
}

double Area(const BaseView* view) {
  return static_cast<double>(view->Width()) * view->Height();
}

}  // namespace

void IntersectionObserverManager::StopExposure(bool send_event) {
  // Do not return only because exposure is already stopped. stop(false) keeps
  // an active exposure open, so a later stop(true) must still be allowed to
  // close it.
  exposure_stopped_ = true;
  for (auto& it : expose_observers_map_) {
    it.second->StopExposure(send_event);
  }

  if (send_event && !expose_observers_map_.empty()) {
    // Flush the disappear events generated by StopExposure synchronously, so
    // the current exposure cycle is closed before this stop task completes.
    owner_page_view_->SendGlobalExposureEvent();
  }
}

void IntersectionObserverManager::ResumeExposure() {
  // Native resumeExposure does not return early based on the previous stopped
  // state and re-adds exposure detection to the run loop. Keep forwarding it
  // and coalesce the actual check at BeginFrame below.
  exposure_stopped_ = false;
  for (auto& it : expose_observers_map_) {
    it.second->ResumeExposure();
  }

  if (!expose_observers_map_.empty()) {
    // Defer the visibility check to BeginFrame so repeated resume calls before
    // the next frame are coalesced into one exposure transition.
    last_expose_time_ = -1;
    owner_page_view_->RequestPaint();
  }
}

void IntersectionObserverManager::AddObserver(
    std::unique_ptr<IntersectionObserver> observer) {
  if (observer->IsOfType(IntersectionObserver::kIntersectionObserver)) {
    intersection_observers_.emplace_back(std::move(observer));
  } else if (observer->IsOfType(IntersectionObserver::kExposeObserver)) {
    std::unique_ptr<ExposeObserver> p(
        static_cast<ExposeObserver*>(observer.release()));
    if (exposure_stopped_) {
      p->StopExposure(false);
    }
    p->SetExposureHostVisible(exposure_host_visible_);
    expose_observers_map_.emplace(p.get()->GetAttachedView(), std::move(p));
  }
}

void IntersectionObserverManager::SetExposureHostVisible(bool visible) {
  if (exposure_host_visible_ == visible) {
    return;
  }
  exposure_host_visible_ = visible;
  for (auto& it : expose_observers_map_) {
    it.second->SetExposureHostVisible(visible);
  }

  bool deferred_target_notified = false;
  if (visible && !host_hidden_first_add_pending_views_.empty()) {
    const std::vector<BaseView*> pending_targets(
        host_hidden_first_add_pending_views_.begin(),
        host_hidden_first_add_pending_views_.end());
    host_hidden_first_add_pending_views_.clear();
    for (auto* target : pending_targets) {
      if (TryReconcileDeferredDirectPageChildAfterHostVisible(target)) {
        deferred_target_notified = true;
      }
    }
  }

  if (visible && !expose_observers_map_.empty()) {
    last_expose_time_ = -1;
    owner_page_view_->RequestPaint();
  }
  if (deferred_target_notified) {
    owner_page_view_->SendGlobalExposureEvent();
  }
}

void IntersectionObserverManager::EraseExposeObserver(
    BaseView* view, const ExposeObserver* target) {
  if (view) {
    layout_fast_path_candidate_views_.erase(view);
    layout_fast_path_attempted_views_.erase(view);
    host_hidden_first_add_pending_views_.erase(view);
    expose_observers_map_.erase(view);
  } else if (target) {
    for (auto iter = expose_observers_map_.begin();
         iter != expose_observers_map_.end();) {
      if ((iter->second).get() == target) {
        auto* attached_view = iter->second->GetAttachedView();
        layout_fast_path_candidate_views_.erase(attached_view);
        layout_fast_path_attempted_views_.erase(attached_view);
        host_hidden_first_add_pending_views_.erase(attached_view);
        iter = expose_observers_map_.erase(iter);
        return;
      } else {
        ++iter;
      }
    }
  }
}

void IntersectionObserverManager::RemoveObserver(
    const IntersectionObserver* target) {
  if (target->IsOfType(IntersectionObserver::kIntersectionObserver)) {
    EraseObserver(intersection_observers_, nullptr, target);
  } else if (target->IsOfType(IntersectionObserver::kExposeObserver)) {
    EraseExposeObserver(target->GetAttachedView());
  }
}

void IntersectionObserverManager::RemoveAll(BaseView* view) {
  EraseObserver(intersection_observers_, view, nullptr);
  EraseExposeObserver(view);
}

void IntersectionObserverManager::RemoveIntersectionObserver(BaseView* view) {
  EraseObserver(intersection_observers_, view, nullptr);
}

void IntersectionObserverManager::RemoveExposeObserver(BaseView* view) {
  EraseExposeObserver(view);
}

void IntersectionObserverManager::SetExposureFrequency(int freq) {
  expose_min_time_gap_ms_ = 1000 / std::min(1, std::max(freq, 60));
}

void IntersectionObserverManager::SetExposureUIMarginEnabled(bool enabled) {
  exposure_ui_margin_enabled_ = enabled;
}

bool IntersectionObserverManager::UpdateExposeData(const char* attr_key,
                                                   const clay::Value& value,
                                                   BaseView* target_view) {
  auto target = expose_observers_map_.find(target_view);
  if (target != expose_observers_map_.end()) {
    return ((target->second).get())->UpdateExposeData(attr_key, value);
  }
  return false;
}

bool IntersectionObserverManager::HasExposeObserver(BaseView* view) {
  return expose_observers_map_.count(view) > 0;
}

void IntersectionObserverManager::NotifyObservers() {
  NotifyObserver(intersection_observers_,
                 &IntersectionObserver::CheckForIntersectionWithTarget,
                 nullptr);
  if (exposure_stopped_ || !exposure_host_visible_ ||
      expose_observers_map_.empty()) {
    return;
  }

  auto now = fml::TimePoint::Now().ToEpochDelta().ToMicroseconds();
  if (last_expose_time_ == -1 ||
      (now - last_expose_time_ > expose_min_time_gap_ms_)) {
    last_expose_time_ = now;
    NotifyExposures(&IntersectionObserver::CheckForIntersectionWithTarget);
  }
}

void IntersectionObserverManager::NotifyTargetAttached(BaseView* view) {
  NotifyAllObserver(&IntersectionObserver::OnAttach, view);
}

void IntersectionObserverManager::NotifyTargetDetached(BaseView* view) {
  layout_fast_path_candidate_views_.erase(view);
  layout_fast_path_attempted_views_.erase(view);
  host_hidden_first_add_pending_views_.erase(view);
  NotifyAllObserver(&IntersectionObserver::OnDetach, view);
}

void IntersectionObserverManager::ReconcileExposureForTarget(BaseView* view) {
  if (view) {
    layout_fast_path_candidate_views_.erase(view);
    layout_fast_path_attempted_views_.insert(view);
  }
  if (exposure_stopped_ || !exposure_host_visible_ || !view ||
      !view->attach_to_tree()) {
    return;
  }
  NotifyExposures(&IntersectionObserver::CheckForIntersectionWithTarget, view);
}

bool IntersectionObserverManager::TryNotifyDirectPageChildOnFirstAdd(
    BaseView* target) {
  const bool direct_page_child =
      target && owner_page_view_ && target->Parent() == owner_page_view_;
  auto observer_it = expose_observers_map_.find(target);
  auto* observer = observer_it == expose_observers_map_.end()
                       ? nullptr
                       : observer_it->second.get();
  const bool has_uiappear = observer && observer->HasUIAppearCallback();

  if (!direct_page_child) {
    return false;
  }
  if (!observer) {
    return false;
  }
  if (!has_uiappear) {
    return false;
  }
  if (!target->attach_to_tree()) {
    return false;
  }
  if (exposure_stopped_) {
    return false;
  }
  if (!exposure_host_visible_) {
    host_hidden_first_add_pending_views_.insert(target);
    return false;
  }
  host_hidden_first_add_pending_views_.erase(target);
  layout_fast_path_candidate_views_.erase(target);
  layout_fast_path_attempted_views_.insert(target);
  if (observer->IsExposed()) {
    owner_page_view_->SendGlobalExposureEvent();
    return true;
  }
  if (!observer->TryNotifyAppearWithoutGeometry()) {
    return false;
  }

  owner_page_view_->SendGlobalExposureEvent();
  return true;
}

bool IntersectionObserverManager::
    TryReconcileDeferredDirectPageChildAfterHostVisible(BaseView* target) {
  const bool direct_page_child =
      target && owner_page_view_ && target->Parent() == owner_page_view_;
  auto observer_it = expose_observers_map_.find(target);
  auto* observer = observer_it == expose_observers_map_.end()
                       ? nullptr
                       : observer_it->second.get();
  const bool has_uiappear = observer && observer->HasUIAppearCallback();

  if (!direct_page_child) {
    return false;
  }
  if (!observer) {
    return false;
  }
  if (!has_uiappear) {
    return false;
  }
  if (!target->attach_to_tree()) {
    return false;
  }
  if (exposure_stopped_) {
    return false;
  }
  if (!exposure_host_visible_) {
    return false;
  }
  layout_fast_path_candidate_views_.erase(target);
  layout_fast_path_attempted_views_.insert(target);
  if (observer->IsExposed()) {
    return false;
  }

  if (!observer->TryNotifyAppearWithoutGeometry()) {
    return false;
  }

  return true;
}

bool IntersectionObserverManager::TryReconcileLargeExposureTargetAfterLayout(
    BaseView* layout_view) {
  if (!layout_view || !owner_page_view_ || expose_observers_map_.empty() ||
      !HasValidPositiveArea(owner_page_view_)) {
    return false;
  }

  const double page_area = Area(owner_page_view_);
  if (HasExposeObserver(layout_view) &&
      layout_fast_path_attempted_views_.count(layout_view) == 0 &&
      HasValidPositiveArea(layout_view) &&
      Area(layout_view) > page_area * kLargeExposureTargetViewportAreaRatio) {
    layout_fast_path_candidate_views_.insert(layout_view);
  }
  if (layout_fast_path_candidate_views_.empty()) {
    return false;
  }

  // An observed target may receive layout before a full-screen wrapper. Only
  // recheck the target when its own or one of its ancestors' bounds changes;
  // unrelated layout updates do not scan the pending candidates.
  bool reconciled = false;
  const std::vector<BaseView*> candidates(
      layout_fast_path_candidate_views_.begin(),
      layout_fast_path_candidate_views_.end());
  for (auto* target : candidates) {
    if (!HasExposeObserver(target) ||
        layout_fast_path_attempted_views_.count(target) != 0) {
      layout_fast_path_candidate_views_.erase(target);
      continue;
    }

    bool relevant_layout_update = layout_view == target;
    for (auto* ancestor = target->Parent(); !relevant_layout_update && ancestor;
         ancestor = ancestor->Parent()) {
      relevant_layout_update = ancestor == layout_view;
      if (ancestor == owner_page_view_) {
        break;
      }
    }
    if (!relevant_layout_update) {
      continue;
    }

    const bool attached = target->attach_to_tree();
    bool large_ready_ancestor_chain = attached;
    BaseView* current = target;
    while (large_ready_ancestor_chain && current &&
           current != owner_page_view_) {
      if (!HasValidPositiveArea(current) ||
          Area(current) <= page_area * kLargeExposureTargetViewportAreaRatio) {
        large_ready_ancestor_chain = false;
        break;
      }
      current = current->Parent();
    }

    const bool page_descendant = current == owner_page_view_;
    const bool eligible = !exposure_stopped_ && exposure_host_visible_ &&
                          large_ready_ancestor_chain && page_descendant;
    if (!eligible) {
      continue;
    }

    ReconcileExposureForTarget(target);
    reconciled = true;
  }

  if (reconciled) {
    owner_page_view_->SendGlobalExposureEvent();
  }
  return reconciled;
}

void IntersectionObserverManager::NotifyExposures(
    void (IntersectionObserver::*ptr)(), BaseView* view) {
  for (auto& it : expose_observers_map_) {
    if (view == nullptr || (it.second->GetAttachedView() == view)) {
      (it.second.get()->*ptr)();
    }
  }
}

void IntersectionObserverManager::NotifyAllObserver(
    void (IntersectionObserver::*ptr)(), BaseView* view) {
  NotifyObserver(intersection_observers_, ptr, view);
  NotifyExposures(ptr, view);
}

}  // namespace clay
