/* C++ code produced by gperf version 3.0.3 */
/* Computed positions: -k'1,3,13,$' */

#if !(                                                                         \
    (' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) && ('%' == 37) && \
    ('&' == 38) && ('\'' == 39) && ('(' == 40) && (')' == 41) &&               \
    ('*' == 42) && ('+' == 43) && (',' == 44) && ('-' == 45) && ('.' == 46) && \
    ('/' == 47) && ('0' == 48) && ('1' == 49) && ('2' == 50) && ('3' == 51) && \
    ('4' == 52) && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) && \
    ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) && ('=' == 61) && \
    ('>' == 62) && ('?' == 63) && ('A' == 65) && ('B' == 66) && ('C' == 67) && \
    ('D' == 68) && ('E' == 69) && ('F' == 70) && ('G' == 71) && ('H' == 72) && \
    ('I' == 73) && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) && \
    ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) && ('R' == 82) && \
    ('S' == 83) && ('T' == 84) && ('U' == 85) && ('V' == 86) && ('W' == 87) && \
    ('X' == 88) && ('Y' == 89) && ('Z' == 90) && ('[' == 91) &&                \
    ('\\' == 92) && (']' == 93) && ('^' == 94) && ('_' == 95) &&               \
    ('a' == 97) && ('b' == 98) && ('c' == 99) && ('d' == 100) &&               \
    ('e' == 101) && ('f' == 102) && ('g' == 103) && ('h' == 104) &&            \
    ('i' == 105) && ('j' == 106) && ('k' == 107) && ('l' == 108) &&            \
    ('m' == 109) && ('n' == 110) && ('o' == 111) && ('p' == 112) &&            \
    ('q' == 113) && ('r' == 114) && ('s' == 115) && ('t' == 116) &&            \
    ('u' == 117) && ('v' == 118) && ('w' == 119) && ('x' == 120) &&            \
    ('y' == 121) && ('z' == 122) && ('{' == 123) && ('|' == 124) &&            \
    ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error \
    "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

// Copyright 2024 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

//
// DO NOT MODIFY THIS FILE! AUTO GENERATED BY clay/tools/make_keywords.py
//

#include "clay/ui/component/keywords.h"

#include <string>

namespace clay {
struct TokenValue {
  short name;
  short id;
};

#define TOTAL_KEYWORDS 256
#define MIN_WORD_LENGTH 3
#define MAX_WORD_LENGTH 37
#define MIN_HASH_VALUE 25
#define MAX_HASH_VALUE 683
/* maximum key range = 659, duplicates = 0 */

class KeywordHash {
 private:
  static inline unsigned int hash(const char *str, unsigned int len);

 public:
  static const struct TokenValue *find(const char *str, unsigned int len);
};

inline unsigned int KeywordHash::hash(const char *str, unsigned int len) {
  static const unsigned short asso_values[] = {
      684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684,
      684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684,
      684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684,
      209, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684,
      684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684,
      684, 684, 684, 684, 684, 684, 684, 684, 0,   684, 684, 684, 684, 684, 684,
      684, 684, 684, 684, 684, 684, 684, 107, 59,  46,  223, 0,   266, 173, 190,
      60,  9,   2,   143, 9,   95,  166, 30,  684, 24,  7,   4,   169, 49,  70,
      190, 264, 2,   684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684,
      684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684,
      684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684,
      684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684,
      684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684,
      684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684,
      684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684,
      684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684,
      684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684, 684,
      684};
  unsigned int hval = len;

  switch (hval) {
    default:
      hval += asso_values[(unsigned char)str[12]];
    /*FALLTHROUGH*/
    case 12:
    case 11:
    case 10:
    case 9:
    case 8:
    case 7:
    case 6:
    case 5:
    case 4:
    case 3:
      hval += asso_values[(unsigned char)str[2]];
    /*FALLTHROUGH*/
    case 2:
    case 1:
      hval += asso_values[(unsigned char)str[0]];
      break;
  }
  return hval + asso_values[(unsigned char)str[len - 1]];
}

struct StringPool_t {
  char StringPool_str25[sizeof("mask-size")];
  char StringPool_str26[sizeof("mask-image")];
  char StringPool_str31[sizeof("mask-repeat")];
  char StringPool_str38[sizeof("type")];
  char StringPool_str44[sizeof("scroll-enable")];
  char StringPool_str46[sizeof("scroll-left")];
  char StringPool_str52[sizeof("markdown-effect")];
  char StringPool_str55[sizeof("mask-clip")];
  char StringPool_str61[sizeof("exposure-screen-margin-left")];
  char StringPool_str62[sizeof("exposure-screen-margin-right")];
  char StringPool_str63[sizeof("visible")];
  char StringPool_str64[sizeof("repeat")];
  char StringPool_str65[sizeof("perspective")];
  char StringPool_str66[sizeof("exposure-ui-margin-left")];
  char StringPool_str67[sizeof("exposure-ui-margin-right")];
  char StringPool_str68[sizeof("exposure-screen-margin-bottom")];
  char StringPool_str71[sizeof("scroll-top")];
  char StringPool_str73[sizeof("exposure-ui-margin-bottom")];
  char StringPool_str74[sizeof("scroll-forward-mode")];
  char StringPool_str75[sizeof("itemkeys")];
  char StringPool_str78[sizeof("richtype")];
  char StringPool_str79[sizeof("bottom-inset")];
  char StringPool_str86[sizeof("exposure-screen-margin-top")];
  char StringPool_str87[sizeof("edit-on-focus")];
  char StringPool_str88[sizeof("sticky-offset")];
  char StringPool_str91[sizeof("exposure-ui-margin-top")];
  char StringPool_str93[sizeof("cap-insets")];
  char StringPool_str94[sizeof("idSelector")];
  char StringPool_str95[sizeof("border-style")];
  char StringPool_str98[sizeof("border-left")];
  char StringPool_str99[sizeof("border-right")];
  char StringPool_str100[sizeof("cursor")];
  char StringPool_str101[sizeof("scroll-bar-track-color")];
  char StringPool_str102[sizeof("src")];
  char StringPool_str103[sizeof("border-top-style")];
  char StringPool_str104[sizeof("prev-scrollable")];
  char StringPool_str105[sizeof("caret-color")];
  char StringPool_str106[sizeof("word-break")];
  char StringPool_str107[sizeof("border-left-style")];
  char StringPool_str108[sizeof("name")];
  char StringPool_str110[sizeof("border-radius")];
  char StringPool_str111[sizeof("border-bottom-style")];
  char StringPool_str112[sizeof("border-top-left-radius")];
  char StringPool_str113[sizeof("border")];
  char StringPool_str114[sizeof("border-bottom")];
  char StringPool_str118[sizeof("min-height")];
  char StringPool_str119[sizeof("border-color")];
  char StringPool_str120[sizeof("auto-size")];
  char StringPool_str121[sizeof("needs-visible-cells")];
  char StringPool_str122[sizeof("mask-origin")];
  char StringPool_str123[sizeof("border-top")];
  char StringPool_str124[sizeof("border-bottom-left-radius")];
  char StringPool_str125[sizeof("border-bottom-right-radius")];
  char StringPool_str126[sizeof("background-repeat")];
  char StringPool_str127[sizeof("adjust-mode")];
  char StringPool_str129[sizeof("transform")];
  char StringPool_str130[sizeof("background-image")];
  char StringPool_str133[sizeof("tint-color")];
  char StringPool_str135[sizeof("border-bottom-color")];
  char StringPool_str138[sizeof("cap-insets-scale")];
  char StringPool_str139[sizeof("exposure-scene")];
  char StringPool_str141[sizeof("white-space")];
  char StringPool_str143[sizeof("scroll-bar-enable")];
  char StringPool_str146[sizeof("scroll-direction")];
  char StringPool_str148[sizeof("scroll-orientation")];
  char StringPool_str152[sizeof("content")];
  char StringPool_str153[sizeof("confirm-type")];
  char StringPool_str154[sizeof("content-range")];
  char StringPool_str156[sizeof("controls")];
  char StringPool_str158[sizeof("scroll-backward-mode")];
  char StringPool_str159[sizeof("list-type")];
  char StringPool_str160[sizeof("select")];
  char StringPool_str164[sizeof("consume-slide-event")];
  char StringPool_str166[sizeof("typewriter-height-transition-duration")];
  char StringPool_str170[sizeof("border-left-color")];
  char StringPool_str172[sizeof("placeholder")];
  char StringPool_str173[sizeof("border-top-right-radius")];
  char StringPool_str174[sizeof("ignore-focus")];
  char StringPool_str176[sizeof("custom-text-selection")];
  char StringPool_str177[sizeof("outline")];
  char StringPool_str180[sizeof("background-size")];
  char StringPool_str182[sizeof("skip-redirection")];
  char StringPool_str183[sizeof("outline-style")];
  char StringPool_str185[sizeof("align-focus")];
  char StringPool_str188[sizeof("vertical-orientation")];
  char StringPool_str190[sizeof("markdown-style")];
  char StringPool_str193[sizeof("image-transition-style")];
  char StringPool_str197[sizeof("value")];
  char StringPool_str202[sizeof("text")];
  char StringPool_str205[sizeof("column-count")];
  char StringPool_str206[sizeof("text-maxline")];
  char StringPool_str209[sizeof("text-indent")];
  char StringPool_str211[sizeof("animation-type")];
  char StringPool_str213[sizeof("max-height")];
  char StringPool_str214[sizeof("maxlines")];
  char StringPool_str215[sizeof("text-gradient")];
  char StringPool_str216[sizeof("transition")];
  char StringPool_str218[sizeof("color")];
  char StringPool_str219[sizeof("mask-position")];
  char StringPool_str220[sizeof("scroll-bar-auto-hide")];
  char StringPool_str221[sizeof("send-composing-input")];
  char StringPool_str224[sizeof("placeholder-color")];
  char StringPool_str226[sizeof("text-mark-attachments")];
  char StringPool_str227[sizeof("scroll-without-focus")];
  char StringPool_str229[sizeof("scroll-x")];
  char StringPool_str231[sizeof("outline-color")];
  char StringPool_str232[sizeof("hit-slop")];
  char StringPool_str233[sizeof("show-soft-input-onfocus")];
  char StringPool_str234[sizeof("bounce")];
  char StringPool_str235[sizeof("speed")];
  char StringPool_str236[sizeof("mode")];
  char StringPool_str238[sizeof("dataset")];
  char StringPool_str241[sizeof("background-origin")];
  char StringPool_str242[sizeof("bounces")];
  char StringPool_str243[sizeof("enable-insert-platform-view-operation")];
  char StringPool_str244[sizeof("overflow")];
  char StringPool_str245[sizeof("enable-new-animator")];
  char StringPool_str246[sizeof("blur-radius")];
  char StringPool_str251[sizeof("scroll-bar-thumb-radius")];
  char StringPool_str253[sizeof("line-height")];
  char StringPool_str257[sizeof("exposure-area")];
  char StringPool_str258[sizeof("list-main-axis-gap")];
  char StringPool_str259[sizeof("z-index")];
  char StringPool_str260[sizeof("preload")];
  char StringPool_str261[sizeof("scroll-event-throttle")];
  char StringPool_str262[sizeof("allow-escape")];
  char StringPool_str263[sizeof("prevent-loading-on-list-scroll")];
  char StringPool_str264[sizeof("exposure-id")];
  char StringPool_str266[sizeof("scroll-to-id")];
  char StringPool_str267[sizeof("scroll-bar-thumb-color")];
  char StringPool_str269[sizeof("smart-scroll")];
  char StringPool_str271[sizeof("animation")];
  char StringPool_str273[sizeof("scroll-bar-thumb-hover-color")];
  char StringPool_str274[sizeof("scroll-bar-thumb-active-color")];
  char StringPool_str275[sizeof("text-shadow")];
  char StringPool_str279[sizeof("initial-animation-step")];
  char StringPool_str280[sizeof("experimental-recycle-sticky-item")];
  char StringPool_str281[sizeof("text-stroke-color")];
  char StringPool_str282[sizeof("transform-origin")];
  char StringPool_str285[sizeof("border-width")];
  char StringPool_str288[sizeof("initial-scroll-offset")];
  char StringPool_str289[sizeof("border-top-color")];
  char StringPool_str290[sizeof("enable-scrollbar")];
  char StringPool_str293[sizeof("background-clip")];
  char StringPool_str294[sizeof("animation-frame-rate")];
  char StringPool_str295[sizeof("enable-report-info")];
  char StringPool_str297[sizeof("scroll-bar-width")];
  char StringPool_str299[sizeof("text-align")];
  char StringPool_str300[sizeof("content-complete")];
  char StringPool_str301[sizeof("border-bottom-width")];
  char StringPool_str302[sizeof("intersection-observers")];
  char StringPool_str303[sizeof("scroll-y")];
  char StringPool_str304[sizeof("next-focus-left")];
  char StringPool_str305[sizeof("clip-path")];
  char StringPool_str306[sizeof("enable-font-scaling")];
  char StringPool_str308[sizeof("uiappear")];
  char StringPool_str309[sizeof("auto-fix")];
  char StringPool_str310[sizeof("border-right-style")];
  char StringPool_str311[sizeof("background-color")];
  char StringPool_str320[sizeof("preferred-focus-child")];
  char StringPool_str321[sizeof("focusable")];
  char StringPool_str323[sizeof("loop-count")];
  char StringPool_str324[sizeof("focus")];
  char StringPool_str327[sizeof("typewriter-dynamic-height")];
  char StringPool_str329[sizeof("box-shadow")];
  char StringPool_str330[sizeof("visibility")];
  char StringPool_str332[sizeof("item-key")];
  char StringPool_str334[sizeof("border-right-color")];
  char StringPool_str335[sizeof("list-container-info")];
  char StringPool_str337[sizeof("sticky")];
  char StringPool_str338[sizeof("background")];
  char StringPool_str340[sizeof("level")];
  char StringPool_str343[sizeof("loop")];
  char StringPool_str347[sizeof("text-overflow")];
  char StringPool_str349[sizeof("border-top-width")];
  char StringPool_str351[sizeof("direction")];
  char StringPool_str352[sizeof("image-config")];
  char StringPool_str353[sizeof("tag")];
  char StringPool_str355[sizeof("vertical-align")];
  char StringPool_str358[sizeof("next-focus-up")];
  char StringPool_str359[sizeof("next-scrollable")];
  char StringPool_str360[sizeof("border-left-width")];
  char StringPool_str361[sizeof("auto-save-last-child")];
  char StringPool_str364[sizeof("text-decoration")];
  char StringPool_str365[sizeof("next-focus-right")];
  char StringPool_str366[sizeof("overflow-x")];
  char StringPool_str370[sizeof("font-size")];
  char StringPool_str371[sizeof("font-style")];
  char StringPool_str374[sizeof("content-id")];
  char StringPool_str376[sizeof("font-weight")];
  char StringPool_str383[sizeof("autoplay")];
  char StringPool_str385[sizeof("background-position")];
  char StringPool_str388[sizeof("scroll-monitor-tag")];
  char StringPool_str389[sizeof("list-cross-axis-gap")];
  char StringPool_str393[sizeof("event-through")];
  char StringPool_str395[sizeof("upper-threshold-item-count")];
  char StringPool_str396[sizeof("enable-exposure-ui-margin")];
  char StringPool_str398[sizeof("maxlength")];
  char StringPool_str402[sizeof("text-maxlength")];
  char StringPool_str403[sizeof("readonly")];
  char StringPool_str406[sizeof("enable-scroll")];
  char StringPool_str409[sizeof("lower-threshold-item-count")];
  char StringPool_str413[sizeof("next-focus-fallback")];
  char StringPool_str415[sizeof("image-rendering")];
  char StringPool_str420[sizeof("user-interaction-enabled")];
  char StringPool_str423[sizeof("line-spacing")];
  char StringPool_str424[sizeof("placeholder-font-size")];
  char StringPool_str427[sizeof("uidisappear")];
  char StringPool_str429[sizeof("letter-spacing")];
  char StringPool_str430[sizeof("placeholder-font-weight")];
  char StringPool_str431[sizeof("custom-context-menu")];
  char StringPool_str433[sizeof("scroll-bar-thumb-width")];
  char StringPool_str438[sizeof("scroll-bar-thumb-min-length")];
  char StringPool_str439[sizeof("filter")];
  char StringPool_str440[sizeof("overflow-y")];
  char StringPool_str442[sizeof("accessibility-element")];
  char StringPool_str445[sizeof("offset-rotate")];
  char StringPool_str446[sizeof("accessibility-elements")];
  char StringPool_str456[sizeof("block-native-event")];
  char StringPool_str459[sizeof("scroll-to-index")];
  char StringPool_str461[sizeof("disabled")];
  char StringPool_str463[sizeof("text-single-line-vertical-align")];
  char StringPool_str468[sizeof("use-soft-keyboard")];
  char StringPool_str469[sizeof("text-selection")];
  char StringPool_str470[sizeof("drop-shadow")];
  char StringPool_str471[sizeof("text-stroke-width")];
  char StringPool_str473[sizeof("initial-scroll-index")];
  char StringPool_str478[sizeof("downsampling")];
  char StringPool_str482[sizeof("allow-break-around-punctuation")];
  char StringPool_str488[sizeof("low-quality")];
  char StringPool_str490[sizeof("scroll-bar-auto-hide-delay")];
  char StringPool_str492[sizeof("need-visible-item-info")];
  char StringPool_str493[sizeof("enable-nested-scroll")];
  char StringPool_str500[sizeof("border-right-width")];
  char StringPool_str507[sizeof("update-animation")];
  char StringPool_str513[sizeof("focus-index")];
  char StringPool_str515[sizeof("full-screen")];
  char StringPool_str537[sizeof("experimental-batch-render-strategy")];
  char StringPool_str540[sizeof("experimental-update-sticky-for-diff")];
  char StringPool_str542[sizeof("offset-distance")];
  char StringPool_str544[sizeof("opacity")];
  char StringPool_str561[sizeof("next-focus-down")];
  char StringPool_str563[sizeof("outline-width")];
  char StringPool_str579[sizeof("accessibility-label")];
  char StringPool_str590[sizeof("fullscreen-mode")];
  char StringPool_str592[sizeof("animation-velocity")];
  char StringPool_str603[sizeof("upper-threshold")];
  char StringPool_str617[sizeof("lower-threshold")];
  char StringPool_str621[sizeof("-x-app-region")];
  char StringPool_str633[sizeof("offset-path")];
  char StringPool_str634[sizeof("update-list-info")];
  char StringPool_str636[sizeof("font-family")];
  char StringPool_str644[sizeof("-x-auto-font-size")];
  char StringPool_str655[sizeof("defer-src-invalidation")];
  char StringPool_str664[sizeof("-x-auto-font-size-preset-sizes")];
  char StringPool_str683[sizeof("focus-smooth-scroll")];
};
static const struct StringPool_t StringPool_contents = {
    "mask-size",
    "mask-image",
    "mask-repeat",
    "type",
    "scroll-enable",
    "scroll-left",
    "markdown-effect",
    "mask-clip",
    "exposure-screen-margin-left",
    "exposure-screen-margin-right",
    "visible",
    "repeat",
    "perspective",
    "exposure-ui-margin-left",
    "exposure-ui-margin-right",
    "exposure-screen-margin-bottom",
    "scroll-top",
    "exposure-ui-margin-bottom",
    "scroll-forward-mode",
    "itemkeys",
    "richtype",
    "bottom-inset",
    "exposure-screen-margin-top",
    "edit-on-focus",
    "sticky-offset",
    "exposure-ui-margin-top",
    "cap-insets",
    "idSelector",
    "border-style",
    "border-left",
    "border-right",
    "cursor",
    "scroll-bar-track-color",
    "src",
    "border-top-style",
    "prev-scrollable",
    "caret-color",
    "word-break",
    "border-left-style",
    "name",
    "border-radius",
    "border-bottom-style",
    "border-top-left-radius",
    "border",
    "border-bottom",
    "min-height",
    "border-color",
    "auto-size",
    "needs-visible-cells",
    "mask-origin",
    "border-top",
    "border-bottom-left-radius",
    "border-bottom-right-radius",
    "background-repeat",
    "adjust-mode",
    "transform",
    "background-image",
    "tint-color",
    "border-bottom-color",
    "cap-insets-scale",
    "exposure-scene",
    "white-space",
    "scroll-bar-enable",
    "scroll-direction",
    "scroll-orientation",
    "content",
    "confirm-type",
    "content-range",
    "controls",
    "scroll-backward-mode",
    "list-type",
    "select",
    "consume-slide-event",
    "typewriter-height-transition-duration",
    "border-left-color",
    "placeholder",
    "border-top-right-radius",
    "ignore-focus",
    "custom-text-selection",
    "outline",
    "background-size",
    "skip-redirection",
    "outline-style",
    "align-focus",
    "vertical-orientation",
    "markdown-style",
    "image-transition-style",
    "value",
    "text",
    "column-count",
    "text-maxline",
    "text-indent",
    "animation-type",
    "max-height",
    "maxlines",
    "text-gradient",
    "transition",
    "color",
    "mask-position",
    "scroll-bar-auto-hide",
    "send-composing-input",
    "placeholder-color",
    "text-mark-attachments",
    "scroll-without-focus",
    "scroll-x",
    "outline-color",
    "hit-slop",
    "show-soft-input-onfocus",
    "bounce",
    "speed",
    "mode",
    "dataset",
    "background-origin",
    "bounces",
    "enable-insert-platform-view-operation",
    "overflow",
    "enable-new-animator",
    "blur-radius",
    "scroll-bar-thumb-radius",
    "line-height",
    "exposure-area",
    "list-main-axis-gap",
    "z-index",
    "preload",
    "scroll-event-throttle",
    "allow-escape",
    "prevent-loading-on-list-scroll",
    "exposure-id",
    "scroll-to-id",
    "scroll-bar-thumb-color",
    "smart-scroll",
    "animation",
    "scroll-bar-thumb-hover-color",
    "scroll-bar-thumb-active-color",
    "text-shadow",
    "initial-animation-step",
    "experimental-recycle-sticky-item",
    "text-stroke-color",
    "transform-origin",
    "border-width",
    "initial-scroll-offset",
    "border-top-color",
    "enable-scrollbar",
    "background-clip",
    "animation-frame-rate",
    "enable-report-info",
    "scroll-bar-width",
    "text-align",
    "content-complete",
    "border-bottom-width",
    "intersection-observers",
    "scroll-y",
    "next-focus-left",
    "clip-path",
    "enable-font-scaling",
    "uiappear",
    "auto-fix",
    "border-right-style",
    "background-color",
    "preferred-focus-child",
    "focusable",
    "loop-count",
    "focus",
    "typewriter-dynamic-height",
    "box-shadow",
    "visibility",
    "item-key",
    "border-right-color",
    "list-container-info",
    "sticky",
    "background",
    "level",
    "loop",
    "text-overflow",
    "border-top-width",
    "direction",
    "image-config",
    "tag",
    "vertical-align",
    "next-focus-up",
    "next-scrollable",
    "border-left-width",
    "auto-save-last-child",
    "text-decoration",
    "next-focus-right",
    "overflow-x",
    "font-size",
    "font-style",
    "content-id",
    "font-weight",
    "autoplay",
    "background-position",
    "scroll-monitor-tag",
    "list-cross-axis-gap",
    "event-through",
    "upper-threshold-item-count",
    "enable-exposure-ui-margin",
    "maxlength",
    "text-maxlength",
    "readonly",
    "enable-scroll",
    "lower-threshold-item-count",
    "next-focus-fallback",
    "image-rendering",
    "user-interaction-enabled",
    "line-spacing",
    "placeholder-font-size",
    "uidisappear",
    "letter-spacing",
    "placeholder-font-weight",
    "custom-context-menu",
    "scroll-bar-thumb-width",
    "scroll-bar-thumb-min-length",
    "filter",
    "overflow-y",
    "accessibility-element",
    "offset-rotate",
    "accessibility-elements",
    "block-native-event",
    "scroll-to-index",
    "disabled",
    "text-single-line-vertical-align",
    "use-soft-keyboard",
    "text-selection",
    "drop-shadow",
    "text-stroke-width",
    "initial-scroll-index",
    "downsampling",
    "allow-break-around-punctuation",
    "low-quality",
    "scroll-bar-auto-hide-delay",
    "need-visible-item-info",
    "enable-nested-scroll",
    "border-right-width",
    "update-animation",
    "focus-index",
    "full-screen",
    "experimental-batch-render-strategy",
    "experimental-update-sticky-for-diff",
    "offset-distance",
    "opacity",
    "next-focus-down",
    "outline-width",
    "accessibility-label",
    "fullscreen-mode",
    "animation-velocity",
    "upper-threshold",
    "lower-threshold",
    "-x-app-region",
    "offset-path",
    "update-list-info",
    "font-family",
    "-x-auto-font-size",
    "defer-src-invalidation",
    "-x-auto-font-size-preset-sizes",
    "focus-smooth-scroll"};
#define StringPool ((const char *)&StringPool_contents)

static const struct TokenValue wordlist[] = {
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str25),
     (short)KeywordID::kMaskSize},
    {offsetof(struct StringPool_t, StringPool_str26),
     (short)KeywordID::kMaskImage},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str31),
     (short)KeywordID::kMaskRepeat},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str38), (short)KeywordID::kType},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str44),
     (short)KeywordID::kScrollEnable},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str46),
     (short)KeywordID::kScrollLeft},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str52),
     (short)KeywordID::kMarkdownEffect},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str55),
     (short)KeywordID::kMaskClip},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str61),
     (short)KeywordID::kExposureScreenMarginLeft},
    {offsetof(struct StringPool_t, StringPool_str62),
     (short)KeywordID::kExposureScreenMarginRight},
    {offsetof(struct StringPool_t, StringPool_str63),
     (short)KeywordID::kVisible},
    {offsetof(struct StringPool_t, StringPool_str64),
     (short)KeywordID::kRepeat},
    {offsetof(struct StringPool_t, StringPool_str65),
     (short)KeywordID::kPerspective},
    {offsetof(struct StringPool_t, StringPool_str66),
     (short)KeywordID::kExposureUiMarginLeft},
    {offsetof(struct StringPool_t, StringPool_str67),
     (short)KeywordID::kExposureUiMarginRight},
    {offsetof(struct StringPool_t, StringPool_str68),
     (short)KeywordID::kExposureScreenMarginBottom},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str71),
     (short)KeywordID::kScrollTop},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str73),
     (short)KeywordID::kExposureUiMarginBottom},
    {offsetof(struct StringPool_t, StringPool_str74),
     (short)KeywordID::kScrollForwardMode},
    {offsetof(struct StringPool_t, StringPool_str75),
     (short)KeywordID::kItemkeys},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str78),
     (short)KeywordID::kRichtype},
    {offsetof(struct StringPool_t, StringPool_str79),
     (short)KeywordID::kBottomInset},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str86),
     (short)KeywordID::kExposureScreenMarginTop},
    {offsetof(struct StringPool_t, StringPool_str87),
     (short)KeywordID::kEditOnFocus},
    {offsetof(struct StringPool_t, StringPool_str88),
     (short)KeywordID::kStickyOffset},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str91),
     (short)KeywordID::kExposureUiMarginTop},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str93),
     (short)KeywordID::kCapInsets},
    {offsetof(struct StringPool_t, StringPool_str94),
     (short)KeywordID::kIdselector},
    {offsetof(struct StringPool_t, StringPool_str95),
     (short)KeywordID::kBorderStyle},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str98),
     (short)KeywordID::kBorderLeft},
    {offsetof(struct StringPool_t, StringPool_str99),
     (short)KeywordID::kBorderRight},
    {offsetof(struct StringPool_t, StringPool_str100),
     (short)KeywordID::kCursor},
    {offsetof(struct StringPool_t, StringPool_str101),
     (short)KeywordID::kScrollBarTrackColor},
    {offsetof(struct StringPool_t, StringPool_str102), (short)KeywordID::kSrc},
    {offsetof(struct StringPool_t, StringPool_str103),
     (short)KeywordID::kBorderTopStyle},
    {offsetof(struct StringPool_t, StringPool_str104),
     (short)KeywordID::kPrevScrollable},
    {offsetof(struct StringPool_t, StringPool_str105),
     (short)KeywordID::kCaretColor},
    {offsetof(struct StringPool_t, StringPool_str106),
     (short)KeywordID::kWordBreak},
    {offsetof(struct StringPool_t, StringPool_str107),
     (short)KeywordID::kBorderLeftStyle},
    {offsetof(struct StringPool_t, StringPool_str108), (short)KeywordID::kName},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str110),
     (short)KeywordID::kBorderRadius},
    {offsetof(struct StringPool_t, StringPool_str111),
     (short)KeywordID::kBorderBottomStyle},
    {offsetof(struct StringPool_t, StringPool_str112),
     (short)KeywordID::kBorderTopLeftRadius},
    {offsetof(struct StringPool_t, StringPool_str113),
     (short)KeywordID::kBorder},
    {offsetof(struct StringPool_t, StringPool_str114),
     (short)KeywordID::kBorderBottom},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str118),
     (short)KeywordID::kMinHeight},
    {offsetof(struct StringPool_t, StringPool_str119),
     (short)KeywordID::kBorderColor},
    {offsetof(struct StringPool_t, StringPool_str120),
     (short)KeywordID::kAutoSize},
    {offsetof(struct StringPool_t, StringPool_str121),
     (short)KeywordID::kNeedsVisibleCells},
    {offsetof(struct StringPool_t, StringPool_str122),
     (short)KeywordID::kMaskOrigin},
    {offsetof(struct StringPool_t, StringPool_str123),
     (short)KeywordID::kBorderTop},
    {offsetof(struct StringPool_t, StringPool_str124),
     (short)KeywordID::kBorderBottomLeftRadius},
    {offsetof(struct StringPool_t, StringPool_str125),
     (short)KeywordID::kBorderBottomRightRadius},
    {offsetof(struct StringPool_t, StringPool_str126),
     (short)KeywordID::kBackgroundRepeat},
    {offsetof(struct StringPool_t, StringPool_str127),
     (short)KeywordID::kAdjustMode},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str129),
     (short)KeywordID::kTransform},
    {offsetof(struct StringPool_t, StringPool_str130),
     (short)KeywordID::kBackgroundImage},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str133),
     (short)KeywordID::kTintColor},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str135),
     (short)KeywordID::kBorderBottomColor},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str138),
     (short)KeywordID::kCapInsetsScale},
    {offsetof(struct StringPool_t, StringPool_str139),
     (short)KeywordID::kExposureScene},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str141),
     (short)KeywordID::kWhiteSpace},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str143),
     (short)KeywordID::kScrollBarEnable},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str146),
     (short)KeywordID::kScrollDirection},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str148),
     (short)KeywordID::kScrollOrientation},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str152),
     (short)KeywordID::kContent},
    {offsetof(struct StringPool_t, StringPool_str153),
     (short)KeywordID::kConfirmType},
    {offsetof(struct StringPool_t, StringPool_str154),
     (short)KeywordID::kContentRange},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str156),
     (short)KeywordID::kControls},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str158),
     (short)KeywordID::kScrollBackwardMode},
    {offsetof(struct StringPool_t, StringPool_str159),
     (short)KeywordID::kListType},
    {offsetof(struct StringPool_t, StringPool_str160),
     (short)KeywordID::kSelect},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str164),
     (short)KeywordID::kConsumeSlideEvent},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str166),
     (short)KeywordID::kTypewriterHeightTransitionDuration},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str170),
     (short)KeywordID::kBorderLeftColor},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str172),
     (short)KeywordID::kPlaceholder},
    {offsetof(struct StringPool_t, StringPool_str173),
     (short)KeywordID::kBorderTopRightRadius},
    {offsetof(struct StringPool_t, StringPool_str174),
     (short)KeywordID::kIgnoreFocus},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str176),
     (short)KeywordID::kCustomTextSelection},
    {offsetof(struct StringPool_t, StringPool_str177),
     (short)KeywordID::kOutline},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str180),
     (short)KeywordID::kBackgroundSize},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str182),
     (short)KeywordID::kSkipRedirection},
    {offsetof(struct StringPool_t, StringPool_str183),
     (short)KeywordID::kOutlineStyle},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str185),
     (short)KeywordID::kAlignFocus},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str188),
     (short)KeywordID::kVerticalOrientation},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str190),
     (short)KeywordID::kMarkdownStyle},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str193),
     (short)KeywordID::kImageTransitionStyle},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str197),
     (short)KeywordID::kValue},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str202), (short)KeywordID::kText},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str205),
     (short)KeywordID::kColumnCount},
    {offsetof(struct StringPool_t, StringPool_str206),
     (short)KeywordID::kTextMaxline},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str209),
     (short)KeywordID::kTextIndent},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str211),
     (short)KeywordID::kAnimationType},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str213),
     (short)KeywordID::kMaxHeight},
    {offsetof(struct StringPool_t, StringPool_str214),
     (short)KeywordID::kMaxlines},
    {offsetof(struct StringPool_t, StringPool_str215),
     (short)KeywordID::kTextGradient},
    {offsetof(struct StringPool_t, StringPool_str216),
     (short)KeywordID::kTransition},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str218),
     (short)KeywordID::kColor},
    {offsetof(struct StringPool_t, StringPool_str219),
     (short)KeywordID::kMaskPosition},
    {offsetof(struct StringPool_t, StringPool_str220),
     (short)KeywordID::kScrollBarAutoHide},
    {offsetof(struct StringPool_t, StringPool_str221),
     (short)KeywordID::kSendComposingInput},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str224),
     (short)KeywordID::kPlaceholderColor},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str226),
     (short)KeywordID::kTextMarkAttachments},
    {offsetof(struct StringPool_t, StringPool_str227),
     (short)KeywordID::kScrollWithoutFocus},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str229),
     (short)KeywordID::kScrollX},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str231),
     (short)KeywordID::kOutlineColor},
    {offsetof(struct StringPool_t, StringPool_str232),
     (short)KeywordID::kHitSlop},
    {offsetof(struct StringPool_t, StringPool_str233),
     (short)KeywordID::kShowSoftInputOnfocus},
    {offsetof(struct StringPool_t, StringPool_str234),
     (short)KeywordID::kBounce},
    {offsetof(struct StringPool_t, StringPool_str235),
     (short)KeywordID::kSpeed},
    {offsetof(struct StringPool_t, StringPool_str236), (short)KeywordID::kMode},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str238),
     (short)KeywordID::kDataset},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str241),
     (short)KeywordID::kBackgroundOrigin},
    {offsetof(struct StringPool_t, StringPool_str242),
     (short)KeywordID::kBounces},
    {offsetof(struct StringPool_t, StringPool_str243),
     (short)KeywordID::kEnableInsertPlatformViewOperation},
    {offsetof(struct StringPool_t, StringPool_str244),
     (short)KeywordID::kOverflow},
    {offsetof(struct StringPool_t, StringPool_str245),
     (short)KeywordID::kEnableNewAnimator},
    {offsetof(struct StringPool_t, StringPool_str246),
     (short)KeywordID::kBlurRadius},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str251),
     (short)KeywordID::kScrollBarThumbRadius},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str253),
     (short)KeywordID::kLineHeight},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str257),
     (short)KeywordID::kExposureArea},
    {offsetof(struct StringPool_t, StringPool_str258),
     (short)KeywordID::kListMainAxisGap},
    {offsetof(struct StringPool_t, StringPool_str259),
     (short)KeywordID::kZIndex},
    {offsetof(struct StringPool_t, StringPool_str260),
     (short)KeywordID::kPreload},
    {offsetof(struct StringPool_t, StringPool_str261),
     (short)KeywordID::kScrollEventThrottle},
    {offsetof(struct StringPool_t, StringPool_str262),
     (short)KeywordID::kAllowEscape},
    {offsetof(struct StringPool_t, StringPool_str263),
     (short)KeywordID::kPreventLoadingOnListScroll},
    {offsetof(struct StringPool_t, StringPool_str264),
     (short)KeywordID::kExposureId},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str266),
     (short)KeywordID::kScrollToId},
    {offsetof(struct StringPool_t, StringPool_str267),
     (short)KeywordID::kScrollBarThumbColor},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str269),
     (short)KeywordID::kSmartScroll},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str271),
     (short)KeywordID::kAnimation},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str273),
     (short)KeywordID::kScrollBarThumbHoverColor},
    {offsetof(struct StringPool_t, StringPool_str274),
     (short)KeywordID::kScrollBarThumbActiveColor},
    {offsetof(struct StringPool_t, StringPool_str275),
     (short)KeywordID::kTextShadow},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str279),
     (short)KeywordID::kInitialAnimationStep},
    {offsetof(struct StringPool_t, StringPool_str280),
     (short)KeywordID::kExperimentalRecycleStickyItem},
    {offsetof(struct StringPool_t, StringPool_str281),
     (short)KeywordID::kTextStrokeColor},
    {offsetof(struct StringPool_t, StringPool_str282),
     (short)KeywordID::kTransformOrigin},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str285),
     (short)KeywordID::kBorderWidth},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str288),
     (short)KeywordID::kInitialScrollOffset},
    {offsetof(struct StringPool_t, StringPool_str289),
     (short)KeywordID::kBorderTopColor},
    {offsetof(struct StringPool_t, StringPool_str290),
     (short)KeywordID::kEnableScrollbar},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str293),
     (short)KeywordID::kBackgroundClip},
    {offsetof(struct StringPool_t, StringPool_str294),
     (short)KeywordID::kAnimationFrameRate},
    {offsetof(struct StringPool_t, StringPool_str295),
     (short)KeywordID::kEnableReportInfo},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str297),
     (short)KeywordID::kScrollBarWidth},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str299),
     (short)KeywordID::kTextAlign},
    {offsetof(struct StringPool_t, StringPool_str300),
     (short)KeywordID::kContentComplete},
    {offsetof(struct StringPool_t, StringPool_str301),
     (short)KeywordID::kBorderBottomWidth},
    {offsetof(struct StringPool_t, StringPool_str302),
     (short)KeywordID::kIntersectionObservers},
    {offsetof(struct StringPool_t, StringPool_str303),
     (short)KeywordID::kScrollY},
    {offsetof(struct StringPool_t, StringPool_str304),
     (short)KeywordID::kNextFocusLeft},
    {offsetof(struct StringPool_t, StringPool_str305),
     (short)KeywordID::kClipPath},
    {offsetof(struct StringPool_t, StringPool_str306),
     (short)KeywordID::kEnableFontScaling},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str308),
     (short)KeywordID::kUiappear},
    {offsetof(struct StringPool_t, StringPool_str309),
     (short)KeywordID::kAutoFix},
    {offsetof(struct StringPool_t, StringPool_str310),
     (short)KeywordID::kBorderRightStyle},
    {offsetof(struct StringPool_t, StringPool_str311),
     (short)KeywordID::kBackgroundColor},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str320),
     (short)KeywordID::kPreferredFocusChild},
    {offsetof(struct StringPool_t, StringPool_str321),
     (short)KeywordID::kFocusable},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str323),
     (short)KeywordID::kLoopCount},
    {offsetof(struct StringPool_t, StringPool_str324),
     (short)KeywordID::kFocus},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str327),
     (short)KeywordID::kTypewriterDynamicHeight},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str329),
     (short)KeywordID::kBoxShadow},
    {offsetof(struct StringPool_t, StringPool_str330),
     (short)KeywordID::kVisibility},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str332),
     (short)KeywordID::kItemKey},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str334),
     (short)KeywordID::kBorderRightColor},
    {offsetof(struct StringPool_t, StringPool_str335),
     (short)KeywordID::kListContainerInfo},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str337),
     (short)KeywordID::kSticky},
    {offsetof(struct StringPool_t, StringPool_str338),
     (short)KeywordID::kBackground},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str340),
     (short)KeywordID::kLevel},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str343), (short)KeywordID::kLoop},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str347),
     (short)KeywordID::kTextOverflow},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str349),
     (short)KeywordID::kBorderTopWidth},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str351),
     (short)KeywordID::kDirection},
    {offsetof(struct StringPool_t, StringPool_str352),
     (short)KeywordID::kImageConfig},
    {offsetof(struct StringPool_t, StringPool_str353), (short)KeywordID::kTag},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str355),
     (short)KeywordID::kVerticalAlign},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str358),
     (short)KeywordID::kNextFocusUp},
    {offsetof(struct StringPool_t, StringPool_str359),
     (short)KeywordID::kNextScrollable},
    {offsetof(struct StringPool_t, StringPool_str360),
     (short)KeywordID::kBorderLeftWidth},
    {offsetof(struct StringPool_t, StringPool_str361),
     (short)KeywordID::kAutoSaveLastChild},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str364),
     (short)KeywordID::kTextDecoration},
    {offsetof(struct StringPool_t, StringPool_str365),
     (short)KeywordID::kNextFocusRight},
    {offsetof(struct StringPool_t, StringPool_str366),
     (short)KeywordID::kOverflowX},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str370),
     (short)KeywordID::kFontSize},
    {offsetof(struct StringPool_t, StringPool_str371),
     (short)KeywordID::kFontStyle},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str374),
     (short)KeywordID::kContentId},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str376),
     (short)KeywordID::kFontWeight},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str383),
     (short)KeywordID::kAutoplay},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str385),
     (short)KeywordID::kBackgroundPosition},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str388),
     (short)KeywordID::kScrollMonitorTag},
    {offsetof(struct StringPool_t, StringPool_str389),
     (short)KeywordID::kListCrossAxisGap},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str393),
     (short)KeywordID::kEventThrough},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str395),
     (short)KeywordID::kUpperThresholdItemCount},
    {offsetof(struct StringPool_t, StringPool_str396),
     (short)KeywordID::kEnableExposureUiMargin},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str398),
     (short)KeywordID::kMaxlength},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str402),
     (short)KeywordID::kTextMaxlength},
    {offsetof(struct StringPool_t, StringPool_str403),
     (short)KeywordID::kReadonly},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str406),
     (short)KeywordID::kEnableScroll},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str409),
     (short)KeywordID::kLowerThresholdItemCount},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str413),
     (short)KeywordID::kNextFocusFallback},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str415),
     (short)KeywordID::kImageRendering},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str420),
     (short)KeywordID::kUserInteractionEnabled},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str423),
     (short)KeywordID::kLineSpacing},
    {offsetof(struct StringPool_t, StringPool_str424),
     (short)KeywordID::kPlaceholderFontSize},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str427),
     (short)KeywordID::kUidisappear},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str429),
     (short)KeywordID::kLetterSpacing},
    {offsetof(struct StringPool_t, StringPool_str430),
     (short)KeywordID::kPlaceholderFontWeight},
    {offsetof(struct StringPool_t, StringPool_str431),
     (short)KeywordID::kCustomContextMenu},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str433),
     (short)KeywordID::kScrollBarThumbWidth},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str438),
     (short)KeywordID::kScrollBarThumbMinLength},
    {offsetof(struct StringPool_t, StringPool_str439),
     (short)KeywordID::kFilter},
    {offsetof(struct StringPool_t, StringPool_str440),
     (short)KeywordID::kOverflowY},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str442),
     (short)KeywordID::kAccessibilityElement},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str445),
     (short)KeywordID::kOffsetRotate},
    {offsetof(struct StringPool_t, StringPool_str446),
     (short)KeywordID::kAccessibilityElements},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str456),
     (short)KeywordID::kBlockNativeEvent},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str459),
     (short)KeywordID::kScrollToIndex},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str461),
     (short)KeywordID::kDisabled},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str463),
     (short)KeywordID::kTextSingleLineVerticalAlign},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str468),
     (short)KeywordID::kUseSoftKeyboard},
    {offsetof(struct StringPool_t, StringPool_str469),
     (short)KeywordID::kTextSelection},
    {offsetof(struct StringPool_t, StringPool_str470),
     (short)KeywordID::kDropShadow},
    {offsetof(struct StringPool_t, StringPool_str471),
     (short)KeywordID::kTextStrokeWidth},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str473),
     (short)KeywordID::kInitialScrollIndex},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str478),
     (short)KeywordID::kDownsampling},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str482),
     (short)KeywordID::kAllowBreakAroundPunctuation},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str488),
     (short)KeywordID::kLowQuality},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str490),
     (short)KeywordID::kScrollBarAutoHideDelay},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str492),
     (short)KeywordID::kNeedVisibleItemInfo},
    {offsetof(struct StringPool_t, StringPool_str493),
     (short)KeywordID::kEnableNestedScroll},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str500),
     (short)KeywordID::kBorderRightWidth},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str507),
     (short)KeywordID::kUpdateAnimation},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str513),
     (short)KeywordID::kFocusIndex},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str515),
     (short)KeywordID::kFullScreen},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str537),
     (short)KeywordID::kExperimentalBatchRenderStrategy},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str540),
     (short)KeywordID::kExperimentalUpdateStickyForDiff},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str542),
     (short)KeywordID::kOffsetDistance},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str544),
     (short)KeywordID::kOpacity},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str561),
     (short)KeywordID::kNextFocusDown},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str563),
     (short)KeywordID::kOutlineWidth},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str579),
     (short)KeywordID::kAccessibilityLabel},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str590),
     (short)KeywordID::kFullscreenMode},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str592),
     (short)KeywordID::kAnimationVelocity},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str603),
     (short)KeywordID::kUpperThreshold},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str617),
     (short)KeywordID::kLowerThreshold},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str621),
     (short)KeywordID::kXAppRegion},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str633),
     (short)KeywordID::kOffsetPath},
    {offsetof(struct StringPool_t, StringPool_str634),
     (short)KeywordID::kUpdateListInfo},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str636),
     (short)KeywordID::kFontFamily},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str644),
     (short)KeywordID::kXAutoFontSize},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str655),
     (short)KeywordID::kDeferSrcInvalidation},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str664),
     (short)KeywordID::kXAutoFontSizePresetSizes},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str683),
     (short)KeywordID::kFocusSmoothScroll}};

const struct TokenValue *KeywordHash::find(const char *str, unsigned int len) {
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH) {
    unsigned int key = hash(str, len);

    if (key <= MAX_HASH_VALUE) {
      int o = wordlist[key].name;
      if (o >= 0) {
        const char *s = o + StringPool;

        if (*str == *s && !strcmp(str + 1, s + 1)) return &wordlist[key];
      }
    }
  }
  return 0;
}

static_assert(sizeof(StringPool_contents) < 32767);

KeywordID GetKeywordID(const std::string &str) {
  auto *tk = KeywordHash::find(str.c_str(), str.size());
  return tk ? static_cast<KeywordID>(tk->id) : KeywordID::kInvalid;
}

}  // namespace clay
