/* C++ code produced by gperf version 3.0.3 */
/* Computed positions: -k'1,3,13,$' */

#if !(                                                                         \
    (' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) && ('%' == 37) && \
    ('&' == 38) && ('\'' == 39) && ('(' == 40) && (')' == 41) &&               \
    ('*' == 42) && ('+' == 43) && (',' == 44) && ('-' == 45) && ('.' == 46) && \
    ('/' == 47) && ('0' == 48) && ('1' == 49) && ('2' == 50) && ('3' == 51) && \
    ('4' == 52) && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) && \
    ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) && ('=' == 61) && \
    ('>' == 62) && ('?' == 63) && ('A' == 65) && ('B' == 66) && ('C' == 67) && \
    ('D' == 68) && ('E' == 69) && ('F' == 70) && ('G' == 71) && ('H' == 72) && \
    ('I' == 73) && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) && \
    ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) && ('R' == 82) && \
    ('S' == 83) && ('T' == 84) && ('U' == 85) && ('V' == 86) && ('W' == 87) && \
    ('X' == 88) && ('Y' == 89) && ('Z' == 90) && ('[' == 91) &&                \
    ('\\' == 92) && (']' == 93) && ('^' == 94) && ('_' == 95) &&               \
    ('a' == 97) && ('b' == 98) && ('c' == 99) && ('d' == 100) &&               \
    ('e' == 101) && ('f' == 102) && ('g' == 103) && ('h' == 104) &&            \
    ('i' == 105) && ('j' == 106) && ('k' == 107) && ('l' == 108) &&            \
    ('m' == 109) && ('n' == 110) && ('o' == 111) && ('p' == 112) &&            \
    ('q' == 113) && ('r' == 114) && ('s' == 115) && ('t' == 116) &&            \
    ('u' == 117) && ('v' == 118) && ('w' == 119) && ('x' == 120) &&            \
    ('y' == 121) && ('z' == 122) && ('{' == 123) && ('|' == 124) &&            \
    ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error \
    "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

// Copyright 2024 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

//
// DO NOT MODIFY THIS FILE! AUTO GENERATED BY clay/tools/make_keywords.py
//

#include "clay/ui/component/keywords.h"

#include <string>

namespace clay {
struct TokenValue {
  short name;
  short id;
};

#define TOTAL_KEYWORDS 235
#define MIN_WORD_LENGTH 3
#define MAX_WORD_LENGTH 35
#define MIN_HASH_VALUE 24
#define MAX_HASH_VALUE 638
/* maximum key range = 615, duplicates = 0 */

class KeywordHash {
 private:
  static inline unsigned int hash(const char *str, unsigned int len);

 public:
  static const struct TokenValue *find(const char *str, unsigned int len);
};

inline unsigned int KeywordHash::hash(const char *str, unsigned int len) {
  static const unsigned short asso_values[] = {
      639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639,
      639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639,
      639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639,
      152, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639,
      639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639,
      639, 639, 639, 639, 639, 639, 639, 639, 2,   639, 639, 639, 639, 639, 639,
      639, 639, 639, 639, 639, 639, 639, 148, 12,  81,  210, 4,   154, 93,  125,
      48,  2,   4,   111, 14,  48,  144, 24,  639, 3,   17,  1,   82,  159, 158,
      89,  184, 3,   639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639,
      639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639,
      639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639,
      639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639,
      639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639,
      639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639,
      639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639,
      639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639,
      639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639, 639,
      639};
  unsigned int hval = len;

  switch (hval) {
    default:
      hval += asso_values[(unsigned char)str[12]];
    /*FALLTHROUGH*/
    case 12:
    case 11:
    case 10:
    case 9:
    case 8:
    case 7:
    case 6:
    case 5:
    case 4:
    case 3:
      hval += asso_values[(unsigned char)str[2]];
    /*FALLTHROUGH*/
    case 2:
    case 1:
      hval += asso_values[(unsigned char)str[0]];
      break;
  }
  return hval + asso_values[(unsigned char)str[len - 1]];
}

struct StringPool_t {
  char StringPool_str24[sizeof("border")];
  char StringPool_str26[sizeof("bottom-inset")];
  char StringPool_str27[sizeof("border-left")];
  char StringPool_str28[sizeof("border-right")];
  char StringPool_str30[sizeof("border-color")];
  char StringPool_str31[sizeof("border-style")];
  char StringPool_str32[sizeof("scroll-left")];
  char StringPool_str33[sizeof("type")];
  char StringPool_str34[sizeof("repeat")];
  char StringPool_str36[sizeof("border-top-style")];
  char StringPool_str41[sizeof("scroll-enable")];
  char StringPool_str42[sizeof("perspective")];
  char StringPool_str43[sizeof("mask-repeat")];
  char StringPool_str44[sizeof("mask-size")];
  char StringPool_str45[sizeof("mask-image")];
  char StringPool_str46[sizeof("scroll-forward-mode")];
  char StringPool_str48[sizeof("scroll-bar-track-color")];
  char StringPool_str49[sizeof("border-top")];
  char StringPool_str51[sizeof("border-bottom-color")];
  char StringPool_str52[sizeof("border-bottom-style")];
  char StringPool_str53[sizeof("border-left-style")];
  char StringPool_str54[sizeof("scroll-top")];
  char StringPool_str56[sizeof("border-bottom")];
  char StringPool_str58[sizeof("border-top-left-radius")];
  char StringPool_str59[sizeof("prev-scrollable")];
  char StringPool_str60[sizeof("exposure-screen-margin-left")];
  char StringPool_str61[sizeof("exposure-screen-margin-right")];
  char StringPool_str62[sizeof("border-radius")];
  char StringPool_str63[sizeof("idSelector")];
  char StringPool_str64[sizeof("mask-clip")];
  char StringPool_str66[sizeof("exposure-ui-margin-left")];
  char StringPool_str67[sizeof("exposure-ui-margin-right")];
  char StringPool_str70[sizeof("name")];
  char StringPool_str71[sizeof("border-bottom-left-radius")];
  char StringPool_str72[sizeof("border-bottom-right-radius")];
  char StringPool_str73[sizeof("min-height")];
  char StringPool_str75[sizeof("exposure-screen-margin-bottom")];
  char StringPool_str77[sizeof("itemkeys")];
  char StringPool_str80[sizeof("sticky-offset")];
  char StringPool_str81[sizeof("exposure-ui-margin-bottom")];
  char StringPool_str82[sizeof("exposure-screen-margin-top")];
  char StringPool_str85[sizeof("scroll-direction")];
  char StringPool_str87[sizeof("scroll-orientation")];
  char StringPool_str88[sizeof("exposure-ui-margin-top")];
  char StringPool_str89[sizeof("scroll-bar-enable")];
  char StringPool_str90[sizeof("mask-origin")];
  char StringPool_str92[sizeof("needs-visible-cells")];
  char StringPool_str93[sizeof("cursor")];
  char StringPool_str94[sizeof("exposure-scene")];
  char StringPool_str95[sizeof("text")];
  char StringPool_str96[sizeof("richtype")];
  char StringPool_str98[sizeof("caret-color")];
  char StringPool_str99[sizeof("edit-on-focus")];
  char StringPool_str102[sizeof("text-indent")];
  char StringPool_str103[sizeof("border-top-right-radius")];
  char StringPool_str104[sizeof("bounce")];
  char StringPool_str105[sizeof("text-gradient")];
  char StringPool_str106[sizeof("text-maxline")];
  char StringPool_str114[sizeof("max-height")];
  char StringPool_str115[sizeof("background-repeat")];
  char StringPool_str116[sizeof("border-left-color")];
  char StringPool_str117[sizeof("scroll-x")];
  char StringPool_str118[sizeof("bounces")];
  char StringPool_str122[sizeof("blur-radius")];
  char StringPool_str125[sizeof("ignore-focus")];
  char StringPool_str126[sizeof("scroll-bar-auto-hide")];
  char StringPool_str127[sizeof("background-image")];
  char StringPool_str128[sizeof("maxlines")];
  char StringPool_str130[sizeof("skip-redirection")];
  char StringPool_str132[sizeof("cap-insets")];
  char StringPool_str134[sizeof("send-composing-input")];
  char StringPool_str135[sizeof("select")];
  char StringPool_str137[sizeof("content")];
  char StringPool_str139[sizeof("scroll-without-focus")];
  char StringPool_str140[sizeof("mask-position")];
  char StringPool_str141[sizeof("list-type")];
  char StringPool_str145[sizeof("confirm-type")];
  char StringPool_str146[sizeof("markdown-style")];
  char StringPool_str147[sizeof("z-index")];
  char StringPool_str148[sizeof("text-align")];
  char StringPool_str152[sizeof("border-width")];
  char StringPool_str153[sizeof("consume-slide-event")];
  char StringPool_str154[sizeof("controls")];
  char StringPool_str156[sizeof("outline")];
  char StringPool_str157[sizeof("next-focus-left")];
  char StringPool_str158[sizeof("hit-slop")];
  char StringPool_str160[sizeof("background-size")];
  char StringPool_str161[sizeof("background-origin")];
  char StringPool_str162[sizeof("auto-size")];
  char StringPool_str164[sizeof("outline-color")];
  char StringPool_str165[sizeof("adjust-mode")];
  char StringPool_str166[sizeof("outline-style")];
  char StringPool_str168[sizeof("next-scrollable")];
  char StringPool_str170[sizeof("scroll-bar-thumb-color")];
  char StringPool_str171[sizeof("line-height")];
  char StringPool_str172[sizeof("transform")];
  char StringPool_str173[sizeof("border-bottom-width")];
  char StringPool_str175[sizeof("word-break")];
  char StringPool_str176[sizeof("scroll-bar-thumb-hover-color")];
  char StringPool_str177[sizeof("scroll-bar-thumb-active-color")];
  char StringPool_str178[sizeof("border-top-color")];
  char StringPool_str182[sizeof("src")];
  char StringPool_str185[sizeof("scroll-bar-thumb-radius")];
  char StringPool_str186[sizeof("placeholder")];
  char StringPool_str187[sizeof("visible")];
  char StringPool_str188[sizeof("border-right-color")];
  char StringPool_str189[sizeof("border-right-style")];
  char StringPool_str190[sizeof("tag")];
  char StringPool_str191[sizeof("text-stroke-color")];
  char StringPool_str192[sizeof("scroll-backward-mode")];
  char StringPool_str197[sizeof("scroll-event-throttle")];
  char StringPool_str198[sizeof("next-focus-up")];
  char StringPool_str200[sizeof("color")];
  char StringPool_str201[sizeof("text-decoration")];
  char StringPool_str202[sizeof("next-focus-right")];
  char StringPool_str204[sizeof("border-top-width")];
  char StringPool_str205[sizeof("column-count")];
  char StringPool_str206[sizeof("cap-insets-scale")];
  char StringPool_str207[sizeof("transition")];
  char StringPool_str209[sizeof("scroll-bar-width")];
  char StringPool_str212[sizeof("scroll-y")];
  char StringPool_str214[sizeof("font-weight")];
  char StringPool_str215[sizeof("font-size")];
  char StringPool_str216[sizeof("font-style")];
  char StringPool_str217[sizeof("prevent-loading-on-list-scroll")];
  char StringPool_str218[sizeof("list-main-axis-gap")];
  char StringPool_str219[sizeof("dataset")];
  char StringPool_str221[sizeof("white-space")];
  char StringPool_str222[sizeof("enable-new-animator")];
  char StringPool_str223[sizeof("image-transition-style")];
  char StringPool_str224[sizeof("align-focus")];
  char StringPool_str225[sizeof("show-soft-input-onfocus")];
  char StringPool_str226[sizeof("experimental-recycle-sticky-item")];
  char StringPool_str229[sizeof("initial-scroll-offset")];
  char StringPool_str230[sizeof("text-maxlength")];
  char StringPool_str232[sizeof("mode")];
  char StringPool_str234[sizeof("vertical-orientation")];
  char StringPool_str236[sizeof("speed")];
  char StringPool_str237[sizeof("maxlength")];
  char StringPool_str240[sizeof("intersection-observers")];
  char StringPool_str241[sizeof("uiappear")];
  char StringPool_str242[sizeof("scroll-to-id")];
  char StringPool_str243[sizeof("background-clip")];
  char StringPool_str244[sizeof("item-key")];
  char StringPool_str245[sizeof("preload")];
  char StringPool_str246[sizeof("auto-fix")];
  char StringPool_str247[sizeof("overflow-x")];
  char StringPool_str248[sizeof("focusable")];
  char StringPool_str249[sizeof("exposure-id")];
  char StringPool_str253[sizeof("animation")];
  char StringPool_str255[sizeof("sticky")];
  char StringPool_str256[sizeof("background-color")];
  char StringPool_str257[sizeof("focus")];
  char StringPool_str259[sizeof("text-shadow")];
  char StringPool_str260[sizeof("list-cross-axis-gap")];
  char StringPool_str261[sizeof("transform-origin")];
  char StringPool_str263[sizeof("clip-path")];
  char StringPool_str264[sizeof("line-spacing")];
  char StringPool_str266[sizeof("loop-count")];
  char StringPool_str267[sizeof("letter-spacing")];
  char StringPool_str269[sizeof("box-shadow")];
  char StringPool_str270[sizeof("direction")];
  char StringPool_str271[sizeof("event-through")];
  char StringPool_str273[sizeof("placeholder-color")];
  char StringPool_str274[sizeof("filter")];
  char StringPool_str275[sizeof("allow-escape")];
  char StringPool_str277[sizeof("upper-threshold-item-count")];
  char StringPool_str279[sizeof("value")];
  char StringPool_str280[sizeof("text-single-line-vertical-align")];
  char StringPool_str281[sizeof("enable-font-scaling")];
  char StringPool_str282[sizeof("enable-scrollbar")];
  char StringPool_str283[sizeof("loop")];
  char StringPool_str288[sizeof("smart-scroll")];
  char StringPool_str292[sizeof("scroll-bar-thumb-width")];
  char StringPool_str295[sizeof("list-container-info")];
  char StringPool_str296[sizeof("text-selection")];
  char StringPool_str297[sizeof("scroll-bar-thumb-min-length")];
  char StringPool_str301[sizeof("image-config")];
  char StringPool_str304[sizeof("background-position")];
  char StringPool_str306[sizeof("uidisappear")];
  char StringPool_str307[sizeof("enable-exposure-ui-margin")];
  char StringPool_str308[sizeof("next-focus-fallback")];
  char StringPool_str310[sizeof("border-right-width")];
  char StringPool_str312[sizeof("scroll-bar-auto-hide-delay")];
  char StringPool_str313[sizeof("background")];
  char StringPool_str314[sizeof("overflow")];
  char StringPool_str315[sizeof("border-left-width")];
  char StringPool_str316[sizeof("initial-scroll-index")];
  char StringPool_str317[sizeof("vertical-align")];
  char StringPool_str321[sizeof("user-interaction-enabled")];
  char StringPool_str324[sizeof("full-screen")];
  char StringPool_str325[sizeof("use-soft-keyboard")];
  char StringPool_str327[sizeof("block-native-event")];
  char StringPool_str334[sizeof("scroll-to-index")];
  char StringPool_str335[sizeof("focus-index")];
  char StringPool_str337[sizeof("exposure-area")];
  char StringPool_str340[sizeof("preferred-focus-child")];
  char StringPool_str341[sizeof("autoplay")];
  char StringPool_str342[sizeof("overflow-y")];
  char StringPool_str343[sizeof("readonly")];
  char StringPool_str344[sizeof("next-focus-down")];
  char StringPool_str350[sizeof("placeholder-font-weight")];
  char StringPool_str351[sizeof("placeholder-font-size")];
  char StringPool_str352[sizeof("image-rendering")];
  char StringPool_str357[sizeof("update-animation")];
  char StringPool_str369[sizeof("experimental-update-sticky-for-diff")];
  char StringPool_str370[sizeof("visibility")];
  char StringPool_str386[sizeof("level")];
  char StringPool_str387[sizeof("enable-scroll")];
  char StringPool_str390[sizeof("text-stroke-width")];
  char StringPool_str396[sizeof("auto-save-last-child")];
  char StringPool_str397[sizeof("font-family")];
  char StringPool_str398[sizeof("experimental-batch-render-strategy")];
  char StringPool_str399[sizeof("animation-style")];
  char StringPool_str408[sizeof("outline-width")];
  char StringPool_str413[sizeof("-x-app-region")];
  char StringPool_str419[sizeof("text-overflow")];
  char StringPool_str428[sizeof("fullscreen-mode")];
  char StringPool_str435[sizeof("accessibility-element")];
  char StringPool_str440[sizeof("lower-threshold-item-count")];
  char StringPool_str445[sizeof("disabled")];
  char StringPool_str452[sizeof("accessibility-elements")];
  char StringPool_str464[sizeof("low-quality")];
  char StringPool_str475[sizeof("upper-threshold")];
  char StringPool_str477[sizeof("-x-auto-font-size")];
  char StringPool_str483[sizeof("opacity")];
  char StringPool_str493[sizeof("enable-nested-scroll")];
  char StringPool_str500[sizeof("update-list-info")];
  char StringPool_str503[sizeof("-x-auto-font-size-preset-sizes")];
  char StringPool_str509[sizeof("animation-velocity")];
  char StringPool_str517[sizeof("focus-smooth-scroll")];
  char StringPool_str523[sizeof("drop-shadow")];
  char StringPool_str543[sizeof("accessibility-label")];
  char StringPool_str593[sizeof("defer-src-invalidation")];
  char StringPool_str638[sizeof("lower-threshold")];
};
static const struct StringPool_t StringPool_contents = {
    "border",
    "bottom-inset",
    "border-left",
    "border-right",
    "border-color",
    "border-style",
    "scroll-left",
    "type",
    "repeat",
    "border-top-style",
    "scroll-enable",
    "perspective",
    "mask-repeat",
    "mask-size",
    "mask-image",
    "scroll-forward-mode",
    "scroll-bar-track-color",
    "border-top",
    "border-bottom-color",
    "border-bottom-style",
    "border-left-style",
    "scroll-top",
    "border-bottom",
    "border-top-left-radius",
    "prev-scrollable",
    "exposure-screen-margin-left",
    "exposure-screen-margin-right",
    "border-radius",
    "idSelector",
    "mask-clip",
    "exposure-ui-margin-left",
    "exposure-ui-margin-right",
    "name",
    "border-bottom-left-radius",
    "border-bottom-right-radius",
    "min-height",
    "exposure-screen-margin-bottom",
    "itemkeys",
    "sticky-offset",
    "exposure-ui-margin-bottom",
    "exposure-screen-margin-top",
    "scroll-direction",
    "scroll-orientation",
    "exposure-ui-margin-top",
    "scroll-bar-enable",
    "mask-origin",
    "needs-visible-cells",
    "cursor",
    "exposure-scene",
    "text",
    "richtype",
    "caret-color",
    "edit-on-focus",
    "text-indent",
    "border-top-right-radius",
    "bounce",
    "text-gradient",
    "text-maxline",
    "max-height",
    "background-repeat",
    "border-left-color",
    "scroll-x",
    "bounces",
    "blur-radius",
    "ignore-focus",
    "scroll-bar-auto-hide",
    "background-image",
    "maxlines",
    "skip-redirection",
    "cap-insets",
    "send-composing-input",
    "select",
    "content",
    "scroll-without-focus",
    "mask-position",
    "list-type",
    "confirm-type",
    "markdown-style",
    "z-index",
    "text-align",
    "border-width",
    "consume-slide-event",
    "controls",
    "outline",
    "next-focus-left",
    "hit-slop",
    "background-size",
    "background-origin",
    "auto-size",
    "outline-color",
    "adjust-mode",
    "outline-style",
    "next-scrollable",
    "scroll-bar-thumb-color",
    "line-height",
    "transform",
    "border-bottom-width",
    "word-break",
    "scroll-bar-thumb-hover-color",
    "scroll-bar-thumb-active-color",
    "border-top-color",
    "src",
    "scroll-bar-thumb-radius",
    "placeholder",
    "visible",
    "border-right-color",
    "border-right-style",
    "tag",
    "text-stroke-color",
    "scroll-backward-mode",
    "scroll-event-throttle",
    "next-focus-up",
    "color",
    "text-decoration",
    "next-focus-right",
    "border-top-width",
    "column-count",
    "cap-insets-scale",
    "transition",
    "scroll-bar-width",
    "scroll-y",
    "font-weight",
    "font-size",
    "font-style",
    "prevent-loading-on-list-scroll",
    "list-main-axis-gap",
    "dataset",
    "white-space",
    "enable-new-animator",
    "image-transition-style",
    "align-focus",
    "show-soft-input-onfocus",
    "experimental-recycle-sticky-item",
    "initial-scroll-offset",
    "text-maxlength",
    "mode",
    "vertical-orientation",
    "speed",
    "maxlength",
    "intersection-observers",
    "uiappear",
    "scroll-to-id",
    "background-clip",
    "item-key",
    "preload",
    "auto-fix",
    "overflow-x",
    "focusable",
    "exposure-id",
    "animation",
    "sticky",
    "background-color",
    "focus",
    "text-shadow",
    "list-cross-axis-gap",
    "transform-origin",
    "clip-path",
    "line-spacing",
    "loop-count",
    "letter-spacing",
    "box-shadow",
    "direction",
    "event-through",
    "placeholder-color",
    "filter",
    "allow-escape",
    "upper-threshold-item-count",
    "value",
    "text-single-line-vertical-align",
    "enable-font-scaling",
    "enable-scrollbar",
    "loop",
    "smart-scroll",
    "scroll-bar-thumb-width",
    "list-container-info",
    "text-selection",
    "scroll-bar-thumb-min-length",
    "image-config",
    "background-position",
    "uidisappear",
    "enable-exposure-ui-margin",
    "next-focus-fallback",
    "border-right-width",
    "scroll-bar-auto-hide-delay",
    "background",
    "overflow",
    "border-left-width",
    "initial-scroll-index",
    "vertical-align",
    "user-interaction-enabled",
    "full-screen",
    "use-soft-keyboard",
    "block-native-event",
    "scroll-to-index",
    "focus-index",
    "exposure-area",
    "preferred-focus-child",
    "autoplay",
    "overflow-y",
    "readonly",
    "next-focus-down",
    "placeholder-font-weight",
    "placeholder-font-size",
    "image-rendering",
    "update-animation",
    "experimental-update-sticky-for-diff",
    "visibility",
    "level",
    "enable-scroll",
    "text-stroke-width",
    "auto-save-last-child",
    "font-family",
    "experimental-batch-render-strategy",
    "animation-style",
    "outline-width",
    "-x-app-region",
    "text-overflow",
    "fullscreen-mode",
    "accessibility-element",
    "lower-threshold-item-count",
    "disabled",
    "accessibility-elements",
    "low-quality",
    "upper-threshold",
    "-x-auto-font-size",
    "opacity",
    "enable-nested-scroll",
    "update-list-info",
    "-x-auto-font-size-preset-sizes",
    "animation-velocity",
    "focus-smooth-scroll",
    "drop-shadow",
    "accessibility-label",
    "defer-src-invalidation",
    "lower-threshold"};
#define StringPool ((const char *)&StringPool_contents)

static const struct TokenValue wordlist[] = {
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str24),
     (short)KeywordID::kBorder},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str26),
     (short)KeywordID::kBottomInset},
    {offsetof(struct StringPool_t, StringPool_str27),
     (short)KeywordID::kBorderLeft},
    {offsetof(struct StringPool_t, StringPool_str28),
     (short)KeywordID::kBorderRight},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str30),
     (short)KeywordID::kBorderColor},
    {offsetof(struct StringPool_t, StringPool_str31),
     (short)KeywordID::kBorderStyle},
    {offsetof(struct StringPool_t, StringPool_str32),
     (short)KeywordID::kScrollLeft},
    {offsetof(struct StringPool_t, StringPool_str33), (short)KeywordID::kType},
    {offsetof(struct StringPool_t, StringPool_str34),
     (short)KeywordID::kRepeat},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str36),
     (short)KeywordID::kBorderTopStyle},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str41),
     (short)KeywordID::kScrollEnable},
    {offsetof(struct StringPool_t, StringPool_str42),
     (short)KeywordID::kPerspective},
    {offsetof(struct StringPool_t, StringPool_str43),
     (short)KeywordID::kMaskRepeat},
    {offsetof(struct StringPool_t, StringPool_str44),
     (short)KeywordID::kMaskSize},
    {offsetof(struct StringPool_t, StringPool_str45),
     (short)KeywordID::kMaskImage},
    {offsetof(struct StringPool_t, StringPool_str46),
     (short)KeywordID::kScrollForwardMode},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str48),
     (short)KeywordID::kScrollBarTrackColor},
    {offsetof(struct StringPool_t, StringPool_str49),
     (short)KeywordID::kBorderTop},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str51),
     (short)KeywordID::kBorderBottomColor},
    {offsetof(struct StringPool_t, StringPool_str52),
     (short)KeywordID::kBorderBottomStyle},
    {offsetof(struct StringPool_t, StringPool_str53),
     (short)KeywordID::kBorderLeftStyle},
    {offsetof(struct StringPool_t, StringPool_str54),
     (short)KeywordID::kScrollTop},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str56),
     (short)KeywordID::kBorderBottom},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str58),
     (short)KeywordID::kBorderTopLeftRadius},
    {offsetof(struct StringPool_t, StringPool_str59),
     (short)KeywordID::kPrevScrollable},
    {offsetof(struct StringPool_t, StringPool_str60),
     (short)KeywordID::kExposureScreenMarginLeft},
    {offsetof(struct StringPool_t, StringPool_str61),
     (short)KeywordID::kExposureScreenMarginRight},
    {offsetof(struct StringPool_t, StringPool_str62),
     (short)KeywordID::kBorderRadius},
    {offsetof(struct StringPool_t, StringPool_str63),
     (short)KeywordID::kIdselector},
    {offsetof(struct StringPool_t, StringPool_str64),
     (short)KeywordID::kMaskClip},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str66),
     (short)KeywordID::kExposureUiMarginLeft},
    {offsetof(struct StringPool_t, StringPool_str67),
     (short)KeywordID::kExposureUiMarginRight},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str70), (short)KeywordID::kName},
    {offsetof(struct StringPool_t, StringPool_str71),
     (short)KeywordID::kBorderBottomLeftRadius},
    {offsetof(struct StringPool_t, StringPool_str72),
     (short)KeywordID::kBorderBottomRightRadius},
    {offsetof(struct StringPool_t, StringPool_str73),
     (short)KeywordID::kMinHeight},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str75),
     (short)KeywordID::kExposureScreenMarginBottom},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str77),
     (short)KeywordID::kItemkeys},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str80),
     (short)KeywordID::kStickyOffset},
    {offsetof(struct StringPool_t, StringPool_str81),
     (short)KeywordID::kExposureUiMarginBottom},
    {offsetof(struct StringPool_t, StringPool_str82),
     (short)KeywordID::kExposureScreenMarginTop},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str85),
     (short)KeywordID::kScrollDirection},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str87),
     (short)KeywordID::kScrollOrientation},
    {offsetof(struct StringPool_t, StringPool_str88),
     (short)KeywordID::kExposureUiMarginTop},
    {offsetof(struct StringPool_t, StringPool_str89),
     (short)KeywordID::kScrollBarEnable},
    {offsetof(struct StringPool_t, StringPool_str90),
     (short)KeywordID::kMaskOrigin},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str92),
     (short)KeywordID::kNeedsVisibleCells},
    {offsetof(struct StringPool_t, StringPool_str93),
     (short)KeywordID::kCursor},
    {offsetof(struct StringPool_t, StringPool_str94),
     (short)KeywordID::kExposureScene},
    {offsetof(struct StringPool_t, StringPool_str95), (short)KeywordID::kText},
    {offsetof(struct StringPool_t, StringPool_str96),
     (short)KeywordID::kRichtype},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str98),
     (short)KeywordID::kCaretColor},
    {offsetof(struct StringPool_t, StringPool_str99),
     (short)KeywordID::kEditOnFocus},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str102),
     (short)KeywordID::kTextIndent},
    {offsetof(struct StringPool_t, StringPool_str103),
     (short)KeywordID::kBorderTopRightRadius},
    {offsetof(struct StringPool_t, StringPool_str104),
     (short)KeywordID::kBounce},
    {offsetof(struct StringPool_t, StringPool_str105),
     (short)KeywordID::kTextGradient},
    {offsetof(struct StringPool_t, StringPool_str106),
     (short)KeywordID::kTextMaxline},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str114),
     (short)KeywordID::kMaxHeight},
    {offsetof(struct StringPool_t, StringPool_str115),
     (short)KeywordID::kBackgroundRepeat},
    {offsetof(struct StringPool_t, StringPool_str116),
     (short)KeywordID::kBorderLeftColor},
    {offsetof(struct StringPool_t, StringPool_str117),
     (short)KeywordID::kScrollX},
    {offsetof(struct StringPool_t, StringPool_str118),
     (short)KeywordID::kBounces},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str122),
     (short)KeywordID::kBlurRadius},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str125),
     (short)KeywordID::kIgnoreFocus},
    {offsetof(struct StringPool_t, StringPool_str126),
     (short)KeywordID::kScrollBarAutoHide},
    {offsetof(struct StringPool_t, StringPool_str127),
     (short)KeywordID::kBackgroundImage},
    {offsetof(struct StringPool_t, StringPool_str128),
     (short)KeywordID::kMaxlines},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str130),
     (short)KeywordID::kSkipRedirection},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str132),
     (short)KeywordID::kCapInsets},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str134),
     (short)KeywordID::kSendComposingInput},
    {offsetof(struct StringPool_t, StringPool_str135),
     (short)KeywordID::kSelect},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str137),
     (short)KeywordID::kContent},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str139),
     (short)KeywordID::kScrollWithoutFocus},
    {offsetof(struct StringPool_t, StringPool_str140),
     (short)KeywordID::kMaskPosition},
    {offsetof(struct StringPool_t, StringPool_str141),
     (short)KeywordID::kListType},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str145),
     (short)KeywordID::kConfirmType},
    {offsetof(struct StringPool_t, StringPool_str146),
     (short)KeywordID::kMarkdownStyle},
    {offsetof(struct StringPool_t, StringPool_str147),
     (short)KeywordID::kZIndex},
    {offsetof(struct StringPool_t, StringPool_str148),
     (short)KeywordID::kTextAlign},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str152),
     (short)KeywordID::kBorderWidth},
    {offsetof(struct StringPool_t, StringPool_str153),
     (short)KeywordID::kConsumeSlideEvent},
    {offsetof(struct StringPool_t, StringPool_str154),
     (short)KeywordID::kControls},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str156),
     (short)KeywordID::kOutline},
    {offsetof(struct StringPool_t, StringPool_str157),
     (short)KeywordID::kNextFocusLeft},
    {offsetof(struct StringPool_t, StringPool_str158),
     (short)KeywordID::kHitSlop},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str160),
     (short)KeywordID::kBackgroundSize},
    {offsetof(struct StringPool_t, StringPool_str161),
     (short)KeywordID::kBackgroundOrigin},
    {offsetof(struct StringPool_t, StringPool_str162),
     (short)KeywordID::kAutoSize},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str164),
     (short)KeywordID::kOutlineColor},
    {offsetof(struct StringPool_t, StringPool_str165),
     (short)KeywordID::kAdjustMode},
    {offsetof(struct StringPool_t, StringPool_str166),
     (short)KeywordID::kOutlineStyle},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str168),
     (short)KeywordID::kNextScrollable},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str170),
     (short)KeywordID::kScrollBarThumbColor},
    {offsetof(struct StringPool_t, StringPool_str171),
     (short)KeywordID::kLineHeight},
    {offsetof(struct StringPool_t, StringPool_str172),
     (short)KeywordID::kTransform},
    {offsetof(struct StringPool_t, StringPool_str173),
     (short)KeywordID::kBorderBottomWidth},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str175),
     (short)KeywordID::kWordBreak},
    {offsetof(struct StringPool_t, StringPool_str176),
     (short)KeywordID::kScrollBarThumbHoverColor},
    {offsetof(struct StringPool_t, StringPool_str177),
     (short)KeywordID::kScrollBarThumbActiveColor},
    {offsetof(struct StringPool_t, StringPool_str178),
     (short)KeywordID::kBorderTopColor},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str182), (short)KeywordID::kSrc},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str185),
     (short)KeywordID::kScrollBarThumbRadius},
    {offsetof(struct StringPool_t, StringPool_str186),
     (short)KeywordID::kPlaceholder},
    {offsetof(struct StringPool_t, StringPool_str187),
     (short)KeywordID::kVisible},
    {offsetof(struct StringPool_t, StringPool_str188),
     (short)KeywordID::kBorderRightColor},
    {offsetof(struct StringPool_t, StringPool_str189),
     (short)KeywordID::kBorderRightStyle},
    {offsetof(struct StringPool_t, StringPool_str190), (short)KeywordID::kTag},
    {offsetof(struct StringPool_t, StringPool_str191),
     (short)KeywordID::kTextStrokeColor},
    {offsetof(struct StringPool_t, StringPool_str192),
     (short)KeywordID::kScrollBackwardMode},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str197),
     (short)KeywordID::kScrollEventThrottle},
    {offsetof(struct StringPool_t, StringPool_str198),
     (short)KeywordID::kNextFocusUp},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str200),
     (short)KeywordID::kColor},
    {offsetof(struct StringPool_t, StringPool_str201),
     (short)KeywordID::kTextDecoration},
    {offsetof(struct StringPool_t, StringPool_str202),
     (short)KeywordID::kNextFocusRight},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str204),
     (short)KeywordID::kBorderTopWidth},
    {offsetof(struct StringPool_t, StringPool_str205),
     (short)KeywordID::kColumnCount},
    {offsetof(struct StringPool_t, StringPool_str206),
     (short)KeywordID::kCapInsetsScale},
    {offsetof(struct StringPool_t, StringPool_str207),
     (short)KeywordID::kTransition},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str209),
     (short)KeywordID::kScrollBarWidth},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str212),
     (short)KeywordID::kScrollY},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str214),
     (short)KeywordID::kFontWeight},
    {offsetof(struct StringPool_t, StringPool_str215),
     (short)KeywordID::kFontSize},
    {offsetof(struct StringPool_t, StringPool_str216),
     (short)KeywordID::kFontStyle},
    {offsetof(struct StringPool_t, StringPool_str217),
     (short)KeywordID::kPreventLoadingOnListScroll},
    {offsetof(struct StringPool_t, StringPool_str218),
     (short)KeywordID::kListMainAxisGap},
    {offsetof(struct StringPool_t, StringPool_str219),
     (short)KeywordID::kDataset},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str221),
     (short)KeywordID::kWhiteSpace},
    {offsetof(struct StringPool_t, StringPool_str222),
     (short)KeywordID::kEnableNewAnimator},
    {offsetof(struct StringPool_t, StringPool_str223),
     (short)KeywordID::kImageTransitionStyle},
    {offsetof(struct StringPool_t, StringPool_str224),
     (short)KeywordID::kAlignFocus},
    {offsetof(struct StringPool_t, StringPool_str225),
     (short)KeywordID::kShowSoftInputOnfocus},
    {offsetof(struct StringPool_t, StringPool_str226),
     (short)KeywordID::kExperimentalRecycleStickyItem},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str229),
     (short)KeywordID::kInitialScrollOffset},
    {offsetof(struct StringPool_t, StringPool_str230),
     (short)KeywordID::kTextMaxlength},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str232), (short)KeywordID::kMode},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str234),
     (short)KeywordID::kVerticalOrientation},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str236),
     (short)KeywordID::kSpeed},
    {offsetof(struct StringPool_t, StringPool_str237),
     (short)KeywordID::kMaxlength},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str240),
     (short)KeywordID::kIntersectionObservers},
    {offsetof(struct StringPool_t, StringPool_str241),
     (short)KeywordID::kUiappear},
    {offsetof(struct StringPool_t, StringPool_str242),
     (short)KeywordID::kScrollToId},
    {offsetof(struct StringPool_t, StringPool_str243),
     (short)KeywordID::kBackgroundClip},
    {offsetof(struct StringPool_t, StringPool_str244),
     (short)KeywordID::kItemKey},
    {offsetof(struct StringPool_t, StringPool_str245),
     (short)KeywordID::kPreload},
    {offsetof(struct StringPool_t, StringPool_str246),
     (short)KeywordID::kAutoFix},
    {offsetof(struct StringPool_t, StringPool_str247),
     (short)KeywordID::kOverflowX},
    {offsetof(struct StringPool_t, StringPool_str248),
     (short)KeywordID::kFocusable},
    {offsetof(struct StringPool_t, StringPool_str249),
     (short)KeywordID::kExposureId},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str253),
     (short)KeywordID::kAnimation},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str255),
     (short)KeywordID::kSticky},
    {offsetof(struct StringPool_t, StringPool_str256),
     (short)KeywordID::kBackgroundColor},
    {offsetof(struct StringPool_t, StringPool_str257),
     (short)KeywordID::kFocus},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str259),
     (short)KeywordID::kTextShadow},
    {offsetof(struct StringPool_t, StringPool_str260),
     (short)KeywordID::kListCrossAxisGap},
    {offsetof(struct StringPool_t, StringPool_str261),
     (short)KeywordID::kTransformOrigin},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str263),
     (short)KeywordID::kClipPath},
    {offsetof(struct StringPool_t, StringPool_str264),
     (short)KeywordID::kLineSpacing},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str266),
     (short)KeywordID::kLoopCount},
    {offsetof(struct StringPool_t, StringPool_str267),
     (short)KeywordID::kLetterSpacing},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str269),
     (short)KeywordID::kBoxShadow},
    {offsetof(struct StringPool_t, StringPool_str270),
     (short)KeywordID::kDirection},
    {offsetof(struct StringPool_t, StringPool_str271),
     (short)KeywordID::kEventThrough},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str273),
     (short)KeywordID::kPlaceholderColor},
    {offsetof(struct StringPool_t, StringPool_str274),
     (short)KeywordID::kFilter},
    {offsetof(struct StringPool_t, StringPool_str275),
     (short)KeywordID::kAllowEscape},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str277),
     (short)KeywordID::kUpperThresholdItemCount},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str279),
     (short)KeywordID::kValue},
    {offsetof(struct StringPool_t, StringPool_str280),
     (short)KeywordID::kTextSingleLineVerticalAlign},
    {offsetof(struct StringPool_t, StringPool_str281),
     (short)KeywordID::kEnableFontScaling},
    {offsetof(struct StringPool_t, StringPool_str282),
     (short)KeywordID::kEnableScrollbar},
    {offsetof(struct StringPool_t, StringPool_str283), (short)KeywordID::kLoop},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str288),
     (short)KeywordID::kSmartScroll},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str292),
     (short)KeywordID::kScrollBarThumbWidth},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str295),
     (short)KeywordID::kListContainerInfo},
    {offsetof(struct StringPool_t, StringPool_str296),
     (short)KeywordID::kTextSelection},
    {offsetof(struct StringPool_t, StringPool_str297),
     (short)KeywordID::kScrollBarThumbMinLength},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str301),
     (short)KeywordID::kImageConfig},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str304),
     (short)KeywordID::kBackgroundPosition},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str306),
     (short)KeywordID::kUidisappear},
    {offsetof(struct StringPool_t, StringPool_str307),
     (short)KeywordID::kEnableExposureUiMargin},
    {offsetof(struct StringPool_t, StringPool_str308),
     (short)KeywordID::kNextFocusFallback},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str310),
     (short)KeywordID::kBorderRightWidth},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str312),
     (short)KeywordID::kScrollBarAutoHideDelay},
    {offsetof(struct StringPool_t, StringPool_str313),
     (short)KeywordID::kBackground},
    {offsetof(struct StringPool_t, StringPool_str314),
     (short)KeywordID::kOverflow},
    {offsetof(struct StringPool_t, StringPool_str315),
     (short)KeywordID::kBorderLeftWidth},
    {offsetof(struct StringPool_t, StringPool_str316),
     (short)KeywordID::kInitialScrollIndex},
    {offsetof(struct StringPool_t, StringPool_str317),
     (short)KeywordID::kVerticalAlign},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str321),
     (short)KeywordID::kUserInteractionEnabled},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str324),
     (short)KeywordID::kFullScreen},
    {offsetof(struct StringPool_t, StringPool_str325),
     (short)KeywordID::kUseSoftKeyboard},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str327),
     (short)KeywordID::kBlockNativeEvent},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str334),
     (short)KeywordID::kScrollToIndex},
    {offsetof(struct StringPool_t, StringPool_str335),
     (short)KeywordID::kFocusIndex},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str337),
     (short)KeywordID::kExposureArea},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str340),
     (short)KeywordID::kPreferredFocusChild},
    {offsetof(struct StringPool_t, StringPool_str341),
     (short)KeywordID::kAutoplay},
    {offsetof(struct StringPool_t, StringPool_str342),
     (short)KeywordID::kOverflowY},
    {offsetof(struct StringPool_t, StringPool_str343),
     (short)KeywordID::kReadonly},
    {offsetof(struct StringPool_t, StringPool_str344),
     (short)KeywordID::kNextFocusDown},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str350),
     (short)KeywordID::kPlaceholderFontWeight},
    {offsetof(struct StringPool_t, StringPool_str351),
     (short)KeywordID::kPlaceholderFontSize},
    {offsetof(struct StringPool_t, StringPool_str352),
     (short)KeywordID::kImageRendering},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str357),
     (short)KeywordID::kUpdateAnimation},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str369),
     (short)KeywordID::kExperimentalUpdateStickyForDiff},
    {offsetof(struct StringPool_t, StringPool_str370),
     (short)KeywordID::kVisibility},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str386),
     (short)KeywordID::kLevel},
    {offsetof(struct StringPool_t, StringPool_str387),
     (short)KeywordID::kEnableScroll},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str390),
     (short)KeywordID::kTextStrokeWidth},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str396),
     (short)KeywordID::kAutoSaveLastChild},
    {offsetof(struct StringPool_t, StringPool_str397),
     (short)KeywordID::kFontFamily},
    {offsetof(struct StringPool_t, StringPool_str398),
     (short)KeywordID::kExperimentalBatchRenderStrategy},
    {offsetof(struct StringPool_t, StringPool_str399),
     (short)KeywordID::kAnimationStyle},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str408),
     (short)KeywordID::kOutlineWidth},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str413),
     (short)KeywordID::kXAppRegion},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str419),
     (short)KeywordID::kTextOverflow},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str428),
     (short)KeywordID::kFullscreenMode},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str435),
     (short)KeywordID::kAccessibilityElement},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str440),
     (short)KeywordID::kLowerThresholdItemCount},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str445),
     (short)KeywordID::kDisabled},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str452),
     (short)KeywordID::kAccessibilityElements},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str464),
     (short)KeywordID::kLowQuality},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str475),
     (short)KeywordID::kUpperThreshold},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str477),
     (short)KeywordID::kXAutoFontSize},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str483),
     (short)KeywordID::kOpacity},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str493),
     (short)KeywordID::kEnableNestedScroll},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str500),
     (short)KeywordID::kUpdateListInfo},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str503),
     (short)KeywordID::kXAutoFontSizePresetSizes},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str509),
     (short)KeywordID::kAnimationVelocity},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str517),
     (short)KeywordID::kFocusSmoothScroll},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str523),
     (short)KeywordID::kDropShadow},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str543),
     (short)KeywordID::kAccessibilityLabel},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str593),
     (short)KeywordID::kDeferSrcInvalidation},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {offsetof(struct StringPool_t, StringPool_str638),
     (short)KeywordID::kLowerThreshold}};

const struct TokenValue *KeywordHash::find(const char *str, unsigned int len) {
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH) {
    unsigned int key = hash(str, len);

    if (key <= MAX_HASH_VALUE) {
      int o = wordlist[key].name;
      if (o >= 0) {
        const char *s = o + StringPool;

        if (*str == *s && !strcmp(str + 1, s + 1)) return &wordlist[key];
      }
    }
  }
  return 0;
}

static_assert(sizeof(StringPool_contents) < 32767);

KeywordID GetKeywordID(const std::string &str) {
  auto *tk = KeywordHash::find(str.c_str(), str.size());
  return tk ? static_cast<KeywordID>(tk->id) : KeywordID::kInvalid;
}

}  // namespace clay
