# Copyright 2021 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.

ui_net_sources = [
  "cache/cache_stats.cc",
  "cache/cache_stats.h",
  "cache/net_disk_cache.cc",
  "cache/net_disk_cache.h",
  "cache/net_resource_cache_key.cc",
  "cache/net_resource_cache_key.h",
  "fetcher/http_resource_fetcher.cc",
  "fetcher/http_resource_fetcher.h",
  "fetcher/http_resource_fetcher_factory.cc",
  "fetcher/http_resource_fetcher_factory.h",
  "fetcher/http_resource_fetcher_host.cc",
  "fetcher/http_resource_fetcher_host.h",
  "net_loader_callback.cc",
  "net_loader_callback.h",
  "net_loader_manager.cc",
  "net_loader_manager.h",
]

ui_net_url_parse_sources = [
  "macros.h",
  "url/uri.cc",
  "url/uri.h",
  "url/url_helper.cc",
  "url/url_helper.h",
  "url/url_parse.cc",
  "url/url_parse.h",
  "url/url_parse_internal.cc",
  "url/url_parse_internal.h",
]
