name: build windows explorer

description: build windows explorer apk.

inputs:
  build-arch:
    description: The architecture of explorer we are building. It could be x64,x86
    required: true
runs:
  using: composite
  steps:
    - name: Python Setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Setup Node.js 18.20.0
      uses: actions/setup-node@v6
      with:
        node-version: '18.20.0'
    - name: Get npm customcache directory
      id: npm-custom-cache-dir
      shell: pwsh
      run: |
        $npm_custom_cache_dir = python -c "import os; import pathlib; print(os.path.join(pathlib.Path.home(), '.pnpm', 'v3'))"
        echo "NPM_CUSTOM_CACHE_DIR=$npm_custom_cache_dir" >> ${env:GITHUB_OUTPUT}
    - name: Cache pnpm Dependencies
      uses: lynx-infra/cache@5c6160a6a4c7fca80a2f3057bb9dfc9513fcb732
      with:
        path: ${{ steps.npm-custom-cache-dir.outputs.NPM_CUSTOM_CACHE_DIR }}
        key: pnpm-custom-${{ runner.os }}-${{ hashFiles('lynx/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-custom-${{ runner.os }}-
    - name: Get habitat cache key
      id: hab
      shell: pwsh
      run: |
        if ([string]::IsNullOrEmpty("clay")) {
          python lynx/tools/ci/habitat_cache_helper.py
        } else {
          python lynx/tools/ci/habitat_cache_helper.py --target clay
        }

    - name: Get habitat cache directory
      id: hab-cache-dir
      shell: pwsh
      run: |
        $habitat_cache_dir = python -c "import os; import tempfile; print(os.path.join(os.environ.get('HOME', tempfile.gettempdir()), '.habitat_cache'))"
        echo "ssss"
        echo $habitat_cache_dir
        echo "HABITAT_CACHE_DIR=$habitat_cache_dir"
        echo "HABITAT_CACHE_DIR=$habitat_cache_dir" >> ${env:GITHUB_OUTPUT}

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: pwsh
      run: |
        $npm_cache_dir = python -c "import os; import pathlib; print(os.path.join(pathlib.Path.home(), '.local', 'share', 'pnpm', 'store'))"
        echo "ssss"
        echo $npm_cache_dir
        echo "NPM_CACHE_DIR=$npm_cache_dir"
        echo "NPM_CACHE_DIR=$npm_cache_dir" >> ${env:GITHUB_OUTPUT}

    - name: Get Python Cache Directory
      id: pip
      shell: pwsh
      run: |
        $cache = python -m pip cache dir
        $correctPath = (Get-Item $cache).FullName
        echo "ssss"
        echo $correctPath
        echo "PIP_CACHE_DIR=$correctPath"
        echo "PIP_CACHE_DIR=$correctPath" >> ${env:GITHUB_OUTPUT}

    - name: Setup cache action
      uses: lynx-infra/cache@5c6160a6a4c7fca80a2f3057bb9dfc9513fcb732
      with:
        path: ${{ steps.hab-cache-dir.outputs.HABITAT_CACHE_DIR }}
        key: hab-${{ runner.os }}-${{ steps.hab.outputs.HABITAT_TARGETS }}-${{ steps.hab.outputs.HABITAT_DEPS_FILE_DIGEST }}
        restore-keys: |
          hab-${{ runner.os }}-${{ steps.hab.outputs.HABITAT_TARGETS }}-

    - name: Setup cache action
      uses: actions/cache@v4
      with:
        path: ${{ steps.hab-cache-dir.outputs.HABITAT_CACHE_DIR }}
        key: hab-${{ runner.os }}-${{ steps.hab.outputs.HABITAT_TARGETS }}-${{ steps.hab.outputs.HABITAT_DEPS_FILE_DIGEST }}
        restore-keys: |
          hab-${{ runner.os }}-${{ steps.hab.outputs.HABITAT_TARGETS }}-

    - name: Python Requirements Cache
      uses: lynx-infra/cache@5c6160a6a4c7fca80a2f3057bb9dfc9513fcb732
      with:
        path: ${{ steps.pip.outputs.PIP_CACHE_DIR }}
        key: pip-${{ runner.os }}-${{ hashFiles('lynx/tools/vpython_tools/requirements.txt', 'lynx/testing/integration_test/test_script/requirements.txt') }}
        restore-keys: |
          pip-${{ runner.os }}-

    - name: Cache pnpm Dependencies
      uses: lynx-infra/cache@5c6160a6a4c7fca80a2f3057bb9dfc9513fcb732
      with:
        # set pnpm store path to a specific value since we can't get it via `pnpm store path` before pnpm is setup.
        path: ${{ steps.npm-cache-dir.outputs.NPM_CACHE_DIR }}
        key: pnpm-${{ runner.os }}-${{ hashFiles('lynx/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-${{ runner.os }}-

    - name: Install Python dependencies
      shell: pwsh
      run: |
        python -m pip install -r lynx/tools/vpython_tools/requirements.txt
        python -m pip install -r lynx/testing/integration_test/test_script/requirements.txt

    - name: run habitat sync
      shell: pwsh
      working-directory: lynx
      run: |
        if ([string]::IsNullOrEmpty("clay")) {
            powershell.exe -Command "& .\tools\hab.ps1 sync ."
        } else {
            powershell.exe -Command "& .\tools\hab.ps1 sync . --target clay"
        }
      env:
        HABITAT_CONCURRENCY: 2
        npm_config_store_dir: ${{ steps.npm-cache-dir.outputs.NPM_CACHE_DIR }}
    - name: Build Explorer App
      shell: pwsh
      run: |-
        cd lynx
        $env:vs2022_install = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\BuildTools"
        $env:DEPOT_TOOLS_WIN_TOOLCHAIN = 0
        $env:GYP_MSVS_OVERRIDE_PATH = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\BuildTools"
        $env:WINDOWSSDKDIR = "${env:ProgramFiles(x86)}\Windows Kits\10"
        .\tools\envsetup.ps1
        # .\buildtools\node\pnpm install
        $PSNativeCommandArgumentPassing = 'Legacy'
        .\buildtools\gn\gn.exe gen out\Default --args='target_cpu=\"${{ inputs.build-arch }}\" desktop_enable_embedder_layer=true enable_clay_standalone=true disable_visibility_hidden=true use_ndk_static_cxx=false enable_linker_map=false enable_clay=true is_headless=true skia_enable_flutter_defines=true skia_use_dng_sdk=false skia_use_sfntly=false skia_enable_pdf=false skia_enable_svg=true enable_svg=true skia_enable_skottie=true skia_use_x11=false skia_use_wuffs=true skia_use_expat=true skia_use_fontconfig=false clay_enable_skshaper=true skia_use_icu=true allow_deprecated_api_calls=true stripped_symbols=true is_official_build=true enable_lto=false is_clang=true enable_lepusng_worklet=true enable_napi_binding=true is_debug=false enable_inspector=true enable_libcpp_abi_namespace_cr=true jsengine_type=\"quickjs\"' --ide=vs
        .\buildtools\ninja\ninja.exe -C out\Default explorer\windows\lynx_explorer:copy_resources
        .\buildtools\ninja\ninja.exe -C out\Default explorer\windows\lynx_explorer:copy_devtool_resources
        .\buildtools\ninja\ninja.exe -C out\Default explorer\windows\lynx_explorer:build_card_resources
        .\buildtools\ninja\ninja.exe -C out\Default explorer platform\windows:package_sdk
        tar --strip-components 3 -czvf LynxExplorer-windows-${{ inputs.build-arch }}.tar.gz out/Default/lynx_explorer
