# Copyright 2021 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.

group("telemetry") {
  testonly = true
  deps = [
    "base:base_benchmark",
    "lepus:lepus_benchmark",
    "styling/css:css_invalidation_benchmark",
    "styling/css:css_variable_handler_benchmark",
    "styling/css:fiber_restyle_benchmark",
    "styling/css:selector_matcher_benchmark",
  ]
}
