name: publish ios sdk

description: package ios source code, upload the zip to release and publish the podspec file to cocoapods

inputs:
  version:
    required: false
    description: The version of pod.
    type: string
  tag:
    required: false
    type: string
    description: The tag for release.
  component:
    required: false
    type: string
    default: 'all'
  cocoapods_trunk_token:
    description: The secret key of the sdk to publish
    type: string
  github_token:
    description: The github token
    type: string

runs:
  using: composite
  steps:
    - name: Prepare cocoapods publish source
      shell: bash
      run: |-
        cd $GITHUB_WORKSPACE/lynx
        source tools/envsetup.sh
        python3 tools/ios_tools/cocoapods_publish_helper.py --prepare-source --tag ${{ inputs.tag }} --version ${{ inputs.version }} --component ${{ inputs.component }}
    - name: Push iOS SDK to release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ inputs.tag }}
        token: ${{ inputs.github_token }}
        artifacts: '${{ github.workspace }}/lynx/*.zip'
        replacesArtifacts: true
        allowUpdates: true
        body: ''
    - name: Publish to CocoaPods Repo
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ inputs.cocoapods_trunk_token }}
      shell: bash
      run: |-
        cd $GITHUB_WORKSPACE/lynx
        source tools/envsetup.sh
        git config --global user.name "lynx.authors"
        git config --global user.email "lynx.authors@users.noreply.github.com"
        python3 tools/ios_tools/skip_pod_lint.py --source public
        python3 tools/ios_tools/cocoapods_publish_helper.py --publish --component ${{ inputs.component }}
