quirksMode:
  description:
  defaultValue: 'base::Version(1, 5)'
  valueType: base::Version
  syncTo:
    - script
  codeGen:
    - NONE
customCSSInheritanceList:
  description:
  defaultValue: null
  valueType: std::unordered_set<CSSPropertyID>
  syncTo:
    - script
  codeGen:
    - NONE
extraInfo:
  description: user defined extraInfo.
  defaultValue: null
  valueType: lepus::Value
  syncTo:
    - script
  codeGen:
    - MEMBER
version:
  description: null
  defaultValue: null
  valueType: string
  syncTo:
    - platform
    - script
cli:
  description: cli version
  defaultValue: null
  valueType: string
  syncTo:
    - script
reactVersion:
  description:
  defaultValue: null
  valueType: string
  syncTo:
    - script
customData:
  description:
  defaultValue: null
  valueType: string
  syncTo:
    - script
tapSlop:
  description:
  defaultValue: 50px
  valueType: string
  syncTo:
    - script
preferredFps:
  description:
  defaultValue: auto
  valueType: string
  syncTo:
    - script
enableLynxScrollFluency:
  description:
  defaultValue: -1
  valueType: double
  syncTo:
    - script
  codeGen:
    - NONE
lepusGCThreshold:
  description: GC threshold of lepusNG. Let default value be 256, and the unit is KB.
  defaultValue: 256
  valueType: int64_t
  syncTo:
    - script
observerFrameRate:
  description:
  defaultValue: 20
  valueType: int32_t
  syncTo:
    - script
longPressDuration:
  description:
  defaultValue: -1
  valueType: int32_t
  syncTo:
    - script
lepusQuickjsStacksize:
  description: null
  defaultValue: 0
  valueType: uint32_t
  syncTo:
    - script
logBoxImageSizeWarningThreshold:
  description: null
  defaultValue: 1000000
  valueType: uint32_t
  syncTo:
    - script
bundleModuleMode:
  description:
  defaultValue: PackageInstanceBundleModuleMode::EVAL_REQUIRE_MODE
  valueType: PackageInstanceBundleModuleMode
  syncTo:
    - script
  codeGen:
    - MEMBER
mapContainerType:
  description:
  defaultValue: 0
  valueType: uint8_t
  syncTo:
    - script
DSL:
  description:
  defaultValue: PackageInstanceDSL::TT
  valueType: PackageInstanceDSL
  syncTo:
    - script
  codeGen:
    - MEMBER
useNewImage:
  description: null
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
enableTextBoringLayout:
  description: Enable Android text BoringLayout.
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
enableTextLayerRender:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
enableTextLayoutCache:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
enableAsyncResolveSubtree:
  description:
    FE Framework use this config to notify Engine that resolve subtree
    binding will be triggered when render DOM (Not exposed to normal user)
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
  author: 'usczz'
# native page config begin
enableSignalAPI:
  description: Enable Signal API
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
  author: 'ShouruiSong'
trailNewImage:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
  author: 'liubb0516'
asyncRedirect:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
enableUseMapBuffer:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
  author: 'nhsprite'
enableUIOperationOptimize:
  description: Introduced in 2.16, enable the optimization about UIOperation batching and CreateViewAsync at Android.
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
  author: 'Awuiil'
enableNativeList:
  description: Indicates whether use c++ list.
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
  author: 'DwwWxx'
enableFiberElementForRadonDiff:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
  author: 'DragonDragonDDD'
enableMicrotaskPromisePolyfill:
  description: Enable microtask promise polyfill.
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
  author: 'huzhanbo1996'
enableOptPushStyleToBundle:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
  author: 'ShouruiSong'
enableNativeScheduleCreateViewAsync:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
  author: 'ShouruiSong'
enableUnifiedPipeline:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
  author: 'nhsprite'
enableUseContextPool:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
  codeGen:
    - DECODE
enableCSSLazyImport:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
  codeGen:
    - DECODE
enableNewAnimator:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
  codeGen:
    - DECODE
enableComponentAsyncDecode:
  description: Enable dynamic components to be decoded in child threads before they are delivered into tasm in async-loading.
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  syncTo:
    - script
  codeGen:
    - DECODE
# native page config end
flatten:
  description: null
  defaultValue: true
  valueType: bool
  syncTo:
    - platform
    - script
implicit:
  description: null
  defaultValue: true
  valueType: bool
  syncTo:
    - script
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_0
      value: 'false'
lepusStrict:
  description: null
  defaultValue: false
  valueType: bool
  syncTo:
    - script
lepusNullPropAsUndef:
  description: null
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_1_6
      value: 'true'
dataStrictMode:
  description: null
  defaultValue: true
  valueType: bool
  syncTo:
    - script
enableAsyncDisplay:
  description: null
  defaultValue: true
  valueType: bool
  syncTo:
    - script
enableImageDownsampling:
  description: null
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableNewImage:
  description: null
  defaultValue: true
  valueType: bool
  syncTo:
    - script
enableTextNonContiguousLayout:
  description: null
  defaultValue: true
  valueType: bool
  syncTo:
    - script
enableViewReceiveTouch:
  description: null
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableEventThrough:
  description: null
  defaultValue: false
  valueType: bool
  syncTo:
    - script
removeComponentElement:
  description: null
  defaultValue: false
  valueType: bool
  syncTo:
    - script
strictPropType:
  description: null
  defaultValue: false
  valueType: bool
  syncTo:
    - script
syncImageAttach:
  description: null
  defaultValue: true
  valueType: bool
  syncTo:
    - script
useImagePostProcessor:
  description: null
  defaultValue: false
  valueType: bool
  syncTo:
    - script
useNewSwiper:
  description: null
  defaultValue: true
  valueType: bool
  syncTo:
    - script
enableAsyncInitVideoEngine:
  description: null
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableComponentLifecycleAlignWebview:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableListNewArchitecture:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableNewListContainer:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableListPlug:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableListMoveOperation:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableCreateViewAsync:
  description:
  defaultValue: true
  valueType: bool
  syncTo:
    - script
enableVsyncAlignedFlush:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableAccessibilityElement:
  description:
  defaultValue: true
  valueType: bool
  syncTo:
    - script
enableOverlapForAccessibilityElement:
  description:
  defaultValue: true
  valueType: bool
  syncTo:
    - script
enableNewAccessibility:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableNewLayoutOnly:
  description:
  defaultValue: true
  valueType: bool
  syncTo:
    - script
enableReactOnlyPropsId:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableGlobalComponentMap:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableTextRefactor:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_2
      value: 'true'
enableTextOverflow:
  description: Set text overflow as visible if true.
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_8
      value: 'true'
enableNewClipMode:
  description: Set new clip mode if true.
  defaultValue: true
  valueType: bool
  syncTo:
    - script
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_10
      value: 'true'
autoResumeAnimation:
  description:
  defaultValue: true
  valueType: bool
  syncTo:
    - script
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_3
      value: 'true'
enableNewTransformOrigin:
  description: If this flag is true, new transform origin algorithm will apply.
  defaultValue: true
  valueType: bool
  syncTo:
    - script
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_6
      value: 'true'
enableCircularDataCheck:
  description: If this flag is true, circular data check will enable when convert js value to other vale.
  defaultValue: true
  valueType: bool
  syncTo:
    - script
enableReduceInitDataCopy:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableSimultaneousTap:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableComponentLayoutOnly:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_6
      value: 'true'
extendedLayoutOnlyOpt:
  description: A config to force make some special properties can be used to layout only (such as direction&text-align,etc.).
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_13
      value: 'true'
enableTouchRefactor:
  description: Default value is false. If this flag is true, the external gesture which's state is possible or began will not cancel the Lynx iOS touch gesture see issue:#7920.
  defaultValue: true
  valueType: bool
  syncTo:
    - script
enableEndGestureAtLastFingerUp:
  description: In the previous commit, when determining whether all fingers had moved off the screen in multiple touch scenarios, touch.view was used for judgment. However, in a scrolling container, touch.view obtained from touchesEnd/touchesMove could be nil, resulting in incorrect judgment of whether all fingers had moved off the screen. _touches could not be cleared, leading to a subsequent failure to trigger tap events. To fix this issue, we added null checks before calling touch.view, and ended the gesture if _touches was empty. This resolved the problem. Only for ios, detail can see f-12375631 and its mr.
  defaultValue: false
  valueType: bool
  syncTo:
    - script
disableLongpressAfterScroll:
  description: If this flag is true, iOS will not recognize the corresponding long press gesture after triggering scrolling.
  defaultValue: false
  valueType: bool
  syncTo:
    - script
keyboardCallbackPassRelativeHeight:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_2
      value: 'true'
enableNewIntersectionObserver:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  readSettings: true
enableCheckDataWhenUpdatePage:
  description:
  defaultValue: true
  valueType: bool
  syncTo:
    - script
forceCalcNewStyle:
  description:
  defaultValue: true
  valueType: bool
  syncTo:
    - script
  codeGen:
    - MEMBER
enableBackgroundShapeLayer:
  description: Enable iOS background manager to apply shape layer optimization.
  defaultValue: true
  valueType: bool
  syncTo:
    - script
compileRender:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableTextLanguageAlignment:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableXTextLayoutReused:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableRemoveComponentExtraData:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableExposureUIMargin:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableNewGesture:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableCheckLocalImage:
  description:
  defaultValue: true
  valueType: bool
  syncTo:
    - script
enableAsyncRequestImage:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableComponentNullProp:
  description: Support component can be passed null props, null props only supported in LepusNG now. Open this switch to support lepus use null prop.
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableCascadePseudo:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
removeDescendantSelectorScope:
  description: If false, descendant selector only works in component scope.
  defaultValue: true
  valueType: bool
  syncTo:
    - script
  codeGen:
    - MEMBER
autoExpose:
  description:
  defaultValue: true
  valueType: bool
  syncTo:
    - script
disableQuickTracingGC:
  description: Disable tracing gc mode in quick context.
  defaultValue: false
  valueType: bool
  syncTo:
    - script
fixCSSImportRuleOrder:
  description:
  defaultValue: true
  valueType: bool
  syncTo:
    - script
enableReloadLifecycle:
  description: Enable LynxUI onNodeReload lifecycle.
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableA11y:
  description: Enable Android A11y
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  author: 'DwwWxx'
enableA11yIDMutationObserver:
  description: Enable MutationObserver for accessibility.
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  author: 'MoonfaceX'
enableCheckExposureOptimize:
  description: Enable exposure detection optimization.
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  author: 'rAY-ooo'
enableDisexposureWhenLynxHidden:
  description: Enable send disexposure events when lynxview is hidden.
  defaultValue: true
  valueType: bool
  syncTo:
    - script
  author: 'rAY-ooo'
enableExposureWhenLayout:
  description: Enable exposure check when LynxView is layoutRequest
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  author: 'ShouruiSong'
enableAirDetectRemovedKeysWhenUpdateData:
  description: enable Air Mode detect removed keys when updating data from native
  defaultValue: false
  valueType: bool
  syncTo:
    - script
enableJSDataProcessor:
  description: Enable data processor on JS thread
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  author: 'ShouruiSong'
enableMultiTouch:
  description: Enable support multi-finger events
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  author: 'rAY-ooo'
  readSettings: true
enableMultiTouchParamsCompatible:
  description: Enable support multi-finger event parameter compatibility
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  readSettings: true
  author: 'rAY-ooo'
enableJsBindingApiThrowException:
  description: Enable js binding api throw exception
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_14
      value: 'true'
  author: 'lybvinci'
enableICU:
  description: Enable Bind PRIMJS-ICU
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  author: 'OverWatch-Winder'
enableQueryComponentSync:
  description: Enable query component sync in background runtime
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  author: 'Awuiil'
absoluteInContentBound:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  codeGen:
    - DECODE
enableFixedNew:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  codeGen:
    - NONE
enableCSSInheritance:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  codeGen:
    - DECODE
CSSAlignWithLegacyW3C:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  codeGen:
    - DECODE
enableCSSStrictMode:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  codeGen:
    - DECODE
unifyVWVHBehavior:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_3
      value: 'true'
  codeGen:
    - DECODE
fontScaleEffectiveOnlyOnSp:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  codeGen:
    - DECODE
includeFontPadding:
  description:
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  codeGen:
    - DECODE
