#!/usr/bin/env python3
# Copyright 2026 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.

"""Generate Clay keyword declarations and lookup tables with host gperf."""

import argparse
from pathlib import Path
import subprocess
import sys
import tempfile

sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "tools"))
from gperf.gperf import run_gperf, write_if_changed


LICENSE = """// Copyright 2026 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

//
// DO NOT MODIFY THIS FILE! AUTO GENERATED BY Clay keyword code generation.
//
"""

GPERF_TEMPLATE = """%%language=C++
%%define class-name KeywordHash
%%define lookup-function-name find
%%define string-pool-name StringPool
%%struct-type
%%global-table
%%readonly-tables
%%pic

%%{
%(license)s
#include "clay/ui/component/keywords.h"

#include <string>

namespace clay {
%%}

struct TokenValue {
  short name;
  short id;
};

%%%%
%(entries)s
%%%%

static_assert(sizeof(StringPool_contents) < 32767);

KeywordID GetKeywordID(const std::string& str) {
  auto* token = KeywordHash::find(str.c_str(), str.size());
  return token ? static_cast<KeywordID>(token->id) : KeywordID::kInvalid;
}

}  // namespace clay
"""


def camel_case_name(name):
    return "".join(word.capitalize() for word in name.split("-"))


def read_keywords(path):
    keywords = []
    seen = set()
    with Path(path).open(encoding="utf-8") as source:
        for line_number, line in enumerate(source, 1):
            keyword = line.strip()
            if not keyword or keyword.startswith("//"):
                continue
            if keyword in seen:
                raise ValueError(
                    f"{path}:{line_number}: duplicate keyword: {keyword}"
                )
            seen.add(keyword)
            keywords.append(keyword)
    if not keywords:
        raise ValueError(f"No keywords found in {path}")
    return keywords


def generate_header(keywords, template_path):
    template = Path(template_path).read_text(encoding="utf-8")
    if template.count("{{ id_list }}") != 1:
        raise ValueError(
            f"{template_path}: expected exactly one {{{{ id_list }}}}"
        )
    identifiers = ",\n".join(
        f"  k{camel_case_name(keyword)}" for keyword in keywords
    )
    return template.replace("{{ id_list }}", identifiers)


def generate_source(gperf, keywords):
    entries = "\n".join(
        f"{keyword}, (short)KeywordID::k{camel_case_name(keyword)}"
        for keyword in keywords
    )
    contents = GPERF_TEMPLATE % {"license": LICENSE, "entries": entries}
    with tempfile.TemporaryDirectory() as temporary_dir:
        template_path = Path(temporary_dir) / "keywords.gperf"
        template_path.write_text(contents, encoding="utf-8")
        generated = run_gperf(gperf, template_path, ["-m", "100"])
    lines = []
    for line in generated.splitlines(True):
        if line.startswith("#line") or line.startswith("/* Command-line:"):
            continue
        lines.append(line.replace("(int)", "(short)"))
    return "".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gperf", required=True)
    parser.add_argument("--input", required=True)
    parser.add_argument("--header-template", required=True)
    parser.add_argument("--header-output", required=True)
    parser.add_argument("--source-output", required=True)
    args = parser.parse_args()
    try:
        keywords = read_keywords(args.input)
        write_if_changed(
            args.header_output,
            generate_header(keywords, args.header_template),
        )
        write_if_changed(
            args.source_output,
            generate_source(args.gperf, keywords),
        )
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        parser.exit(1, f"Clay keyword generation failed: {error}\n")


if __name__ == "__main__":
    main()
