# Copyright 2026 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.

import("../../../core/Lynx.gni")

shared_library("lynx_clay_shared_library") {
  output_name = "Lynx_clay"

  deps = [
    "..:lynx_rust_capi",
    "../../darwin/macos:lynx_common_deps",
  ]
  if (jsengine_type == "v8") {
    deps += [ "../../../third_party/NativeScript:NativeScript" ]
  }

  ldflags = [
    "-Wl,-install_name,@rpath/libLynx_clay.dylib",
    "-Wl,-exported_symbols_list," +
        rebase_path("exported_symbols.sym", root_build_dir),
  ]

  frameworks = [
    "CoreData.framework",
    "QuartzCore.framework",
    "WebKit.framework",
    "JavaScriptCore.framework",
  ]
}

action("package_sdk") {
  script = "package_sdk.py"
  outputs = [ "$root_build_dir/lynx_clay_sdk_macos_${target_cpu}.zip" ]
  args = [
    rebase_path(outputs[0]),
    rebase_path(root_build_dir),
    rebase_path("../../../third_party/icu/flutter/icudtl.dat"),
  ]
  deps = [
    ":lynx_clay_shared_library",
    "../../darwin/macos:lynx_debug_resources_bundle",
    "../../darwin/macos:lynx_resources_bundle",
  ]
}
