// Copyright 2026 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

package com.lynx.processor.ksp;

import static javax.lang.model.element.Modifier.PUBLIC;
import static javax.lang.model.element.Modifier.STATIC;

import com.google.devtools.ksp.processing.CodeGenerator;
import com.google.devtools.ksp.processing.KSPLogger;
import com.google.devtools.ksp.processing.Resolver;
import com.google.devtools.ksp.symbol.KSAnnotated;
import com.google.devtools.ksp.symbol.KSAnnotation;
import com.google.devtools.ksp.symbol.KSClassDeclaration;
import com.google.devtools.ksp.symbol.KSDeclaration;
import com.google.devtools.ksp.symbol.KSFile;
import com.google.devtools.ksp.symbol.KSFunctionDeclaration;
import com.google.devtools.ksp.symbol.KSTypeReference;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeSpec;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

final class BehaviorGenerator {
  static final String LYNX_BEHAVIOR = "com.lynx.tasm.behavior.LynxBehavior";
  static final String LYNX_ELEMENT = "com.lynx.tasm.behavior.LynxElement";
  static final String LYNX_SHADOW_NODE = "com.lynx.tasm.behavior.LynxShadowNode";
  static final String LYNX_GENERATOR_NAME = "com.lynx.tasm.behavior.LynxGeneratorName";
  private static final String DEFAULT_RENDERER_HOST = "com.lynx.tasm.behavior.render.IRendererHost";

  private final CodeGenerator codeGenerator;
  private final KSPLogger logger;

  BehaviorGenerator(CodeGenerator codeGenerator, KSPLogger logger) {
    this.codeGenerator = codeGenerator;
    this.logger = logger;
  }

  Result generate(Resolver resolver) {
    Map<String, BehaviorInfo> behaviors = new LinkedHashMap<>();
    Map<String, ShadowInfo> shadowNodes = new LinkedHashMap<>();
    Set<KSFile> sourceFiles = new LinkedHashSet<>();
    String packageName = generatorPackage(resolver);

    for (KSClassDeclaration declaration : classes(resolver, LYNX_BEHAVIOR)) {
      KSAnnotation annotation = KspUtils.annotation(declaration, LYNX_BEHAVIOR);
      BehaviorInfo info =
          behaviorInfo(declaration, annotation, KspUtils.stringListArgument(annotation, "tagName"));
      behaviors.put(info.className.reflectionName(), info);
      addSourceFile(sourceFiles, declaration);
      if (packageName.isEmpty()) {
        packageName = KspUtils.packageName(declaration);
      }
    }
    for (KSClassDeclaration declaration : classes(resolver, LYNX_ELEMENT)) {
      KSAnnotation annotation = KspUtils.annotation(declaration, LYNX_ELEMENT);
      BehaviorInfo info = behaviorInfo(declaration, annotation,
          Collections.singletonList(KspUtils.stringArgument(annotation, "name", "")));
      behaviors.put(info.className.reflectionName(), info);
      addSourceFile(sourceFiles, declaration);
      if (packageName.isEmpty()) {
        packageName = KspUtils.packageName(declaration);
      }
    }
    for (KSClassDeclaration declaration : classes(resolver, LYNX_SHADOW_NODE)) {
      KSAnnotation annotation = KspUtils.annotation(declaration, LYNX_SHADOW_NODE);
      String tag = KspUtils.stringArgument(annotation, "tagName", "");
      if (!tag.isEmpty()) {
        shadowNodes.put(tag, new ShadowInfo(className(declaration), declaration));
        addSourceFile(sourceFiles, declaration);
      }
    }

    if (behaviors.isEmpty()) {
      return new Result("", false, sourceFiles);
    }

    try {
      SourceWriter.write(codeGenerator,
          JavaFile.builder(packageName, behaviorType(behaviors.values(), shadowNodes))
              .addFileComment("Generated by com.lynx.processor.LynxBehaviorProcessor")
              .build(),
          sourceFiles);
    } catch (IOException | RuntimeException error) {
      logger.error(error.getMessage() == null ? error.toString() : error.getMessage(), null);
    }
    return new Result(packageName, true, sourceFiles);
  }

  private String generatorPackage(Resolver resolver) {
    for (KSClassDeclaration declaration : classes(resolver, LYNX_GENERATOR_NAME)) {
      String packageName = KspUtils.stringArgument(
          KspUtils.annotation(declaration, LYNX_GENERATOR_NAME), "packageName", "");
      if (!packageName.isEmpty()) {
        return packageName;
      }
    }
    return "";
  }

  private BehaviorInfo behaviorInfo(
      KSClassDeclaration declaration, KSAnnotation annotation, List<String> tags) {
    String rendererHost = KspUtils.typeArgument(annotation, "fragmentLayerRendererHost");
    if ("void".equals(rendererHost) || "java.lang.Void".equals(rendererHost)
        || DEFAULT_RENDERER_HOST.equals(rendererHost)) {
      rendererHost = null;
    }
    return new BehaviorInfo(className(declaration), declaration, tags,
        KspUtils.booleanArgument(annotation, "isCreateAsync", false),
        KspUtils.booleanArgument(annotation, "needProcessDirection", false),
        KspUtils.booleanArgument(annotation, "supportFragmentLayerRender", false), rendererHost,
        hasContextAndObjectConstructor(declaration));
  }

  private TypeSpec behaviorType(
      Iterable<BehaviorInfo> behaviors, Map<String, ShadowInfo> shadowNodes) {
    MethodSpec.Builder method = MethodSpec.methodBuilder("getBehaviors")
                                    .addModifiers(PUBLIC, STATIC)
                                    .returns(ParameterizedTypeName.get(ClassName.get(List.class),
                                        ClassName.get("com.lynx.tasm.behavior", "Behavior")))
                                    .addStatement("$T result = new $T<>()",
                                        ParameterizedTypeName.get(ClassName.get(List.class),
                                            ClassName.get("com.lynx.tasm.behavior", "Behavior")),
                                        ArrayList.class);
    Set<String> consumedShadowTags = new LinkedHashSet<>();
    for (BehaviorInfo info : behaviors) {
      for (String tag : info.tags) {
        if (tag.isEmpty()) {
          continue;
        }
        addBehavior(method, info, tag, shadowNodes.get(tag));
        consumedShadowTags.add(tag);
      }
    }
    for (Map.Entry<String, ShadowInfo> entry : shadowNodes.entrySet()) {
      if (!consumedShadowTags.contains(entry.getKey())) {
        addShadowOnly(method, entry.getKey(), entry.getValue());
      }
    }
    method.addStatement("return result");
    return TypeSpec.classBuilder("BehaviorGenerator")
        .addAnnotation(ClassName.get("androidx.annotation", "Keep"))
        .addModifiers(PUBLIC)
        .addMethod(method.build())
        .build();
  }

  private void addBehavior(
      MethodSpec.Builder method, BehaviorInfo info, String tag, ShadowInfo shadow) {
    ClassName behavior = ClassName.get("com.lynx.tasm.behavior", "Behavior");
    ClassName context = ClassName.get("com.lynx.tasm.behavior", "LynxContext");
    ClassName lynxUi = ClassName.get("com.lynx.tasm.behavior.ui", "LynxUI");
    if (info.supportFragmentLayerRender) {
      method.addCode("result.add(new $T($S, false, $L, $L, true) {\n", behavior, tag,
          info.createAsync, info.needProcessDirection);
    } else {
      method.addCode("result.add(new $T($S, false, $L, $L) {\n", behavior, tag, info.createAsync,
          info.needProcessDirection);
    }
    method.addCode("@$T\n", Override.class);
    if (info.hasParamsConstructor) {
      method.addCode("public $T createUIWithParams($T context, Object params) {\n", lynxUi, context)
          .addStatement("return new $T(context, params)", info.className)
          .addCode("}\n");
    } else {
      method.addCode("public $T createUI($T context) {\n", lynxUi, context)
          .addStatement("return new $T(context)", info.className)
          .addCode("}\n");
    }
    if (info.supportFragmentLayerRender && info.rendererHost != null) {
      method.addCode("@$T\n", Override.class)
          .addCode("public $T createPlatformRendererHost($T context) {\n",
              ClassName.get("com.lynx.tasm.behavior.render", "IRendererHost"), context)
          .addStatement("return new $T(context)", ClassName.bestGuess(info.rendererHost))
          .addCode("}\n");
    }
    if (shadow != null) {
      method.addCode("@$T\n", Override.class)
          .addCode("public $T createShadowNode() {\n",
              ClassName.get("com.lynx.tasm.behavior.shadow", "ShadowNode"))
          .addStatement("return new $T()", shadow.className)
          .addCode("}\n");
    }
    method.addCode("});\n");
  }

  private void addShadowOnly(MethodSpec.Builder method, String tag, ShadowInfo shadow) {
    method
        .addCode(
            "result.add(new $T($S) {\n", ClassName.get("com.lynx.tasm.behavior", "Behavior"), tag)
        .addCode("@$T\n", Override.class)
        .addCode("public $T createShadowNode() {\n",
            ClassName.get("com.lynx.tasm.behavior.shadow", "ShadowNode"))
        .addStatement("return new $T()", shadow.className)
        .addCode("}\n")
        .addCode("});\n");
  }

  private boolean hasContextAndObjectConstructor(KSClassDeclaration declaration) {
    for (KSDeclaration child : KspUtils.toList(declaration.getDeclarations())) {
      if (!(child instanceof KSFunctionDeclaration)
          || !"<init>".equals(child.getSimpleName().asString())) {
        continue;
      }
      KSFunctionDeclaration constructor = (KSFunctionDeclaration) child;
      if (constructor.getParameters().size() != 2) {
        continue;
      }
      String first = typeName(constructor.getParameters().get(0).getType());
      String second = typeName(constructor.getParameters().get(1).getType());
      if ("com.lynx.tasm.behavior.LynxContext".equals(first)
          && ("java.lang.Object".equals(second) || "kotlin.Any".equals(second))) {
        return true;
      }
    }
    return false;
  }

  private static String typeName(KSTypeReference typeReference) {
    return KspUtils.qualifiedName(typeReference.resolve().getDeclaration());
  }

  private static ClassName className(KSClassDeclaration declaration) {
    return ClassName.bestGuess(KspUtils.qualifiedName(declaration));
  }

  private static List<KSClassDeclaration> classes(Resolver resolver, String annotation) {
    List<KSClassDeclaration> result = new ArrayList<>();
    for (KSAnnotated symbol :
        KspUtils.toList(resolver.getSymbolsWithAnnotation(annotation, false))) {
      KSClassDeclaration declaration = KspUtils.asClass(symbol);
      if (declaration != null) {
        result.add(declaration);
      }
    }
    return result;
  }

  private static void addSourceFile(Set<KSFile> files, KSDeclaration declaration) {
    if (declaration.getContainingFile() != null) {
      files.add(declaration.getContainingFile());
    }
  }

  static final class Result {
    final String packageName;
    final boolean hasBehaviors;
    final Set<KSFile> sourceFiles;

    Result(String packageName, boolean hasBehaviors, Set<KSFile> sourceFiles) {
      this.packageName = packageName;
      this.hasBehaviors = hasBehaviors;
      this.sourceFiles = sourceFiles;
    }
  }

  private static final class BehaviorInfo {
    final ClassName className;
    final KSClassDeclaration declaration;
    final List<String> tags;
    final boolean createAsync;
    final boolean needProcessDirection;
    final boolean supportFragmentLayerRender;
    final String rendererHost;
    final boolean hasParamsConstructor;

    BehaviorInfo(ClassName className, KSClassDeclaration declaration, List<String> tags,
        boolean createAsync, boolean needProcessDirection, boolean supportFragmentLayerRender,
        String rendererHost, boolean hasParamsConstructor) {
      this.className = className;
      this.declaration = declaration;
      this.tags = tags;
      this.createAsync = createAsync;
      this.needProcessDirection = needProcessDirection;
      this.supportFragmentLayerRender = supportFragmentLayerRender;
      this.rendererHost = rendererHost;
      this.hasParamsConstructor = hasParamsConstructor;
    }
  }

  private static final class ShadowInfo {
    final ClassName className;
    final KSClassDeclaration declaration;

    ShadowInfo(ClassName className, KSClassDeclaration declaration) {
      this.className = className;
      this.declaration = declaration;
    }
  }
}
