// Copyright 2026 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

package com.lynx.processor.ksp;

import static javax.lang.model.element.Modifier.PROTECTED;
import static javax.lang.model.element.Modifier.PUBLIC;

import com.google.devtools.ksp.processing.CodeGenerator;
import com.google.devtools.ksp.processing.KSPLogger;
import com.google.devtools.ksp.processing.Resolver;
import com.google.devtools.ksp.symbol.KSAnnotated;
import com.google.devtools.ksp.symbol.KSAnnotation;
import com.google.devtools.ksp.symbol.KSClassDeclaration;
import com.google.devtools.ksp.symbol.KSDeclaration;
import com.google.devtools.ksp.symbol.KSFile;
import com.google.devtools.ksp.symbol.KSPropertyDeclaration;
import com.google.devtools.ksp.symbol.KSType;
import com.google.devtools.ksp.symbol.KSTypeArgument;
import com.google.devtools.ksp.symbol.KSTypeReference;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeSpec;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

final class JSPropertyGenerator {
  private static final String JS_PROPERTY = "com.lynx.jsbridge.jsi.LynxJSProperty";
  private static final String SERIALIZED_NAME = "com.google.gson.annotations.SerializedName";

  private final CodeGenerator codeGenerator;
  private final KSPLogger logger;

  JSPropertyGenerator(CodeGenerator codeGenerator, KSPLogger logger) {
    this.codeGenerator = codeGenerator;
    this.logger = logger;
  }

  void generate(Resolver resolver) {
    Map<String, KSClassDeclaration> classes = new LinkedHashMap<>();
    for (KSAnnotated symbol :
        KspUtils.toList(resolver.getSymbolsWithAnnotation(JS_PROPERTY, false))) {
      if (!(symbol instanceof KSPropertyDeclaration)) {
        logger.error("@LynxJSProperty must be a field", symbol);
        continue;
      }
      KSDeclaration parent = ((KSPropertyDeclaration) symbol).getParentDeclaration();
      if (parent instanceof KSClassDeclaration) {
        classes.put(KspUtils.qualifiedName(parent), (KSClassDeclaration) parent);
      }
    }
    for (KSClassDeclaration declaration : classes.values()) {
      try {
        SourceWriter.write(codeGenerator, javaFile(declaration), sourceFiles(declaration));
      } catch (IOException | RuntimeException error) {
        logger.error(
            error.getMessage() == null ? error.toString() : error.getMessage(), declaration);
      }
    }
  }

  private JavaFile javaFile(KSClassDeclaration declaration) {
    ClassName sourceClass = ClassName.bestGuess(KspUtils.qualifiedName(declaration));
    String descriptorName = sourceClass.reflectionName();
    descriptorName = descriptorName.substring(descriptorName.lastIndexOf('.') + 1) + "$$Descriptor";
    Map<String, FieldInfo> fields = collectFields(declaration);

    ClassName propertyDescriptor =
        ClassName.get("com.lynx.jsbridge.jsi", "LynxJSPropertyDescriptor");
    MethodSpec.Builder createFieldInfos =
        MethodSpec.methodBuilder("createFieldInfos")
            .addAnnotation(Override.class)
            .addModifiers(PROTECTED)
            .returns(ParameterizedTypeName.get(ClassName.get(ConcurrentHashMap.class),
                ClassName.get(String.class), propertyDescriptor))
            .addStatement("$T<String, $T> fieldInfos = new $T<>()", ConcurrentHashMap.class,
                propertyDescriptor, ConcurrentHashMap.class);
    for (Map.Entry<String, FieldInfo> entry : fields.entrySet()) {
      createFieldInfos.addStatement("fieldInfos.put($S, new $T($S, $S))", entry.getKey(),
          propertyDescriptor, entry.getValue().fieldName, entry.getValue().descriptor);
    }
    createFieldInfos.addStatement("return fieldInfos");

    TypeSpec type =
        TypeSpec.classBuilder(descriptorName)
            .addAnnotation(ClassName.get("androidx.annotation", "Keep"))
            .addModifiers(PUBLIC)
            .superclass(ClassName.get("com.lynx.jsbridge.jsi", "AbsLynxJSIObjectDescriptor"))
            .addMethod(MethodSpec.methodBuilder("getClassName")
                           .addAnnotation(Override.class)
                           .addModifiers(PUBLIC)
                           .returns(String.class)
                           .addStatement("return $S", sourceClass.reflectionName())
                           .build())
            .addMethod(createFieldInfos.build())
            .build();
    return JavaFile.builder(KspUtils.packageName(declaration), type)
        .addFileComment("Generated by com.lynx.jsbridge.jsi.LynxJSPropertyProcessor")
        .build();
  }

  private Map<String, FieldInfo> collectFields(KSClassDeclaration declaration) {
    Map<String, FieldInfo> fields = new LinkedHashMap<>();
    KSClassDeclaration current = declaration;
    while (current != null) {
      for (KSDeclaration child : KspUtils.toList(current.getDeclarations())) {
        if (!(child instanceof KSPropertyDeclaration)
            || KspUtils.annotation(child, JS_PROPERTY) == null) {
          continue;
        }
        KSPropertyDeclaration property = (KSPropertyDeclaration) child;
        String fieldName = property.getSimpleName().asString();
        KSAnnotation serializedName = KspUtils.annotation(property, SERIALIZED_NAME);
        String scriptName = KspUtils.stringArgument(serializedName, "value", fieldName);
        fields.put(scriptName, new FieldInfo(fieldName, descriptor(property.getType().resolve())));
      }
      current = superclass(current);
    }
    return fields;
  }

  private String descriptor(KSType type) {
    String qualifiedName = KspUtils.qualifiedName(type.getDeclaration());
    boolean nullable = "NULLABLE".equals(type.getNullability().name());
    switch (qualifiedName) {
      case "boolean":
        return "Z";
      case "kotlin.Boolean":
        return nullable ? "Ljava/lang/Boolean;" : "Z";
      case "int":
        return "I";
      case "kotlin.Int":
        return nullable ? "Ljava/lang/Integer;" : "I";
      case "long":
        return "J";
      case "kotlin.Long":
        return nullable ? "Ljava/lang/Long;" : "J";
      case "float":
        return "F";
      case "kotlin.Float":
        return nullable ? "Ljava/lang/Float;" : "F";
      case "double":
        return "D";
      case "kotlin.Double":
        return nullable ? "Ljava/lang/Double;" : "D";
      case "kotlin.String":
        return "Ljava/lang/String;";
      case "kotlin.collections.List":
      case "kotlin.collections.MutableList":
        return "Ljava/util/List;";
      case "kotlin.BooleanArray":
        return "[Z";
      case "kotlin.IntArray":
        return "[I";
      case "kotlin.LongArray":
        return "[J";
      case "kotlin.FloatArray":
        return "[F";
      case "kotlin.DoubleArray":
        return "[D";
      case "kotlin.Array":
        List<KSTypeArgument> arguments = type.getArguments();
        if (!arguments.isEmpty() && arguments.get(0).getType() != null) {
          return "[" + descriptor(arguments.get(0).getType().resolve());
        }
        return "[Ljava/lang/Object;";
      default:
        return "L" + binaryName(type.getDeclaration()).replace('.', '/') + ";";
    }
  }

  private static String binaryName(KSDeclaration declaration) {
    ClassName className = ClassName.bestGuess(KspUtils.qualifiedName(declaration));
    return className.reflectionName();
  }

  private static KSClassDeclaration superclass(KSClassDeclaration declaration) {
    for (KSTypeReference reference : KspUtils.toList(declaration.getSuperTypes())) {
      KSType type = reference.resolve();
      String typeName = KspUtils.qualifiedName(type.getDeclaration());
      if (type.getDeclaration() instanceof KSClassDeclaration
          && !"java.lang.Object".equals(typeName) && !"kotlin.Any".equals(typeName)) {
        return (KSClassDeclaration) type.getDeclaration();
      }
    }
    return null;
  }

  private static Set<KSFile> sourceFiles(KSClassDeclaration declaration) {
    Set<KSFile> files = new LinkedHashSet<>();
    KSClassDeclaration current = declaration;
    while (current != null) {
      if (current.getContainingFile() != null) {
        files.add(current.getContainingFile());
      }
      current = superclass(current);
    }
    return files;
  }

  private static final class FieldInfo {
    final String fieldName;
    final String descriptor;

    FieldInfo(String fieldName, String descriptor) {
      this.fieldName = fieldName;
      this.descriptor = descriptor;
    }
  }
}
