// Copyright 2026 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

package com.lynx.processor.ksp;

import static javax.lang.model.element.Modifier.PUBLIC;

import com.google.devtools.ksp.processing.CodeGenerator;
import com.google.devtools.ksp.processing.KSPLogger;
import com.google.devtools.ksp.processing.Resolver;
import com.google.devtools.ksp.symbol.KSAnnotated;
import com.google.devtools.ksp.symbol.KSAnnotation;
import com.google.devtools.ksp.symbol.KSClassDeclaration;
import com.google.devtools.ksp.symbol.KSFile;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeSpec;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

final class LibraryGenerator {
  static final String OPTION_LIBRARY_PACKAGE_NAME = "lynx.library.packageName";
  private static final String LYNX_NATIVE_MODULE = "com.lynx.jsbridge.LynxNativeModule";
  private static final String LYNX_SERVICE = "com.lynx.tasm.service.LynxService";

  private final CodeGenerator codeGenerator;
  private final KSPLogger logger;
  private final Map<String, String> options;

  LibraryGenerator(CodeGenerator codeGenerator, KSPLogger logger, Map<String, String> options) {
    this.codeGenerator = codeGenerator;
    this.logger = logger;
    this.options = options;
  }

  void generate(Resolver resolver, BehaviorGenerator.Result behavior) {
    String packageName = options.get(OPTION_LIBRARY_PACKAGE_NAME);
    if (packageName == null || packageName.trim().isEmpty()) {
      return;
    }
    packageName = packageName.trim();

    List<ModuleInfo> modules = new ArrayList<>();
    List<ClassName> services = new ArrayList<>();
    Set<KSFile> sourceFiles = new LinkedHashSet<>(behavior.sourceFiles);
    collectModules(resolver, modules, sourceFiles);
    collectServices(resolver, services, sourceFiles);
    if (!behavior.hasBehaviors && modules.isEmpty() && services.isEmpty()) {
      return;
    }

    MethodSpec.Builder register =
        MethodSpec.methodBuilder("register")
            .addAnnotation(Override.class)
            .addModifiers(PUBLIC)
            .addParameter(
                ClassName.get("com.lynx.tasm.library", "LynxLibraryRegistry"), "registry");
    if (behavior.hasBehaviors) {
      register.addStatement("registry.addBehaviors($T.getBehaviors())",
          ClassName.get(behavior.packageName, "BehaviorGenerator"));
    }
    for (ModuleInfo module : modules) {
      register.addStatement("registry.registerModule($S, $T.class)", module.name, module.className);
    }
    for (ClassName service : services) {
      register.addStatement("registry.registerService($T.class)", service);
    }

    TypeSpec provider =
        TypeSpec.classBuilder("LynxLibraryProviderImpl")
            .addAnnotation(ClassName.get("androidx.annotation", "Keep"))
            .addModifiers(PUBLIC)
            .addSuperinterface(ClassName.get("com.lynx.tasm.library", "LynxLibraryProvider"))
            .addMethod(register.build())
            .build();
    try {
      SourceWriter.write(codeGenerator,
          JavaFile.builder(packageName, provider)
              .addFileComment("Generated by com.lynx.processor.LynxLibraryProcessor")
              .build(),
          sourceFiles);
    } catch (IOException | RuntimeException error) {
      logger.error(error.getMessage() == null ? error.toString() : error.getMessage(), null);
    }
  }

  private void collectModules(
      Resolver resolver, List<ModuleInfo> modules, Set<KSFile> sourceFiles) {
    for (KSAnnotated symbol :
        KspUtils.toList(resolver.getSymbolsWithAnnotation(LYNX_NATIVE_MODULE, false))) {
      KSClassDeclaration declaration = KspUtils.asClass(symbol);
      if (declaration == null) {
        continue;
      }
      KSAnnotation annotation = KspUtils.annotation(declaration, LYNX_NATIVE_MODULE);
      modules.add(new ModuleInfo(KspUtils.stringArgument(annotation, "name", ""),
          ClassName.bestGuess(KspUtils.qualifiedName(declaration))));
      addSourceFile(sourceFiles, declaration);
    }
  }

  private void collectServices(
      Resolver resolver, List<ClassName> services, Set<KSFile> sourceFiles) {
    for (KSAnnotated symbol :
        KspUtils.toList(resolver.getSymbolsWithAnnotation(LYNX_SERVICE, false))) {
      KSClassDeclaration declaration = KspUtils.asClass(symbol);
      if (declaration == null) {
        continue;
      }
      services.add(ClassName.bestGuess(KspUtils.qualifiedName(declaration)));
      addSourceFile(sourceFiles, declaration);
    }
  }

  private static void addSourceFile(Set<KSFile> files, KSClassDeclaration declaration) {
    if (declaration.getContainingFile() != null) {
      files.add(declaration.getContainingFile());
    }
  }

  private static final class ModuleInfo {
    final String name;
    final ClassName className;

    ModuleInfo(String name, ClassName className) {
      this.name = name;
      this.className = className;
    }
  }
}
