// Copyright 2026 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

package com.lynx.processor.ksp;

import static javax.lang.model.element.Modifier.PUBLIC;

import com.google.devtools.ksp.processing.CodeGenerator;
import com.google.devtools.ksp.processing.KSPLogger;
import com.google.devtools.ksp.processing.Resolver;
import com.google.devtools.ksp.symbol.KSAnnotated;
import com.google.devtools.ksp.symbol.KSAnnotation;
import com.google.devtools.ksp.symbol.KSClassDeclaration;
import com.google.devtools.ksp.symbol.KSDeclaration;
import com.google.devtools.ksp.symbol.KSFile;
import com.google.devtools.ksp.symbol.KSFunctionDeclaration;
import com.google.devtools.ksp.symbol.KSType;
import com.google.devtools.ksp.symbol.KSTypeReference;
import com.google.devtools.ksp.symbol.KSValueParameter;
import com.google.devtools.ksp.symbol.Modifier;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.CodeBlock;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeSpec;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

final class PropsGenerator {
  private static final String HOLDER = "com.lynx.tasm.behavior.LynxPropsHolder";
  private static final String PROP = "com.lynx.tasm.behavior.LynxProp";
  private static final String PROP_GROUP = "com.lynx.tasm.behavior.LynxPropGroup";
  private static final String LYNX_UI = "com.lynx.tasm.behavior.ui.LynxBaseUI";
  private static final String SHADOW_NODE = "com.lynx.tasm.behavior.shadow.ShadowNode";

  private final CodeGenerator codeGenerator;
  private final KSPLogger logger;

  PropsGenerator(CodeGenerator codeGenerator, KSPLogger logger) {
    this.codeGenerator = codeGenerator;
    this.logger = logger;
  }

  void generate(Resolver resolver) {
    for (KSAnnotated symbol : KspUtils.toList(resolver.getSymbolsWithAnnotation(HOLDER, false))) {
      KSClassDeclaration declaration = KspUtils.asClass(symbol);
      if (declaration == null) {
        continue;
      }
      try {
        List<PropertyInfo> properties = properties(declaration);
        Collections.sort(properties, Comparator.comparing(info -> info.name));
        SourceWriter.write(
            codeGenerator, javaFile(declaration, properties), sourceFiles(declaration));
      } catch (IOException | RuntimeException error) {
        logger.error(error.getMessage() == null ? error.toString() : error.getMessage(), symbol);
      }
    }
  }

  private JavaFile javaFile(KSClassDeclaration declaration, List<PropertyInfo> properties) {
    String packageName = KspUtils.packageName(declaration);
    ClassName target = ClassName.bestGuess(KspUtils.qualifiedName(declaration));
    SettableType settableType = settableType(declaration);
    ClassName parent = superclassName(declaration);
    String generatedName = generatedClassName(declaration, packageName) + "$$PropsSetter";
    TypeSpec.Builder type =
        TypeSpec.classBuilder(generatedName)
            .addModifiers(PUBLIC)
            .addMethod(setPropertyMethod(target, settableType, properties, isRoot(declaration)));
    if (isRoot(declaration)) {
      ClassName setter = settableType == SettableType.LYNX_UI
          ? ClassName.get("com.lynx.tasm.behavior.utils", "LynxUISetter")
          : ClassName.get("com.lynx.tasm.behavior.utils", "ShadowNodeSetter");
      type.addSuperinterface(ParameterizedTypeName.get(setter, target));
    } else {
      type.superclass(ClassName.get(parent.packageName(), parent.simpleName() + "$$PropsSetter"));
    }
    return JavaFile.builder(packageName, type.build())
        .addFileComment("Generated by com.lynx.processor.LynxPropsProcessor")
        .build();
  }

  private MethodSpec setPropertyMethod(
      ClassName target, SettableType settableType, List<PropertyInfo> properties, boolean root) {
    ClassName managerType = settableType == SettableType.LYNX_UI ? ClassName.bestGuess(LYNX_UI)
                                                                 : ClassName.bestGuess(SHADOW_NODE);
    CodeBlock.Builder code = CodeBlock.builder();
    if (!properties.isEmpty()) {
      code.addStatement("$T manager2 = ($T) manager", target, target)
          .add("switch (name) {\n")
          .indent();
      for (PropertyInfo property : properties) {
        code.add("case $S:\n", property.name).indent().add("manager2.$L(", property.methodName);
        if (property.groupIndex >= 0) {
          code.add("$L, ", property.groupIndex);
        }
        addExtractor(code, property);
        code.addStatement(")").addStatement("return").unindent();
      }
      code.unindent().add("}\n");
    }
    if (!root || properties.isEmpty()) {
      code.addStatement("super.setProperty(manager, name, props)");
    }
    return MethodSpec.methodBuilder("setProperty")
        .addAnnotation(Override.class)
        .addModifiers(PUBLIC)
        .addParameter(managerType, "manager")
        .addParameter(String.class, "name")
        .addParameter(ClassName.get("com.lynx.tasm.behavior", "StylesDiffMap"), "props")
        .addCode(code.build())
        .build();
  }

  private void addExtractor(CodeBlock.Builder code, PropertyInfo property) {
    if (property.boxedPrimitive) {
      code.add("props.isNull(name) ? null : ");
    }
    switch (property.type) {
      case "java.lang.String":
      case "kotlin.String":
        code.add("props.getString(name)");
        return;
      case "com.lynx.react.bridge.ReadableArray":
        code.add("props.getArray(name)");
        return;
      case "com.lynx.react.bridge.ReadableMap":
        code.add("props.getMap(name)");
        return;
      case "com.lynx.react.bridge.Dynamic":
        code.add("props.getDynamic(name)");
        return;
      case "boolean":
      case "java.lang.Boolean":
      case "kotlin.Boolean":
        code.add("props.getBoolean(name, $L)", property.defaultBoolean);
        return;
      case "double":
      case "java.lang.Double":
      case "kotlin.Double":
        if (Double.isNaN(property.defaultDouble)) {
          code.add("props.getDouble(name, $T.NaN)", Double.class);
        } else {
          code.add("props.getDouble(name, $Lf)", property.defaultDouble);
        }
        return;
      case "float":
      case "java.lang.Float":
      case "kotlin.Float":
        if (Float.isNaN(property.defaultFloat)) {
          code.add("props.getFloat(name, $T.NaN)", Float.class);
        } else {
          code.add("props.getFloat(name, $Lf)", property.defaultFloat);
        }
        return;
      case "int":
      case "java.lang.Integer":
      case "kotlin.Int":
        code.add("props.getInt(name, $L)", property.defaultInt);
        return;
      case "long":
      case "java.lang.Long":
      case "kotlin.Long":
        code.add("props.getLong(name, 0L)");
        return;
      default:
        throw new IllegalArgumentException("Unsupported @LynxProp type: " + property.type);
    }
  }

  private List<PropertyInfo> properties(KSClassDeclaration declaration) {
    List<PropertyInfo> result = new ArrayList<>();
    Set<String> names = new LinkedHashSet<>();
    for (KSDeclaration child : KspUtils.toList(declaration.getDeclarations())) {
      if (!(child instanceof KSFunctionDeclaration)) {
        continue;
      }
      KSFunctionDeclaration method = (KSFunctionDeclaration) child;
      KSAnnotation prop = KspUtils.annotation(method, PROP);
      KSAnnotation group = KspUtils.annotation(method, PROP_GROUP);
      if (prop == null && group == null) {
        continue;
      }
      if (!method.getModifiers().contains(Modifier.PUBLIC)) {
        throw new IllegalArgumentException(
            "@LynxProp and @LynxPropGroup must be on a public method");
      }
      if (prop != null) {
        addProperty(result, names, method, prop, KspUtils.stringArgument(prop, "name", ""), -1);
      } else {
        List<String> groupNames = KspUtils.stringListArgument(group, "names");
        for (int i = 0; i < groupNames.size(); i++) {
          addProperty(result, names, method, group, groupNames.get(i), i);
        }
      }
    }
    return result;
  }

  private void addProperty(List<PropertyInfo> result, Set<String> names,
      KSFunctionDeclaration method, KSAnnotation annotation, String name, int groupIndex) {
    if (!names.add(name)) {
      return;
    }
    int valueIndex = groupIndex >= 0 ? 1 : 0;
    int expectedParameters = groupIndex >= 0 ? 2 : 1;
    if (method.getParameters().size() != expectedParameters) {
      throw new IllegalArgumentException("Wrong number of args for " + method.getSimpleName());
    }
    if (groupIndex >= 0 && !isInt(typeName(method.getParameters().get(0)))) {
      throw new IllegalArgumentException("First @LynxPropGroup argument must be an int");
    }
    String type = typeName(method.getParameters().get(valueIndex));
    if (!isSupported(type)) {
      throw new IllegalArgumentException("Unsupported @LynxProp type: " + type);
    }
    result.add(new PropertyInfo(name, method.getSimpleName().asString(), type, groupIndex,
        KspUtils.doubleArgument(annotation, "defaultDouble", 0.0),
        KspUtils.floatArgument(annotation, "defaultFloat", 0.0f),
        KspUtils.intArgument(annotation, "defaultInt", 0),
        KspUtils.booleanArgument(annotation, "defaultBoolean", false), isBoxedPrimitive(type)));
  }

  private SettableType settableType(KSClassDeclaration declaration) {
    KSClassDeclaration current = declaration;
    while (current != null) {
      String name = KspUtils.qualifiedName(current);
      if (LYNX_UI.equals(name)) {
        return SettableType.LYNX_UI;
      }
      if (SHADOW_NODE.equals(name)) {
        return SettableType.SHADOW_NODE;
      }
      current = superclass(current);
    }
    throw new IllegalArgumentException("Could not find Lynx prop target type");
  }

  private boolean isRoot(KSClassDeclaration declaration) {
    KSClassDeclaration parent = superclass(declaration);
    if (parent == null) {
      return true;
    }
    String parentName = KspUtils.qualifiedName(parent);
    return LYNX_UI.equals(parentName) || SHADOW_NODE.equals(parentName);
  }

  private static ClassName superclassName(KSClassDeclaration declaration) {
    KSClassDeclaration parent = superclass(declaration);
    if (parent == null) {
      throw new IllegalArgumentException("Missing superclass");
    }
    return ClassName.bestGuess(KspUtils.qualifiedName(parent));
  }

  private static KSClassDeclaration superclass(KSClassDeclaration declaration) {
    for (KSTypeReference reference : KspUtils.toList(declaration.getSuperTypes())) {
      KSType type = reference.resolve();
      if (type.getDeclaration() instanceof KSClassDeclaration
          && !"java.lang.Object".equals(KspUtils.qualifiedName(type.getDeclaration()))
          && !"kotlin.Any".equals(KspUtils.qualifiedName(type.getDeclaration()))) {
        return (KSClassDeclaration) type.getDeclaration();
      }
    }
    return null;
  }

  private static String typeName(KSValueParameter parameter) {
    KSType type = parameter.getType().resolve();
    String name = KspUtils.qualifiedName(type.getDeclaration());
    if (!type.getNullability().name().equals("NULLABLE")) {
      return primitiveName(name);
    }
    return boxedName(name);
  }

  private static String primitiveName(String name) {
    switch (name) {
      case "kotlin.Boolean":
        return "boolean";
      case "kotlin.Double":
        return "double";
      case "kotlin.Float":
        return "float";
      case "kotlin.Int":
        return "int";
      case "kotlin.Long":
        return "long";
      default:
        return name;
    }
  }

  private static String boxedName(String name) {
    switch (name) {
      case "kotlin.Boolean":
        return "java.lang.Boolean";
      case "kotlin.Double":
        return "java.lang.Double";
      case "kotlin.Float":
        return "java.lang.Float";
      case "kotlin.Int":
        return "java.lang.Integer";
      case "kotlin.Long":
        return "java.lang.Long";
      default:
        return name;
    }
  }

  private static boolean isInt(String type) {
    return "int".equals(type) || "java.lang.Integer".equals(type) || "kotlin.Int".equals(type);
  }

  private static boolean isSupported(String type) {
    return "boolean".equals(type) || "double".equals(type) || "float".equals(type)
        || "int".equals(type) || "long".equals(type) || "java.lang.Boolean".equals(type)
        || "java.lang.Double".equals(type) || "java.lang.Float".equals(type)
        || "java.lang.Integer".equals(type) || "java.lang.Long".equals(type)
        || "java.lang.String".equals(type) || "kotlin.String".equals(type)
        || "com.lynx.react.bridge.ReadableArray".equals(type)
        || "com.lynx.react.bridge.ReadableMap".equals(type)
        || "com.lynx.react.bridge.Dynamic".equals(type);
  }

  private static boolean isBoxedPrimitive(String type) {
    return type.startsWith("java.lang.") && !"java.lang.String".equals(type);
  }

  private static String generatedClassName(KSClassDeclaration declaration, String packageName) {
    return KspUtils.qualifiedName(declaration)
        .substring(packageName.length() + 1)
        .replace('.', '$');
  }

  private static Set<KSFile> sourceFiles(KSClassDeclaration declaration) {
    Set<KSFile> files = new LinkedHashSet<>();
    if (declaration.getContainingFile() != null) {
      files.add(declaration.getContainingFile());
    }
    return files;
  }

  private enum SettableType { LYNX_UI, SHADOW_NODE }

  private static final class PropertyInfo {
    final String name;
    final String methodName;
    final String type;
    final int groupIndex;
    final double defaultDouble;
    final float defaultFloat;
    final int defaultInt;
    final boolean defaultBoolean;
    final boolean boxedPrimitive;

    PropertyInfo(String name, String methodName, String type, int groupIndex, double defaultDouble,
        float defaultFloat, int defaultInt, boolean defaultBoolean, boolean boxedPrimitive) {
      this.name = name;
      this.methodName = methodName;
      this.type = type;
      this.groupIndex = groupIndex;
      this.defaultDouble = defaultDouble;
      this.defaultFloat = defaultFloat;
      this.defaultInt = defaultInt;
      this.defaultBoolean = defaultBoolean;
      this.boxedPrimitive = boxedPrimitive;
    }
  }
}
