// Copyright 2026 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

package com.lynx.processor.ksp;

import static javax.lang.model.element.Modifier.PUBLIC;

import com.google.devtools.ksp.processing.CodeGenerator;
import com.google.devtools.ksp.processing.KSPLogger;
import com.google.devtools.ksp.processing.Resolver;
import com.google.devtools.ksp.symbol.KSAnnotated;
import com.google.devtools.ksp.symbol.KSClassDeclaration;
import com.google.devtools.ksp.symbol.KSDeclaration;
import com.google.devtools.ksp.symbol.KSFile;
import com.google.devtools.ksp.symbol.KSFunctionDeclaration;
import com.google.devtools.ksp.symbol.KSType;
import com.google.devtools.ksp.symbol.KSTypeReference;
import com.google.devtools.ksp.symbol.KSValueParameter;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.CodeBlock;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeSpec;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

final class UIMethodsGenerator {
  private static final String HOLDER = "com.lynx.tasm.behavior.LynxUIMethodsHolder";
  private static final String UI_METHOD = "com.lynx.tasm.behavior.LynxUIMethod";
  private static final String READABLE_MAP = "com.lynx.react.bridge.ReadableMap";
  private static final String CALLBACK = "com.lynx.react.bridge.Callback";

  private final CodeGenerator codeGenerator;
  private final KSPLogger logger;

  UIMethodsGenerator(CodeGenerator codeGenerator, KSPLogger logger) {
    this.codeGenerator = codeGenerator;
    this.logger = logger;
  }

  void generate(Resolver resolver) {
    for (KSAnnotated symbol : KspUtils.toList(resolver.getSymbolsWithAnnotation(HOLDER, false))) {
      KSClassDeclaration declaration = KspUtils.asClass(symbol);
      if (declaration == null) {
        continue;
      }
      List<KSFunctionDeclaration> methods = collectMethods(declaration);
      if (methods.isEmpty()) {
        continue;
      }
      try {
        SourceWriter.write(
            codeGenerator, javaFile(declaration, methods), sourceFiles(declaration, methods));
      } catch (IOException | RuntimeException error) {
        logger.error(error.getMessage() == null ? error.toString() : error.getMessage(), symbol);
      }
    }
  }

  private JavaFile javaFile(KSClassDeclaration declaration, List<KSFunctionDeclaration> methods) {
    ClassName target = ClassName.bestGuess(KspUtils.qualifiedName(declaration));
    String packageName = KspUtils.packageName(declaration);
    String generatedName = generatedClassName(declaration, packageName) + "$$MethodInvoker";
    TypeSpec type =
        TypeSpec.classBuilder(generatedName)
            .addAnnotation(ClassName.get("androidx.annotation", "Keep"))
            .addModifiers(PUBLIC)
            .addSuperinterface(ParameterizedTypeName.get(
                ClassName.get("com.lynx.tasm.behavior.utils", "LynxUIMethodInvoker"), target))
            .addMethod(invokeMethod(target, methods))
            .build();
    return JavaFile.builder(packageName, type)
        .addFileComment("Generated by com.lynx.processor.LynxUIMethodsProcessor")
        .addStaticImport(
            ClassName.get("com.lynx.tasm.behavior", "LynxUIMethodConstants"), "METHOD_NOT_FOUND")
        .build();
  }

  private MethodSpec invokeMethod(ClassName target, List<KSFunctionDeclaration> methods) {
    CodeBlock.Builder code = CodeBlock.builder().add("switch (methodName) {\n").indent();
    for (KSFunctionDeclaration method : methods) {
      String name = method.getSimpleName().asString();
      code.add("case $S:\n", name).indent().add("ui.$L(", name);
      List<String> arguments = new ArrayList<>();
      for (KSValueParameter parameter : method.getParameters()) {
        String type = typeName(parameter.getType());
        if (READABLE_MAP.equals(type)) {
          arguments.add("params");
        } else if (CALLBACK.equals(type)) {
          arguments.add("callback");
        }
      }
      if (method.getParameters().size() > 2 || arguments.size() != method.getParameters().size()) {
        throw new IllegalArgumentException("Parameters of method annotated with @LynxUIMethod "
            + "must be ReadableMap and/or Callback: " + name);
      }
      code.add(String.join(", ", arguments)).addStatement(")").addStatement("break").unindent();
    }
    code.add("default:\n")
        .indent()
        .addStatement("callback.invoke(METHOD_NOT_FOUND)")
        .addStatement("break")
        .unindent()
        .unindent()
        .add("}\n");
    return MethodSpec.methodBuilder("invoke")
        .addAnnotation(Override.class)
        .addModifiers(PUBLIC)
        .addParameter(target, "ui")
        .addParameter(String.class, "methodName")
        .addParameter(ClassName.bestGuess(READABLE_MAP), "params")
        .addParameter(ClassName.bestGuess(CALLBACK), "callback")
        .addCode(code.build())
        .build();
  }

  private List<KSFunctionDeclaration> collectMethods(KSClassDeclaration declaration) {
    List<KSFunctionDeclaration> result = new ArrayList<>();
    Set<String> names = new HashSet<>();
    KSClassDeclaration current = declaration;
    while (current != null) {
      for (KSDeclaration child : KspUtils.toList(current.getDeclarations())) {
        if (child instanceof KSFunctionDeclaration && KspUtils.annotation(child, UI_METHOD) != null
            && names.add(child.getSimpleName().asString())) {
          result.add((KSFunctionDeclaration) child);
        }
      }
      current = superclass(current);
    }
    return result;
  }

  private static KSClassDeclaration superclass(KSClassDeclaration declaration) {
    for (KSTypeReference reference : KspUtils.toList(declaration.getSuperTypes())) {
      KSType type = reference.resolve();
      if (type.getDeclaration() instanceof KSClassDeclaration
          && !"java.lang.Object".equals(KspUtils.qualifiedName(type.getDeclaration()))
          && !"kotlin.Any".equals(KspUtils.qualifiedName(type.getDeclaration()))) {
        return (KSClassDeclaration) type.getDeclaration();
      }
    }
    return null;
  }

  private static String typeName(KSTypeReference reference) {
    return KspUtils.qualifiedName(reference.resolve().getDeclaration());
  }

  private static String generatedClassName(KSClassDeclaration declaration, String packageName) {
    String qualifiedName = KspUtils.qualifiedName(declaration);
    return qualifiedName.substring(packageName.length() + 1).replace('.', '$');
  }

  private static Set<KSFile> sourceFiles(
      KSClassDeclaration declaration, List<KSFunctionDeclaration> methods) {
    Set<KSFile> files = new LinkedHashSet<>();
    if (declaration.getContainingFile() != null) {
      files.add(declaration.getContainingFile());
    }
    for (KSFunctionDeclaration method : methods) {
      if (method.getContainingFile() != null) {
        files.add(method.getContainingFile());
      }
    }
    return files;
  }
}
