# Copyright 2022 The Lynx Authors. All rights reserved.

import("../Android.gni")

declare_args() {
  enable_memory_tracing = false

  # Enable JNI helpers for Android instrumentation tests.
  enable_lynx_android_test = false

  # enable lynx testing with googletest
  enable_lynx_testing = false
}

enable_radon = true
