# Copyright 2026 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.

import("../../../testing/test.gni")
import("../devtool.gni")

devtool_source_set("input_types") {
  sources = [ "input_event_target.h" ]
  public_deps = [ "../base" ]
}

devtool_source_set("input") {
  sources = [
    "synthetic_gesture.h",
    "synthetic_gesture_controller.cc",
    "synthetic_gesture_controller.h",
    "synthetic_tap_gesture.cc",
    "synthetic_tap_gesture.h",
  ]

  public_deps = [ ":input_types" ]
}

unittest_set("input_testset") {
  sources = [ "synthetic_gesture_unittest.cc" ]
  public_deps = [ ":input" ]
}

unittest_exec("input_unittests_exec") {
  sources = []
  deps = [
    ":input_testset",
    "../../../core/base:base",
    "../../../core/renderer/utils:lynx_env",
  ]
}
