/*
 * This file is auto-generated by lynx/tools/css_generator/generate_types.py
 * Do not edit this file directly.
 */

export interface Properties {
% for name, type in properties.items():
  ${name}?: ${type};
% endfor
}