/*
 * This file is auto-generated by lynx/tools/css_generator/generate_types.py
 * Do not edit this file directly.
 */

export interface Properties {
% for name, data in properties.items():
%if data.get('desc'):
  /**
   * ${data.get('desc')}
   *
%if data.get('syntax'):
   * **Syntax**: `${data.get('syntax')}`
   *
%endif
   * @see https://lynxjs.org/api/css/properties/${data.get('name')}
   */
%endif
  ${name}?: ${data.get('type')};
% endfor
}