/*
 * This file is auto-generated by lynx/tools/css_generator/generate_types.py
 * Do not edit this file directly.
 */

export interface Properties {
  /**
   * The `top` CSS property participates in specifying the vertical position.
   *
   * **Syntax**: `<length-percentage> | auto`
   *
   * @see https://lynxjs.org/api/css/properties/top
   */
  top?: 'auto' | (string & {}) | 0 | undefined;
  borderTopColor?: (string & {}) | number | undefined;
  backgroundOrigin?: (string & {}) | number | undefined;
  backgroundRepeat?: (string & {}) | number | undefined;
  backgroundSize?: (string & {}) | number | undefined;
  border?: (string & {}) | number | undefined;
  visibility?: (string & {}) | number | undefined;
  borderRight?: (string & {}) | number | undefined;
  borderLeft?: (string & {}) | number | undefined;
  borderTop?: (string & {}) | number | undefined;
  borderBottom?: (string & {}) | number | undefined;
  transition?: (string & {}) | number | undefined;
  borderBottomColor?: (string & {}) | number | undefined;
  transitionProperty?: (string & {}) | number | undefined;
  transitionDuration?: (string & {}) | number | undefined;
  transitionDelay?: (string & {}) | number | undefined;
  transitionTimingFunction?: (string & {}) | number | undefined;
  content?: (string & {}) | number | undefined;
  borderLeftStyle?: (string & {}) | number | undefined;
  borderRightStyle?: (string & {}) | number | undefined;
  borderTopStyle?: (string & {}) | number | undefined;
  borderBottomStyle?: (string & {}) | number | undefined;
  implicitAnimation?: (string & {}) | number | undefined;
  borderRadius?: (string & {}) | number | undefined;
  /**
   * The `overflow-x` property specifies whether to clip the content when it overflows at the left and right edges.
   *
   * **Syntax**: `<overflow-block>`
   *
   * @see https://lynxjs.org/api/css/properties/overflow-x
   */
  overflowX?: 'hidden' | 'visible' | undefined;
  /**
   * The `overflow-y` property specifies whether to clip the content when it overflows at the top and bottom edges.
   *
   * **Syntax**: `<overflow-block>`
   *
   * @see https://lynxjs.org/api/css/properties/overflow-y
   */
  overflowY?: 'hidden' | 'visible' | undefined;
  wordBreak?: (string & {}) | number | undefined;
  backgroundClip?: (string & {}) | number | undefined;
  outline?: (string & {}) | number | undefined;
  outlineColor?: (string & {}) | number | undefined;
  outlineStyle?: (string & {}) | number | undefined;
  outlineWidth?: (string & {}) | number | undefined;
  verticalAlign?: (string & {}) | number | undefined;
  /**
   * auto
   *
   * @see https://lynxjs.org/api/css/properties/caret-color
   */
  caretColor?: (string & {}) | number | undefined;
  borderTopLeftRadius?: (string & {}) | number | undefined;
  /**
   * lynx layout direction
   *
   * @see https://lynxjs.org/api/css/properties/direction
   */
  direction?: (string & {}) | number | undefined;
  relativeId?: (string & {}) | number | undefined;
  relativeAlignTop?: (string & {}) | number | undefined;
  relativeAlignRight?: (string & {}) | number | undefined;
  relativeAlignBottom?: (string & {}) | number | undefined;
  relativeAlignLeft?: (string & {}) | number | undefined;
  relativeTopOf?: (string & {}) | number | undefined;
  relativeRightOf?: (string & {}) | number | undefined;
  relativeBottomOf?: (string & {}) | number | undefined;
  relativeLeftOf?: (string & {}) | number | undefined;
  borderBottomLeftRadius?: (string & {}) | number | undefined;
  relativeLayoutOnce?: (string & {}) | number | undefined;
  /**
   * TBD
   *
   * @see https://lynxjs.org/api/css/properties/relative-center
   */
  relativeCenter?: (string & {}) | number | undefined;
  /**
   * enter transition name
   *
   * @see https://lynxjs.org/api/css/properties/enter-transition-name
   */
  enterTransitionName?: (string & {}) | number | undefined;
  /**
   * enter transition name
   *
   * @see https://lynxjs.org/api/css/properties/exit-transition-name
   */
  exitTransitionName?: (string & {}) | number | undefined;
  /**
   * enter transition name
   *
   * @see https://lynxjs.org/api/css/properties/pause-transition-name
   */
  pauseTransitionName?: (string & {}) | number | undefined;
  /**
   * enter transition name
   *
   * @see https://lynxjs.org/api/css/properties/resume-transition-name
   */
  resumeTransitionName?: (string & {}) | number | undefined;
  /**
   * flex and wrap
   *
   * @see https://lynxjs.org/api/css/properties/flex-flow
   */
  flexFlow?: (string & {}) | number | undefined;
  zIndex?: (string & {}) | number | undefined;
  textDecorationColor?: (string & {}) | number | undefined;
  /**
   * default linear layout gravity for children
   *
   * @see https://lynxjs.org/api/css/properties/linear-cross-gravity
   */
  linearCrossGravity?: (string & {}) | number | undefined;
  borderTopRightRadius?: (string & {}) | number | undefined;
  marginInlineStart?: (string & {}) | number | undefined;
  marginInlineEnd?: (string & {}) | number | undefined;
  paddingInlineStart?: (string & {}) | number | undefined;
  paddingInlineEnd?: (string & {}) | number | undefined;
  borderInlineStartColor?: (string & {}) | number | undefined;
  borderInlineEndColor?: (string & {}) | number | undefined;
  borderInlineStartWidth?: (string & {}) | number | undefined;
  borderInlineEndWidth?: (string & {}) | number | undefined;
  borderInlineStartStyle?: (string & {}) | number | undefined;
  borderInlineEndStyle?: (string & {}) | number | undefined;
  borderBottomRightRadius?: (string & {}) | number | undefined;
  borderStartStartRadius?: (string & {}) | number | undefined;
  borderEndStartRadius?: (string & {}) | number | undefined;
  borderStartEndRadius?: (string & {}) | number | undefined;
  borderEndEndRadius?: (string & {}) | number | undefined;
  relativeAlignInlineStart?: (string & {}) | number | undefined;
  relativeAlignInlineEnd?: (string & {}) | number | undefined;
  relativeInlineStartOf?: (string & {}) | number | undefined;
  relativeInlineEndOf?: (string & {}) | number | undefined;
  insetInlineStart?: (string & {}) | number | undefined;
  insetInlineEnd?: (string & {}) | number | undefined;
  borderWidth?: (string & {}) | number | undefined;
  maskImage?: (string & {}) | number | undefined;
  gridTemplateColumns?: (string & {}) | number | undefined;
  gridTemplateRows?: (string & {}) | number | undefined;
  gridAutoColumns?: (string & {}) | number | undefined;
  gridAutoRows?: (string & {}) | number | undefined;
  gridColumnSpan?: (string & {}) | number | undefined;
  gridRowSpan?: (string & {}) | number | undefined;
  gridColumnStart?: (string & {}) | number | undefined;
  gridColumnEnd?: (string & {}) | number | undefined;
  gridRowStart?: (string & {}) | number | undefined;
  borderLeftWidth?: (string & {}) | number | undefined;
  gridRowEnd?: (string & {}) | number | undefined;
  gridColumnGap?: (string & {}) | number | undefined;
  gridRowGap?: (string & {}) | number | undefined;
  justifyItems?: (string & {}) | number | undefined;
  justifySelf?: (string & {}) | number | undefined;
  gridAutoFlow?: (string & {}) | number | undefined;
  /**
   * The filter CSS property applies graphical effects like blur or color shift to an element. Filters are commonly used to adjust the rendering of images, backgrounds, and borders.
   *
   * @see https://lynxjs.org/api/css/properties/filter
   */
  filter?: (string & {}) | number | undefined;
  listMainAxisGap?: (string & {}) | number | undefined;
  listCrossAxisGap?: (string & {}) | number | undefined;
  linearDirection?: (string & {}) | number | undefined;
  borderRightWidth?: (string & {}) | number | undefined;
  perspective?: (string & {}) | number | undefined;
  cursor?: (string & {}) | number | undefined;
  textIndent?: (string & {}) | number | undefined;
  clipPath?: (string & {}) | number | undefined;
  textStroke?: (string & {}) | number | undefined;
  textStrokeWidth?: (string & {}) | number | undefined;
  textStrokeColor?: (string & {}) | number | undefined;
  XAutoFontSize?: (string & {}) | number | undefined;
  XAutoFontSizePresetSizes?: (string & {}) | number | undefined;
  mask?: (string & {}) | number | undefined;
  /**
   * The `left` CSS property participates in specifying the horizontal position of a positioned element.
   *
   * **Syntax**: `<length-percentage> | auto`
   *
   * @see https://lynxjs.org/api/css/properties/left
   */
  left?: 'auto' | (string & {}) | 0 | undefined;
  borderTopWidth?: (string & {}) | number | undefined;
  maskRepeat?: (string & {}) | number | undefined;
  maskPosition?: (string & {}) | number | undefined;
  maskClip?: (string & {}) | number | undefined;
  maskOrigin?: (string & {}) | number | undefined;
  maskSize?: (string & {}) | number | undefined;
  gap?: (string & {}) | number | undefined;
  columnGap?: (string & {}) | number | undefined;
  rowGap?: (string & {}) | number | undefined;
  imageRendering?: (string & {}) | number | undefined;
  hyphens?: (string & {}) | number | undefined;
  borderBottomWidth?: (string & {}) | number | undefined;
  XAppRegion?: (string & {}) | number | undefined;
  XAnimationColorInterpolation?: (string & {}) | number | undefined;
  XHandleSize?: (string & {}) | number | undefined;
  XHandleColor?: (string & {}) | number | undefined;
  offsetDistance?: (string & {}) | number | undefined;
  offsetPath?: (string & {}) | number | undefined;
  offsetRotate?: (string & {}) | number | undefined;
  fontVariationSettings?: (string & {}) | number | undefined;
  fontFeatureSettings?: (string & {}) | number | undefined;
  fontOpticalSizing?: (string & {}) | number | undefined;
  color?: (string & {}) | number | undefined;
  XPlaceholderColor?: (string & {}) | number | undefined;
  XPlaceholderFontFamily?: (string & {}) | number | undefined;
  XPlaceholderFontSize?: (string & {}) | number | undefined;
  XPlaceholderFontWeight?: (string & {}) | number | undefined;
  XPlaceholderFontStyle?: (string & {}) | number | undefined;
  opacity?: (string & {}) | number | undefined;
  display?: (string & {}) | number | undefined;
  /**
   * The `overflow` property specifies whether to clip the content when the content of an element is too big.
   *
   * **Syntax**: `<overflow-block>{1,2}`
   *
   * @see https://lynxjs.org/api/css/properties/overflow
   */
  overflow?: 'hidden' | 'visible' | (string & {}) | undefined;
  height?: (string & {}) | number | undefined;
  width?: (string & {}) | number | undefined;
  maxWidth?: (string & {}) | number | undefined;
  minWidth?: (string & {}) | number | undefined;
  /**
   * The `right` CSS property participates in specifying the horizontal position of a positioned element.
   *
   * **Syntax**: `<length-percentage> | auto`
   *
   * @see https://lynxjs.org/api/css/properties/right
   */
  right?: 'auto' | (string & {}) | 0 | undefined;
  maxHeight?: (string & {}) | number | undefined;
  minHeight?: (string & {}) | number | undefined;
  padding?: (string & {}) | number | undefined;
  paddingLeft?: (string & {}) | number | undefined;
  paddingRight?: (string & {}) | number | undefined;
  paddingTop?: (string & {}) | number | undefined;
  paddingBottom?: (string & {}) | number | undefined;
  margin?: (string & {}) | number | undefined;
  marginLeft?: (string & {}) | number | undefined;
  marginRight?: (string & {}) | number | undefined;
  /**
   * The `bottom` CSS property participates in specifying the vertical position.
   *
   * **Syntax**: `<length-percentage> | auto`
   *
   * @see https://lynxjs.org/api/css/properties/bottom
   */
  bottom?: 'auto' | (string & {}) | 0 | undefined;
  marginTop?: (string & {}) | number | undefined;
  marginBottom?: (string & {}) | number | undefined;
  whiteSpace?: (string & {}) | number | undefined;
  letterSpacing?: (string & {}) | number | undefined;
  textAlign?: (string & {}) | number | undefined;
  lineHeight?: (string & {}) | number | undefined;
  textOverflow?: (string & {}) | number | undefined;
  fontSize?: (string & {}) | number | undefined;
  fontWeight?: (string & {}) | number | undefined;
  flex?: (string & {}) | number | undefined;
  position?: (string & {}) | number | undefined;
  flexGrow?: (string & {}) | number | undefined;
  flexShrink?: (string & {}) | number | undefined;
  flexBasis?: (string & {}) | number | undefined;
  flexDirection?: (string & {}) | number | undefined;
  flexWrap?: (string & {}) | number | undefined;
  alignItems?: (string & {}) | number | undefined;
  alignSelf?: (string & {}) | number | undefined;
  alignContent?: (string & {}) | number | undefined;
  justifyContent?: (string & {}) | number | undefined;
  background?: (string & {}) | number | undefined;
  boxSizing?: (string & {}) | number | undefined;
  borderColor?: (string & {}) | number | undefined;
  fontFamily?: (string & {}) | number | undefined;
  fontStyle?: (string & {}) | number | undefined;
  transform?: (string & {}) | number | undefined;
  animation?: (string & {}) | number | undefined;
  animationName?: (string & {}) | number | undefined;
  animationDuration?: (string & {}) | number | undefined;
  animationTimingFunction?: (string & {}) | number | undefined;
  animationDelay?: (string & {}) | number | undefined;
  animationIterationCount?: (string & {}) | number | undefined;
  backgroundColor?: (string & {}) | number | undefined;
  animationDirection?: (string & {}) | number | undefined;
  animationFillMode?: (string & {}) | number | undefined;
  animationPlayState?: (string & {}) | number | undefined;
  lineSpacing?: (string & {}) | number | undefined;
  borderStyle?: (string & {}) | number | undefined;
  order?: (string & {}) | number | undefined;
  boxShadow?: (string & {}) | number | undefined;
  transformOrigin?: (string & {}) | number | undefined;
  linearOrientation?: (string & {}) | number | undefined;
  linearWeightSum?: (string & {}) | number | undefined;
  borderLeftColor?: (string & {}) | number | undefined;
  linearWeight?: (string & {}) | number | undefined;
  linearGravity?: (string & {}) | number | undefined;
  linearLayoutGravity?: (string & {}) | number | undefined;
  layoutAnimationCreateDuration?: (string & {}) | number | undefined;
  layoutAnimationCreateTimingFunction?: (string & {}) | number | undefined;
  layoutAnimationCreateDelay?: (string & {}) | number | undefined;
  layoutAnimationCreateProperty?: (string & {}) | number | undefined;
  layoutAnimationDeleteDuration?: (string & {}) | number | undefined;
  layoutAnimationDeleteTimingFunction?: (string & {}) | number | undefined;
  layoutAnimationDeleteDelay?: (string & {}) | number | undefined;
  borderRightColor?: (string & {}) | number | undefined;
  layoutAnimationDeleteProperty?: (string & {}) | number | undefined;
  layoutAnimationUpdateDuration?: (string & {}) | number | undefined;
  layoutAnimationUpdateTimingFunction?: (string & {}) | number | undefined;
  layoutAnimationUpdateDelay?: (string & {}) | number | undefined;
  adaptFontSize?: (string & {}) | number | undefined;
  aspectRatio?: (string & {}) | number | undefined;
  textDecoration?: (string & {}) | number | undefined;
  textShadow?: (string & {}) | number | undefined;
  /**
   * The `background-image` CSS property sets one or more background images on an element.
   *
   * **Syntax**: `<bg-image>#`
   *
   * @see https://lynxjs.org/api/css/properties/background-image
   */
  backgroundImage?: 'none' | (string & {}) | undefined;
  backgroundPosition?: (string & {}) | number | undefined;
}