# Copyright 2026 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.

import("../../testing/test.gni")
import("../Lynx.gni")

lynx_core_source_set("observer") {
  sources = [ "owned_observer_list.h" ]
}

unittest_set("observer_testset") {
  sources = [ "owned_observer_list_unittest.cc" ]
  public_deps = [ ":observer" ]
}

unittest_exec("observer_unittests_exec") {
  sources = []
  deps = [ ":observer_testset" ]
}
