name: install common dependencies

description: pull common source and binary dependencies via habitat.

inputs:
  concurrency:
    description: concurrency of requests
    default: '2'
    required: false
  skip-cache:
    description: whether to skip cache
    default: 'false'
    required: false

runs:
  using: composite
  steps:
    - name: setup cache action
      uses: lynx-infra/cache@main
      if: ${{ inputs.skip-cache == 'false' }}
      with:
        path: ~/.habitat_cache
        key: ${{ runner.os }}-${{ hashFiles('lynx/.habitat', 'lynx/DEPS') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: run habitat sync
      shell: bash
      working-directory: lynx
      run: |
        python3 -m pip install PyYAML
        python3 -m pip install requests
        tools/hab sync .
      env:
        HABITAT_CONCURRENCY: ${{ inputs.concurrency }}
