js_v8_bridge_platform_sources = []
if (is_mac || is_win) {
  js_v8_bridge_platform_sources +=
      rebase_path([
                    "v8_isolate_wrapper_node_impl.cc",
                    "v8_isolate_wrapper_node_impl.h",
                  ])
} else {
  js_v8_bridge_platform_sources +=
      rebase_path(
          [
            "//$lynx_dir/core/runtime/jsi/v8/v8_isolate_wrapper_node_impl.cc",
            "//$lynx_dir/core/runtime/jsi/v8/v8_isolate_wrapper_node_impl.h",
          ])
}

js_v8_bridge_shared_sources =
    rebase_path([
                  "../../jscache/v8/v8_cache_generator.cc",
                  "../../jscache/v8/v8_cache_generator.h",
                  "../../profile/v8/v8_runtime_profiler_wrapper.h",
                  "../../profile/v8/v8_runtime_profiler_wrapper_impl.cc",
                  "../../profile/v8/v8_runtime_profiler_wrapper_impl.h",
                  "v8_api.h",
                  "v8_context_wrapper.h",
                  "v8_context_wrapper_impl.cc",
                  "v8_context_wrapper_impl.h",
                  "v8_exception.cc",
                  "v8_exception.h",
                  "v8_helper.cc",
                  "v8_helper.h",
                  "v8_host_function.cc",
                  "v8_host_function.h",
                  "v8_host_object.cc",
                  "v8_host_object.h",
                  "v8_inspector_manager.h",
                  "v8_isolate_wrapper.h",
                  "v8_runtime.cc",
                  "v8_runtime.h",
                  "v8_platform_data.h",
                  "v8_platform_data.cc",
                ])

js_v8_bridge_shared_sources += js_v8_bridge_platform_sources
