# Copyright 2026 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.

import("../../../testing/test.gni")

benchmark_test("android_display_list_serializer_benchmark") {
  testonly = true
  sources = [ "android_display_list_serializer_benchmark.cc" ]
  deps = [
    "../../../core/renderer/dom/fragment:display_list",
    "../../../core/renderer/ui_wrapper/painting:android_display_list_item_serializer",
  ]
}
