# Copyright 2026 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.

declare_args() {
  # Path to a gperf executable for the build host, including cross builds.
  gperf_executable = ""
}

gperf_runner = get_path_info("gperf.py", "abspath")

if (gperf_executable == "") {
  gperf_executable = exec_script(gperf_runner,
                                 [
                                   "--find-gperf",
                                   rebase_path("//buildtools"),
                                 ],
                                 "trim string")
}
