name: ci

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - 'p/fenghao.0721/**'

defaults:
  run:
    working-directory: lynx

jobs:
  static-check:
    runs-on: lynx-ubuntu-22.04-avd-medium
    steps:
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Download Source
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.sha }}
          path: lynx
      - name: Install Common Dependencies
        uses: ./lynx/.github/actions/common-deps
      - name: Run file type check
        run: |
          source tools/envsetup.sh
          python3 tools_shared/git_lynx.py check --checkers file-type
      - name: Run cpplint check
        run: |
          source tools/envsetup.sh
          python3 tools_shared/git_lynx.py check --checkers cpplint
      - name: Run java-lint check
        run: |
          source tools/envsetup.sh
          python3 tools_shared/git_lynx.py check --checkers java-lint
      - name: Run commit-message check
        run: |
          source tools/envsetup.sh
          python3 tools_shared/git_lynx.py check --checkers commit-message
      - name: Run coding-style check
        run: |
          source tools/envsetup.sh
          python3 tools_shared/git_lynx.py check --checkers coding-style
      - name: Run android-check-style check
        run: |
          source tools/envsetup.sh
          python3 tools_shared/git_lynx.py check --checkers android-check-style

  darwin-native-unittests-check:
    runs-on: lynx-darwin-14-medium
    steps:
      - name: Download Source
        uses: actions/checkout@v4.2.2
        with:
          path: lynx
      - name: Debug
        run: |-
          whoami
          pwd
          while true; do echo "当前时间：$(date)"; sleep 5; done
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Common Dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |-
            set -e
            python3 -m venv myenv
            source myenv/bin/activate
            cd $GITHUB_WORKSPACE/lynx
            python3 -m pip install PyYAML -i https://pypi.org/simple
            tools/hab sync .
      - name: Run Unittests
        run: |
          set -e
          source ../myenv/bin/activate
          source tools/envsetup.sh
          tools/rtf/rtf native-ut run --names lynx
