name: ci

on:
  pull_request:
  push:
    branches:
      - CQ-*
      - cq-*

defaults:
  run:
    working-directory: lynx

jobs:
  windows-explorer-build:
    runs-on: lynx-windows-2022-large
    strategy:
      matrix:
        arch: [x86, x64]
    steps:
      - name: Configure Git
        shell: PowerShell
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global http.sslBackend "schannel"
        working-directory: ./
      - name: Download Source
        uses: actions/checkout@v4.2.2
        with:
          path: lynx
      - name: Build windows Explorer
        uses: ./lynx/.github/actions/windows-explorer-build
        with:
          build-arch: ${{ matrix.arch }}

  macos-explorer-build:
    timeout-minutes: 60
    runs-on: lynx-darwin-14-medium
    strategy:
      matrix:
        arch: [arm64, x64]
    steps:
      - name: Download Source
        uses: actions/checkout@v4.2.2
        with:
          path: lynx
      - name: Build macOS Explorer
        uses: ./lynx/.github/actions/macos-explorer-build
        with:
          build-arch: ${{ matrix.arch }}
      # - name: upload artifact
      #   uses: lynx-infra/upload-artifact@332ec52e99f7cbf1fbbdc9bcc09280d49147d092
      #   with:
      #     name: macos-explorer-build-${{ matrix.arch }}
      #     path: '${{ github.workspace }}/lynx/LynxExplorer-macos-${{ matrix.arch }}.app.tar.gz'
