name: ci

on:
  pull_request:
  push:
    branches:
      - CQ-*

defaults:
  run:
    working-directory: lynx

jobs:
  ios-sdk-publish:
    timeout-minutes: 60
    runs-on: lynx-darwin-14-medium
    steps:
      - name: Download Source
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.sha }}
          path: lynx
      - name: Install Common Dependencies
        uses: ./lynx/.github/actions/common-deps
        with:
          cache-backend: 'lynx-infra'
      - name: Setup Ruby Cache
        uses: ./lynx/.github/actions/ios-common-deps
      - name: Publish iOS SDK
        uses: ./lynx/.github/actions/ios-sdk-publish
        with:
          version: '3.5.1'
          tag: '3.5.1'
          cocoapods_trunk_token: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          component: LynxService
      - name: Publish iOS SDK
        uses: ./lynx/.github/actions/ios-sdk-publish
        with:
          version: '3.5.1'
          tag: '3.5.1'
          cocoapods_trunk_token: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          component: XElement
      - name: Publish iOS dev SDK
        uses: ./lynx/.github/actions/ios-sdk-publish
        env:
          LYNX_ENABLE_RECORDER: 1
        with:
          version: 3.5.1-dev
          tag: '3.5.1'
          cocoapods_trunk_token: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          component: all
