name: issue_management
on:
  issues:
    types:
      - opened
      - assigned

permissions:
  issues: write

jobs:
  add-label-triage:
    timeout-minutes: 30
    runs-on: lynx-ubuntu-22.04-mini
    if: github.event.action == 'opened' # Only run for 'opened' event
    steps:
      - name: Add 'status:need triage' label to new issues
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            await github.rest.issues.addLabels({
              ...context.issue,
              labels: ['status:need triage'],
            })

  update-label-assigned:
    timeout-minutes: 30
    runs-on: lynx-ubuntu-22.04-mini
    if: github.event.action == 'assigned' # Only run for 'assigned' event
    steps:
      - name: Update status labels
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            try {
              await github.rest.issues.removeLabel({
                ...context.issue,
                name: 'status:need triage',
              })
            } catch (error) {
              if (error.status !== 404) throw error
            }
            await github.rest.issues.addLabels({
              ...context.issue,
              labels: ['status:assigned'],
            })
