name: publish-release
on:
  workflow_call:
    inputs:
      dry-run:
        required: true
        type: boolean
      version:
        required: false
        type: string

jobs:
  ios-sdk-publish:
    runs-on: lynx-darwin-14-medium
    if: ${{ inputs.dry-run == false }}
    steps:
      - name: Download Source
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.sha }}
          path: lynx
      - name: Install Common Dependencies
        uses: ./lynx/.github/actions/common-deps
        with:
          cache-backend: 'lynx-infra'
      - name: Setup Ruby Cache
        uses: ./lynx/.github/actions/ios-common-deps
      - name: Prepare cocoapods publish source
        run: |-
          cd $GITHUB_WORKSPACE/lynx
          source tools/envsetup.sh
          cd $GITHUB_WORKSPACE
          python3 lynx/tools/ios_tools/cocoapods_publish_helper.py --prepare-source --tag ${{ inputs.version }} --component all
      - name: Push iOS SDK to release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: '*.zip'
          replacesArtifacts: true
          allowUpdates: true
      - name: Publish to CocoaPods Repo
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |-
          cd $GITHUB_WORKSPACE/lynx
          source tools/envsetup.sh
          cd $GITHUB_WORKSPACE
          git config --global user.name "lynx.authors"
          git config --global user.email "lynx.authors@users.noreply.github.com"
          python3 lynx/tools/ios_tools/skip_pod_lint.py --source public
          python3 lynx/tools/ios_tools/cocoapods_publish_helper.py --publish --component all  --tag ${{ inputs.version }}
