name: type_config_publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The npm tag to publish with.'
        required: false
        default: 'latest'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  type_config_publish:
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download Source
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
          path: lynx
      - name: Python Setup
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: '3.13'
      - name: Install Common Dependencies
        uses: ./lynx/.github/actions/common-deps
        with:
          cache-backend: github
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: 'lynx/.node-version'

          registry-url: 'https://registry.npmjs.org'
      - name: Build
        run: |-
          cd $GITHUB_WORKSPACE/lynx
          source tools/envsetup.sh
      - name: Update version for non-latest tags
        if: github.event.inputs.tag != 'latest'
        run: |
          cd $GITHUB_WORKSPACE/lynx/js_libraries/type-config
          npm version prerelease --preid=${{ github.event.inputs.tag }} --no-git-tag-version
      - name: Test
        run: |-
          cd $GITHUB_WORKSPACE/lynx/js_libraries/type-config
          npm test
      - name: Publish
        run: |-
          cd $GITHUB_WORKSPACE/lynx/js_libraries/type-config
          npm publish --access public --provenance --tag ${{ github.event.inputs.tag }}
